import type { EvidenceTier } from './types';

export type CompareVerdict = 'a' | 'b' | 'tie' | 'context';

export interface CompareRow {
  dimension: string;
  a: string;
  b: string;
  verdict: CompareVerdict;
  pmid?: string;
  note?: string;
}

export interface EvidenceComparison {
  slug: string;
  title: string;
  subtitle: string;
  labelA: string;
  labelB: string;
  category: 'compound' | 'stack' | 'form';
  evidenceTier: EvidenceTier;
  summary: string;
  verdict: string;
  rows: CompareRow[];
  whenChooseA: string[];
  whenChooseB: string[];
  relatedHrefs: { label: string; href: string }[];
  keywords: string[];
}

export const evidenceComparisons: EvidenceComparison[] = [
  {
    slug: 'nmn-vs-nr',
    title: 'NMN vs NR',
    subtitle: 'Two NAD+ precursors — same destination, different trial footprints',
    labelA: 'NMN',
    labelB: 'NR (Nicotinamide Riboside)',
    category: 'compound',
    evidenceTier: 'A',
    summary:
      'Both raise NAD+ metabolites in humans. TNiC standardizes on NMN for stack integration and Igarashi/Liao trial dosing. NR is defensible — do not combine high doses without physician oversight.',
    verdict:
      'Tie on core NAD+ restoration. Choose NMN if you run TNiC stacks (SIRT1 pair, Mito Stack). Choose NR if your physician prefers NR-specific literature or you already respond well.',
    rows: [
      {
        dimension: 'Human NAD+ elevation',
        a: 'Multiple RCTs — 250 mg/day',
        b: 'Multiple RCTs — 300–1000 mg/day',
        verdict: 'tie',
        pmid: '36482258',
      },
      {
        dimension: 'NAMPT bypass',
        a: 'Direct precursor in salvage pathway',
        b: 'NR → NMN → NAD+ (extra step)',
        verdict: 'context',
        note: 'Mechanistic debate — both work in humans',
      },
      {
        dimension: 'TNiC stack integration',
        a: 'Native in all NAD+ presets',
        b: 'Manual substitution required',
        verdict: 'a',
      },
      {
        dimension: 'Typical consumer dose',
        a: '250–500 mg/day',
        b: '300–1000 mg/day',
        verdict: 'tie',
      },
      {
        dimension: 'Cost per trial-matched month',
        a: 'Moderate',
        b: 'Moderate–premium',
        verdict: 'tie',
      },
      {
        dimension: 'Combine both?',
        a: 'Not recommended high-dose combo',
        b: 'Not recommended high-dose combo',
        verdict: 'tie',
        note: 'Physician oversight if stacking precursors',
      },
      {
        dimension: 'Buyer verification',
        a: 'β-NMN identity + ≥98% HPLC',
        b: 'NR-Cl identity + ≥98% HPLC',
        verdict: 'context',
        note: 'Different COA targets — see compound buyer guides',
      },
      {
        dimension: 'NR-specific human RCT',
        a: 'Igarashi/Liao 250 mg NMN',
        b: 'Martens 1000 mg NR',
        verdict: 'b',
        pmid: '29514064',
        note: 'Both elevate NAD+ — dose units differ',
      },
    ],
    whenChooseA: [
      'Running TNiC SIRT1 or Mito stacks',
      'Matching Igarashi 250 mg protocol exactly',
      'Already have NMN COA and week-4 NAD+ baseline',
    ],
    whenChooseB: [
      'Physician already prescribed NR',
      'Prior positive NR response with NAD+ metabolite proof',
      'NR-specific brand with verified NR-Cl purity you trust',
    ],
    relatedHrefs: [
      { label: 'NMN deep dive', href: '/library/compounds/nmn' },
      { label: 'NR deep dive', href: '/library/compounds/nr' },
      { label: 'NMN buyer guide', href: '/library/compounds/nmn#buyer-guide' },
      { label: 'NR buyer guide', href: '/library/compounds/nr#buyer-guide' },
      { label: 'NAD+ Mito Stack', href: '/library/synergies/nad-mito-stack' },
      { label: 'NR shop verification', href: '/shop?stack=nr' },
      { label: 'NMN vs Spermidine', href: '/library/compare/nmn-vs-spermidine' },
    ],
    keywords: ['nmn', 'nr', 'nicotinamide riboside', 'nad+', 'precursor'],
  },
  {
    slug: 'glynac-vs-liposomal-glutathione',
    title: 'GlyNAC vs Liposomal Glutathione',
    subtitle: 'Rebuild vs replace — synthesis beats swallowing GSH',
    labelA: 'GlyNAC (precursors)',
    labelB: 'Liposomal GSH',
    category: 'form',
    evidenceTier: 'A',
    summary:
      'GlyNAC has Tier A human RCTs restoring erythrocyte GSH over 24 weeks. Liposomal glutathione raises plasma GSH acutely but lacks equivalent longevity-trial depth.',
    verdict:
      'GlyNAC wins for evidence-backed stack foundation. Liposomal GSH may help short-term rescue if tolerance or compliance blocks NAC.',
    rows: [
      {
        dimension: 'Human RCT longevity markers',
        a: '24-week GSH restoration (Kumar)',
        b: 'Acute plasma rise; limited long-term trials',
        verdict: 'a',
        pmid: '34129059',
      },
      {
        dimension: 'Mechanism',
        a: 'Endogenous synthesis — both limiting precursors',
        b: 'Exogenous GSH — digestion limits intact absorption',
        verdict: 'a',
      },
      {
        dimension: 'Cost efficiency',
        a: 'Moderate — dual precursor',
        b: 'Premium — liposomal premium pricing',
        verdict: 'a',
      },
      {
        dimension: 'GI tolerance',
        a: 'NAC sulfur odor; start low',
        b: 'Often better tolerated',
        verdict: 'b',
      },
      {
        dimension: 'NRF2 stack fit',
        a: 'Designed substrate for sulforaphane',
        b: 'Orthogonal — does not replace glycine need',
        verdict: 'a',
      },
      {
        dimension: 'Biomarker target',
        a: 'Erythrocyte GSH',
        b: 'Plasma GSH (transient)',
        verdict: 'a',
      },
    ],
    whenChooseA: [
      'Building NRF2 Defense or Full Hybrid stack',
      'GSH below 5.0 μmol/L on labs',
      'Age 50+ with oxidative stress lifestyle',
    ],
    whenChooseB: [
      'Cannot tolerate NAC after titration',
      'Short-term pre-surgery or acute oxidative stress (physician guided)',
      'Bridge week while transitioning to GlyNAC',
    ],
    relatedHrefs: [
      { label: 'GlyNAC deep dive', href: '/library/compounds/glynac' },
      { label: 'NRF2 Defense Triad', href: '/library/synergies/glynac-nrf2-triad' },
      { label: 'Testing guide', href: '/library/guides/testing-and-monitoring' },
    ],
    keywords: ['glynac', 'glutathione', 'liposomal', 'gsh', 'nac'],
  },
  {
    slug: 'sulforaphane-vs-curcumin',
    title: 'Sulforaphane vs Curcumin',
    subtitle: 'NRF2 covalent switch vs indirect inflammation modulation',
    labelA: 'Sulforaphane',
    labelB: 'Curcumin',
    category: 'compound',
    evidenceTier: 'A',
    summary:
      'Sulforaphane covalently modifies KEAP1, releasing NRF2 to drive 200+ cytoprotective genes. Curcumin modulates NF-κB and inflammation but has poor bioavailability and weaker NRF2 activation data.',
    verdict:
      'Sulforaphane wins for NRF2-primary stacks and hs-CRP reduction paired with GlyNAC. Curcumin is adjunct anti-inflammatory — not a substitute for KEAP1 pathway activation.',
    rows: [
      {
        dimension: 'NRF2 activation mechanism',
        a: 'KEAP1 covalent modification — direct',
        b: 'Indirect; weak KEAP1 data',
        verdict: 'a',
        pmid: '18454171',
      },
      {
        dimension: 'Bioavailability',
        a: 'Requires myrosinase conversion',
        b: 'Poor native; needs piperine/phytosome',
        verdict: 'context',
      },
      {
        dimension: 'hs-CRP evidence',
        a: 'Strong when paired with lifestyle + GlyNAC',
        b: 'Mixed meta-analyses',
        verdict: 'a',
      },
      {
        dimension: 'Gene programs induced',
        a: 'NQO1, GST, HO-1, proteasome subunits',
        b: 'NF-κB, COX-2 modulation',
        verdict: 'a',
      },
      {
        dimension: 'TNiC stack role',
        a: 'Core NRF2 Defense compound',
        b: 'Not in TNiC presets',
        verdict: 'a',
      },
      {
        dimension: 'Buyer verification',
        a: 'GR + myrosinase quantified',
        b: 'Curcuminoid % + absorption tech',
        verdict: 'tie',
      },
    ],
    whenChooseA: [
      'Genomic instability or inflammation hallmarks primary',
      'Running NRF2 Defense stack',
      'hs-CRP above 1.0 mg/L',
    ],
    whenChooseB: [
      'Joint pain / NF-κB inflammation focus with physician plan',
      'Cannot source quality sulforaphane with myrosinase',
      'Adjunct only — not NRF2 foundation',
    ],
    relatedHrefs: [
      { label: 'Sulforaphane deep dive', href: '/library/compounds/sulforaphane' },
      { label: 'Chronic inflammation hallmark', href: '/library/chronic-inflammation' },
    ],
    keywords: ['sulforaphane', 'curcumin', 'nrf2', 'crp', 'inflammation'],
  },
  {
    slug: 'resveratrol-vs-pterostilbene',
    title: 'Trans-Resveratrol vs Pterostilbene',
    subtitle: 'SIRT1 activators — methoxy groups change absorption, not certainty',
    labelA: 'Trans-Resveratrol',
    labelB: 'Pterostilbene',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      'Resveratrol has longer human exposure history and SIRT1 literature. Pterostilbene is more lipophilic with longer half-life in preclinical models — human longevity outcomes for both remain Tier B.',
    verdict:
      'Resveratrol wins for TNiC SIRT1 stack parity with published NMN pairings. Pterostilbene is experimental swap — only with NAD+ monitoring and physician awareness.',
    rows: [
      {
        dimension: 'SIRT1 activation data',
        a: 'Extensive in-vitro + human pilot exposure',
        b: 'Strong preclinical; fewer human trials',
        verdict: 'a',
        pmid: '17909917',
      },
      {
        dimension: 'Oral bioavailability',
        a: 'Low — needs fat + micronization',
        b: 'Higher lipophilicity in models',
        verdict: 'b',
      },
      {
        dimension: 'TNiC stack integration',
        a: 'Native PM pair in SIRT1 preset',
        b: 'Manual substitution',
        verdict: 'a',
      },
      {
        dimension: 'Typical dose',
        a: '150–500 mg trans-resveratrol',
        b: '50–150 mg pterostilbene',
        verdict: 'context',
      },
      {
        dimension: 'Evidence tier (longevity)',
        a: 'Tier B',
        b: 'Tier B',
        verdict: 'tie',
      },
      {
        dimension: 'Drug interactions',
        a: 'CYP substrates — physician review',
        b: 'Similar CYP caution',
        verdict: 'tie',
      },
    ],
    whenChooseA: [
      'Running NMN + resveratrol SIRT1 stack',
      'Matching TNiC timing choreography (AM NMN, PM resveratrol)',
    ],
    whenChooseB: [
      'GI intolerance to resveratrol at 300+ mg',
      'Physician-supervised swap with biomarker tracking',
    ],
    relatedHrefs: [
      { label: 'Resveratrol deep dive', href: '/library/compounds/resveratrol' },
      { label: 'SIRT1 synergy guide', href: '/library/synergies/nmn-resveratrol-sirt1' },
    ],
    keywords: ['resveratrol', 'pterostilbene', 'sirt1', 'nad+'],
  },
  {
    slug: 'nrf2-triad-vs-mito-stack',
    title: 'NRF2 Triad vs NAD+ Mito Stack',
    subtitle: 'Antioxidant gene switch first, or mitochondrial fuel first?',
    labelA: 'NRF2 Defense Triad',
    labelB: 'NAD+ Mito Stack',
    category: 'stack',
    evidenceTier: 'A',
    summary:
      'NRF2 Triad (GlyNAC + sulforaphane + R-ALA) rebuilds redox defense and lowers inflammaging. NAD+ Mito Stack (NMN + Ca-AKG + resveratrol) restores mitochondrial fuel and SIRT signaling.',
    verdict:
      'Start NRF2 Triad if GSH or hs-CRP are off-target. Start Mito Stack if NAD+ is low and energy/mitochondrial hallmark leads. Full Hybrid combines both — higher cost, maximum coverage.',
    rows: [
      {
        dimension: 'Primary hallmarks',
        a: 'Inflammation, genomic, proteostasis',
        b: 'Mitochondrial, epigenetic, nutrient sensing',
        verdict: 'context',
      },
      {
        dimension: 'Lead biomarkers',
        a: 'GSH, hs-CRP',
        b: 'NAD+ index, resting HR',
        verdict: 'context',
      },
      {
        dimension: 'Compound count',
        a: '3 OTC',
        b: '3 OTC',
        verdict: 'tie',
      },
      {
        dimension: 'Monthly cost',
        a: 'Moderate',
        b: 'Moderate–premium',
        verdict: 'a',
      },
      {
        dimension: 'Evidence backbone',
        a: 'Kumar GlyNAC RCT + NRF2 literature',
        b: 'Igarashi NMN RCT + AKG mouse data',
        verdict: 'tie',
        pmid: '34129059',
      },
      {
        dimension: 'Quiz preset mapping',
        a: 'Inflammation / defense goals',
        b: 'Energy / mitochondrial goals',
        verdict: 'context',
      },
    ],
    whenChooseA: [
      'hs-CRP above 1.0 or GSH below 5.0',
      'Quiz result: inflammation or defense focus',
      'Age 55+ with oxidative lifestyle',
    ],
    whenChooseB: [
      'NAD+ below 80 or morning energy ≤5/10',
      'Quiz result: energy / mitochondrial focus',
      'Already optimized sleep + Zone 2',
    ],
    relatedHrefs: [
      { label: 'NRF2 Triad guide', href: '/library/synergies/glynac-nrf2-triad' },
      { label: 'NAD+ Mito Stack', href: '/library/synergies/nad-mito-stack' },
      { label: 'Stack Architect', href: '/stacks' },
    ],
    keywords: ['nrf2', 'mito', 'stack', 'glynac', 'nmn'],
  },
  {
    slug: 'starter-elite-vs-full-hybrid',
    title: 'Starter Elite vs Full Hybrid',
    subtitle: 'Entry stack vs maximum hallmark coverage',
    labelA: 'Starter Elite',
    labelB: 'Full Hybrid',
    category: 'stack',
    evidenceTier: 'A',
    summary:
      'Starter Elite is the lowest-friction entry: GlyNAC + NMN + sulforaphane. Full Hybrid adds resveratrol, Ca-AKG, and R-ALA for dual-pathway coverage — more pills, more monitoring.',
    verdict:
      'Starter Elite wins for first-time stackers and quiz onboarding. Full Hybrid wins when baseline labs justify dual-pathway spend and compliance is proven at 12 weeks.',
    rows: [
      {
        dimension: 'Compounds',
        a: '3',
        b: '6',
        verdict: 'a',
        note: 'Simplicity score higher on Starter',
      },
      {
        dimension: 'Monthly cost',
        a: 'Budget–moderate',
        b: 'Premium',
        verdict: 'a',
      },
      {
        dimension: 'Hallmark coverage',
        a: 'Core 6 hallmarks',
        b: '10+ hallmarks',
        verdict: 'b',
      },
      {
        dimension: 'Monitoring burden',
        a: 'GSH + NAD+ + CRP',
        b: 'Full Tier 1 + Tier 2 panel',
        verdict: 'a',
      },
      {
        dimension: 'Compliance risk',
        a: 'Low',
        b: 'Moderate–high',
        verdict: 'a',
      },
      {
        dimension: 'Upgrade path',
        a: '→ SIRT1 or Full Hybrid at week 12',
        b: 'Maintenance after lab confirmation',
        verdict: 'context',
      },
    ],
    whenChooseA: [
      'First longevity stack ever',
      '3-Min Quiz beginner path',
      'Want results before maximizing spend',
    ],
    whenChooseB: [
      '12+ weeks compliance on Starter Elite',
      'Multiple hallmarks off-target on labs',
      'Budget for premium monitoring cadence',
    ],
    relatedHrefs: [
      { label: 'Stack Architect', href: '/stacks' },
      { label: '3-Min Quiz', href: '/quiz' },
      { label: 'Testing guide', href: '/library/guides/testing-and-monitoring' },
    ],
    keywords: ['starter', 'hybrid', 'stack', 'beginner'],
  },
  {
    slug: 'berberine-vs-metformin',
    title: 'Berberine vs Metformin',
    subtitle: 'Head-to-head RCT showed comparable glucose outcomes — one is a prescription drug, one is not',
    labelA: 'Berberine HCl',
    labelB: 'Metformin',
    category: 'compound',
    evidenceTier: 'A',
    summary:
      'A 2008 Metabolism RCT (PMID 18396172) randomized 116 T2D patients to berberine 500 mg TID vs metformin 500 mg TID for 13 weeks. Berberine reduced fasting glucose 20% and HbA1c by 2.0% — outcomes statistically equivalent to metformin at the same dose. Both activate AMPK, the cellular energy sensor that also inhibits mTOR and supports longevity pathways. The key difference: metformin is a prescription biguanide with known B12 depletion risk and contraindications in renal impairment; berberine is a consumer-accessible alkaloid with a favorable safety profile and additional lipid benefits not seen with metformin.',
    verdict:
      'Tie on acute glucose control (head-to-head RCT). Choose berberine for consumer accessibility, lipid co-benefits, and absence of B12 depletion. Choose metformin if your physician recommends it for T2D management or you are in the TAME trial longevity cohort — do not self-combine both at full dose (additive hypoglycemia risk).',
    rows: [
      {
        dimension: 'Fasting glucose reduction',
        a: '−20% (13-week RCT, n=116)',
        b: '−23% (same trial, same dose)',
        verdict: 'tie',
        pmid: '18396172',
        note: 'Difference not statistically significant — berberine non-inferior',
      },
      {
        dimension: 'HbA1c reduction',
        a: '−2.0 percentage points',
        b: '−1.8 percentage points',
        verdict: 'a',
        pmid: '18396172',
      },
      {
        dimension: 'LDL cholesterol',
        a: '−13.5% (meta-analysis, 27 RCTs)',
        b: 'Neutral to modest reduction',
        verdict: 'a',
        pmid: '26507383',
        note: "Berberine's lipid benefit is a meaningful advantage for CV risk reduction",
      },
      {
        dimension: 'Triglycerides',
        a: '−35% in dyslipidemia trials',
        b: 'Minimal effect',
        verdict: 'a',
        pmid: '26507383',
      },
      {
        dimension: 'AMPK activation (longevity pathway)',
        a: 'Direct AMPK activator — inhibits mTORC1',
        b: 'Direct AMPK activator via Complex I inhibition',
        verdict: 'tie',
        note: 'Both mimic caloric restriction signaling at the AMPK node',
      },
      {
        dimension: 'Vitamin B12 depletion',
        a: 'Not observed in trials',
        b: 'Documented — requires monitoring',
        verdict: 'a',
        note: 'Metformin blocks B12 absorption in terminal ileum; cumulative risk at 5+ years',
      },
      {
        dimension: 'Renal contraindication',
        a: 'No renal cutoff established',
        b: 'Contraindicated eGFR <30; caution <45',
        verdict: 'a',
      },
      {
        dimension: 'Prescription required',
        a: 'No — consumer accessible',
        b: 'Yes — physician prescription',
        verdict: 'context',
        note: 'Metformin may be the right choice when diabetes management requires physician oversight',
      },
      {
        dimension: 'Muscle hypertrophy interference',
        a: 'Not reported',
        b: 'Blocks exercise-induced mTORC1/MAPK — attenuates muscle gains',
        verdict: 'a',
        pmid: '32910831',
        note: 'Significant tradeoff for physically active users targeting body composition',
      },
      {
        dimension: 'Gut microbiome',
        a: 'Reshapes toward Lactobacillus, reduces Firmicutes:Bacteroidetes',
        b: 'Also reshapes microbiome — mechanisms overlap',
        verdict: 'tie',
      },
      {
        dimension: 'Longevity trial evidence',
        a: 'No dedicated longevity RCT yet',
        b: 'TAME trial underway (n=3,000) — targeting aging directly',
        verdict: 'b',
        pmid: '32910831',
        note: 'TAME is the first FDA-approved trial targeting aging as an indication — metformin leads here',
      },
      {
        dimension: 'Bioavailability standard form',
        a: 'Berberine HCl ~36%; dihydroberberine 5× higher',
        b: 'Standard oral — well-established PK',
        verdict: 'context',
        note: 'Upgrade to dihydroberberine (BPEL) formulation to close the bioavailability gap',
      },
    ],
    whenChooseA: [
      'No T2D diagnosis — seeking metabolic and longevity benefits without a prescription',
      'Physically active — want AMPK benefits without metformin\'s mTORC1/muscle interference',
      'Elevated LDL or triglycerides — berberine adds meaningful lipid benefits metformin does not',
      'Long-term use — avoiding B12 depletion risk without supplemental monitoring',
      'Stacking with TNiC longevity protocol (R-ALA, resveratrol, omega-3 — synergistic with berberine AMPK axis)',
    ],
    whenChooseB: [
      'Physician-managed T2D requiring proven first-line pharmacological intervention',
      'Enrolled or eligible for the TAME longevity trial (metformin-specific)',
      'Prefer FDA-regulated pharmaceutical with decades of post-market safety data',
      'Cost is the primary constraint — generic metformin is extremely low cost',
    ],
    relatedHrefs: [
      { label: 'Berberine in Library', href: '/library/berberine' },
      { label: 'Stack Architect', href: '/stacks' },
      { label: 'Nutrient Sensing Hallmark', href: '/library/hallmarks/nutrient' },
    ],
    keywords: ['berberine', 'metformin', 'ampk', 'glucose', 'metabolic', 'diabetes', 'longevity'],
  },
  {
    slug: 'urolithina-vs-coq10',
    title: 'Urolithin A vs CoQ10',
    subtitle: 'Both target mitochondrial aging — but at completely different points in the process',
    labelA: 'Urolithin A (Mitopure)',
    labelB: 'CoQ10 (Ubiquinol)',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      'Urolithin A and CoQ10 are frequently compared as "mitochondrial supplements" — but they operate at entirely different levels of mitochondrial biology. CoQ10 is an electron transport chain cofactor: it fuels existing mitochondria by shuttling electrons between Complex I/II and Complex III. Urolithin A activates mitophagy: it removes the damaged mitochondria that can no longer function well enough for CoQ10 to help. These are not competing interventions — they are complementary. The question is which problem you are solving first.',
    verdict:
      'Choose urolithin A if your primary goal is clearing dysfunctional mitochondria via mitophagy — especially post-45 with fatigue or declining muscle function. Choose CoQ10 if you are on a statin (obligatory repletion), have cardiovascular history, or want ETC support with strong safety data. Stack both for comprehensive mitochondrial coverage.',
    rows: [
      {
        dimension: 'Mechanism',
        a: 'PINK1/Parkin mitophagy activation — removes damaged mitochondria',
        b: 'ETC electron shuttle at Complex I/II → III — fuels existing mitochondria',
        verdict: 'context',
        note: 'Upstream (cleanup) vs downstream (fuel) — orthogonal, not competing',
      },
      {
        dimension: 'Human trial evidence',
        a: 'Phase 2 RCT (Ryu 2022, PMID 35391504) — muscle strength and mitophagy gene expression confirmed in biopsy',
        b: 'Meta-analysis 17 RCTs (Liang 2016, PMID 26267690) — hs-CRP and IL-6 reduction; Q-SYMBIO RCT for heart failure',
        verdict: 'tie',
        note: 'Both have Tier A-level evidence in their respective primary endpoints',
      },
      {
        dimension: 'Statin users',
        a: 'Not indicated for statin depletion',
        b: 'Obligatory — statins block HMG-CoA reductase which synthesizes CoQ10 endogenously',
        verdict: 'b',
        note: 'If on any statin, CoQ10 is the priority. Non-negotiable repletion.',
      },
      {
        dimension: 'Muscle function (≥65)',
        a: 'Phase 2 RCT primary endpoint: significant improvement in handgrip and leg press',
        b: 'Indirect — ETC support contributes to muscle energy but not primary endpoint',
        verdict: 'a',
        pmid: '35391504',
      },
      {
        dimension: 'Cardiovascular benefit',
        a: 'Not primary indication',
        b: 'Q-SYMBIO: 43% MACE reduction in heart failure; REDUCE-IT context (CoQ10 membrane + omega-3)',
        verdict: 'b',
        pmid: '29541041',
      },
      {
        dimension: 'Dietary accessibility',
        a: 'Only ~40% of people have gut microbiome to produce UA from food — supplement dependency high',
        b: 'Endogenous synthesis possible; ubiquinone in many foods; but declines with age',
        verdict: 'context',
        note: 'UA requires standardized Mitopure to bypass gut conversion limitation',
      },
      {
        dimension: 'Fat co-ingestion requirement',
        a: 'Yes — take with fat-containing meal',
        b: 'Yes — lipid-soluble, requires dietary fat',
        verdict: 'tie',
        note: 'Both are fat-soluble; breakfast is the ideal timing for both',
      },
      {
        dimension: 'Senescent cell coverage',
        a: 'Indirect — mitophagy reduces mitochondria-driven ROS that promotes senescence',
        b: 'Indirect — ROS reduction via ETC efficiency reduces senescence trigger signals',
        verdict: 'a',
        note: "Urolithin A's mitophagy mechanism has a more direct senescence pathway link",
      },
      {
        dimension: 'Safety profile',
        a: 'Phase 1 + 2: no serious adverse events at 250–2000 mg across 5 months',
        b: 'Decades of clinical use; excellent profile; warfarin interaction at high dose',
        verdict: 'tie',
      },
      {
        dimension: 'Cost-effectiveness',
        a: 'Mitopure is premium — standardization is essential but carries premium pricing',
        b: 'Generic ubiquinol well-characterized; CoQ10 cost has fallen significantly',
        verdict: 'b',
        note: 'For budget-constrained stacks, CoQ10 delivers strong ETC support at lower cost',
      },
    ],
    whenChooseA: [
      'Age ≥45 with declining muscle recovery, endurance, or unexplained fatigue',
      'Building a senescence/healthspan protocol — mitophagy clearance as the core mechanism',
      'Not on statins — the statin-depletion rationale for CoQ10 does not apply',
      'Adding to an NMN stack — urolithin A clears damaged mitochondria that NMN alone cannot rehabilitate',
      'Low dietary urolithin A conversion suspected (most Western adults fall in this category)',
    ],
    whenChooseB: [
      'On any statin medication — CoQ10 repletion is obligatory, not optional',
      'Cardiovascular disease history — Q-SYMBIO data supports MACE reduction in HF',
      'Muscle fatigue or myalgia on statins — the most actionable CoQ10 use case',
      'Budget-constrained — CoQ10 delivers Tier B mitochondrial support at substantially lower cost than Mitopure',
    ],
    relatedHrefs: [
      { label: 'Urolithin A in Library', href: '/library/compounds/urolithina' },
      { label: 'CoQ10 in Library', href: '/library/compounds/coq10' },
      { label: 'Mitochondrial Dysfunction hallmark', href: '/library/mitochondrial-dysfunction' },
      { label: 'NMN vs Spermidine', href: '/library/compare/nmn-vs-spermidine' },
    ],
    keywords: ['urolithin a', 'coq10', 'mitochondria', 'mitophagy', 'statin', 'energy', 'aging'],
  },
  {
    slug: 'nmn-vs-spermidine',
    title: 'NMN vs Spermidine',
    subtitle: 'Two longevity starters — NAD⁺ repletion vs direct autophagy induction',
    labelA: 'NMN',
    labelB: 'Spermidine',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      'NMN restores NAD⁺ levels that decline ~50% by age 60, fueling SIRT1-mediated DNA repair and mitochondrial biogenesis. Spermidine inhibits the acetyltransferase EP300, directly triggering autophagy — the cellular recycling process that clears damaged proteins and organelles. Both are credible longevity starters but act at entirely different nodes; stacking them provides complementary coverage rather than redundancy.',
    verdict:
      'NMN leads on NAD⁺-sensitive domains: DNA repair, mitochondrial biogenesis, vascular endothelium. Spermidine leads on autophagy flux and immune T-cell rejuvenation. Do not force a choice — the Full Hybrid and Full-Spectrum 14 stacks include both for orthogonal pathway coverage.',
    rows: [
      {
        dimension: 'Primary mechanism',
        a: 'NAD⁺ repletion → SIRT1 / PARP1 / CD38 axis activation',
        b: 'EP300 acetyltransferase inhibition → autophagy induction',
        verdict: 'context',
        note: 'Mechanistically orthogonal — not competing for the same target',
      },
      {
        dimension: 'Human RCT evidence',
        a: 'Multiple RCTs — Liao 2021, Igarashi 2022; 250–500 mg/day',
        b: 'Observational cohort (n=829, Kiechl 2018) + Phase II hair trial',
        verdict: 'a',
        pmid: '34631532',
        note: 'NMN has stronger double-blind interventional footprint',
      },
      {
        dimension: 'Autophagy induction',
        a: 'Indirect — SIRT1 deacetylates FOXO3a to upregulate autophagy genes',
        b: 'Direct — EP300 inhibition mimics caloric restriction signaling at low doses',
        verdict: 'b',
        pmid: '28026137',
        note: 'Spermidine triggers robust autophagy flux at 1 mg/day dietary-equivalent dosing',
      },
      {
        dimension: 'NAD⁺ restoration',
        a: '38% whole-blood NAD⁺ increase at 250 mg/day (Liao 2021)',
        b: 'None — polyamine mechanism is independent of NAD⁺ metabolism',
        verdict: 'a',
        pmid: '34631532',
      },
      {
        dimension: 'Cardiovascular aging',
        a: 'Endothelial NAD⁺ deficit is a validated vascular aging target',
        b: 'Cardiac hypertrophy reversal in aged hearts; human cohort CV mortality data',
        verdict: 'tie',
        pmid: '30975980',
        note: 'Distinct benefits at different vascular targets — both additive in Full Hybrid',
      },
      {
        dimension: 'Immune T-cell rejuvenation',
        a: 'Moderate — NAD⁺ is required for T-cell activation and metabolic fitness',
        b: 'High — autophagy restores T-cell mitochondria, reversing CD8⁺ exhaustion',
        verdict: 'b',
        pmid: '28026137',
        note: 'Puleston 2016: spermidine-induced autophagy rescues aged CD8⁺ memory T-cells',
      },
      {
        dimension: 'Epigenetic aging impact',
        a: 'SIRT1 histone deacetylation — broad epigenetic maintenance and clock improvement',
        b: 'Autophagy removes epigenetically dysregulated protein aggregates; limited clock data',
        verdict: 'a',
        note: 'NMN-SIRT1 axis has published epigenetic clock acceleration reversal data',
      },
      {
        dimension: 'Dosing practicality',
        a: '250–500 mg/day capsule, morning, stable shelf life',
        b: '0.8–1.2 mg/day capsule (dietary equivalent) or 1+ tbsp wheat germ daily',
        verdict: 'b',
        note: 'Spermidine achieves effect at micro-dose; NMN requires gram-scale supplementation',
      },
      {
        dimension: 'Synergy within TNiC stack',
        a: 'NMN + Resveratrol = SIRT1 dual activation (core NAD⁺ pair)',
        b: 'Spermidine + NMN = orthogonal coverage: polyamine autophagy + NAD⁺ repair',
        verdict: 'tie',
        note: 'Both are included in Full Hybrid and Full-Spectrum 14 — the combination is the point',
      },
    ],
    whenChooseA: [
      'Primary goal is NAD⁺ repletion — declining energy, muscle endurance, or cognition after 40',
      'Running the SIRT1 pair stack (NMN + Resveratrol) as your core longevity protocol',
      'Vascular aging is a priority — endothelial NAD⁺ deficit is the validated target',
      'Prefer the compound with the strongest double-blind RCT footprint available OTC',
    ],
    whenChooseB: [
      'Primary goal is autophagy enhancement — protein aggregate clearance or immune aging',
      'Following a caloric-restriction mimicry approach — spermidine is the closest dietary proxy',
      'Concerned about T-cell exhaustion or immune aging — spermidine has direct mechanistic data',
      'Budget-constrained and diet is already rich in polyamines (beef, aged cheese, mushrooms)',
    ],
    relatedHrefs: [
      { label: 'NMN in Library', href: '/library/compounds/nmn' },
      { label: 'Spermidine in Library', href: '/library/compounds/spermidine' },
      { label: 'NMN vs NR', href: '/library/compare/nmn-vs-nr' },
      { label: 'Disabled Autophagy hallmark', href: '/library/disabled-macroautophagy' },
      { label: 'NAD⁺ Mito Stack synergy', href: '/library/nad-mito-stack' },
    ],
    keywords: ['nmn', 'spermidine', 'autophagy', 'nad+', 'ep300', 'sirt1', 'longevity', 'immune aging', 'polyamine'],
  },
  {
    slug: 'fisetin-vs-quercetin',
    title: 'Fisetin vs Quercetin',
    subtitle: 'Two flavonoid senolytics — Mayo Clinic pilot vs Dasatinib adjunct',
    labelA: 'Fisetin',
    labelB: 'Quercetin',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      'Fisetin and quercetin are both flavonoids studied for senolytic activity — the ability to selectively eliminate senescent "zombie" cells that accumulate with age and drive inflammaging. They share the BCL-2/BCL-XL inhibition pathway but differ dramatically in their human evidence, dosing strategy, and solo OTC viability. Fisetin has a standalone Mayo Clinic phase 1 pilot; quercetin is most studied in combination with the prescription drug dasatinib (D+Q protocol).',
    verdict:
      'Fisetin is the stronger OTC-only senolytic choice: the only flavonoid with a standalone Mayo Clinic clinical signal. Quercetin belongs in a D+Q protocol (physician supervised) — solo OTC quercetin has weak senolytic evidence. Do not replace dasatinib with quercetin for serious senolytic intent.',
    rows: [
      {
        dimension: 'Standalone senolytic human evidence',
        a: 'Phase 1 feasibility (Trivedi 2019): cleared circulating senescent cells in 14 subjects',
        b: 'Weak as solo agent — primarily studied as D+Q adjunct',
        verdict: 'a',
        pmid: '30957782',
        note: 'Quercetin alone has not shown clinically significant senolytic effect in RCTs',
      },
      {
        dimension: 'Prescription pairing',
        a: 'Used as OTC standalone or with physician-guided protocol',
        b: 'Synergistic with Dasatinib (BCR-ABL inhibitor); D+Q is the benchmark senolytic regimen',
        verdict: 'context',
        note: 'If physician prescribes Dasatinib, Quercetin is the validated pairing — not Fisetin',
      },
      {
        dimension: 'Neurological evidence',
        a: 'Strong preclinical: BDNF upregulation, reduces tau, neuroinflammation in aged mice',
        b: 'Moderate — primarily anti-inflammatory, less direct neuroproliferative data',
        verdict: 'a',
        pmid: '30957782',
      },
      {
        dimension: 'AMPK / metabolic support',
        a: 'Minor AMPK signal; not primary mechanism',
        b: 'Quercetin activates AMPK and has modest MetS data',
        verdict: 'b',
      },
      {
        dimension: 'Bioavailability',
        a: 'Poor native — requires fat co-ingestion; isorhamnetin metabolite is active form',
        b: 'Quercetin-3-glucoside better absorbed; piperine co-administration boosts plasma levels',
        verdict: 'context',
        note: 'Both are poor without formulation optimization; quercetin dihydrate + piperine preferred',
      },
      {
        dimension: 'Dosing strategy',
        a: 'Pulse dosing: 20 mg/kg body weight for 2 consecutive days, repeat monthly',
        b: 'D+Q: 100 mg dasatinib + 1,000 mg quercetin on same 2-day pulse schedule',
        verdict: 'context',
      },
      {
        dimension: 'OTC accessibility',
        a: 'Widely available; Fisetin 100–500 mg capsules from reputable suppliers',
        b: 'Quercetin OTC but Dasatinib is Rx-only — limiting the validated protocol',
        verdict: 'a',
      },
      {
        dimension: 'Safety profile',
        a: 'Excellent — no serious adverse events at doses up to 1,200 mg in pilot',
        b: 'Quercetin itself is safe; Dasatinib carries cardiovascular and pleural effusion risk',
        verdict: 'a',
        note: 'Compare quercetin safety only — adding dasatinib significantly changes risk profile',
      },
    ],
    whenChooseA: [
      'Solo OTC senolytic protocol — Fisetin is the only flavonoid with standalone Mayo signal',
      'Neurological aging concern: cognitive protection, BDNF support, tau reduction',
      'Pulse dosing without prescription involvement',
      'No physician for Dasatinib access — Fisetin is the defensible OTC alternative',
    ],
    whenChooseB: [
      'Physician prescribes Dasatinib — Quercetin is the validated adjunct in D+Q protocol',
      'AMPK or metabolic support primary goal alongside mild senolytic activity',
      'Cardiovascular or inflammation focus — quercetin has broader anti-inflammatory meta-analysis data',
    ],
    relatedHrefs: [
      { label: 'Cellular Senescence hallmark', href: '/library/cellular-senescence' },
      { label: 'Full Hybrid Stack', href: '/stacks' },
      { label: 'Berberine vs Metformin', href: '/library/compare/berberine-vs-metformin' },
    ],
    keywords: ['fisetin', 'quercetin', 'senolytic', 'senescence', 'zombie cells', 'flavonoid', 'mayo clinic', 'dasatinib'],
  },
  {
    slug: 'taurine-vs-nmn',
    title: 'Taurine vs NMN',
    subtitle: 'The 2023 Science longevity paper compound vs the NAD+ repletion gold standard',
    labelA: 'Taurine',
    labelB: 'NMN',
    category: 'compound',
    evidenceTier: 'A',
    summary:
      'Taurine exploded onto the longevity stage in 2023 when a landmark Science paper (Singh et al.) showed taurine deficiency drives aging across worms, mice, and monkeys — and that taurine supplementation extended median lifespan 10–12% in middle-aged mice and improved multiple aging biomarkers in primates. NMN has a longer track record of controlled human RCTs confirming NAD+ elevation. Both are Tier A compounds operating through fundamentally different mechanisms — taurine is a systemic deficiency corrector; NMN is a pathway-specific fuel for sirtuin/PARP repair.',
    verdict:
      'Both deserve a place in a serious longevity stack. NMN leads on RCT evidence in humans and SIRT1 pathway specificity. Taurine leads on lifespan extension breadth (multi-species), cost-efficiency, and systemic marker coverage. The Full Hybrid and Full-Spectrum 14 stacks include both — this is not an either/or decision.',
    rows: [
      {
        dimension: 'Landmark human evidence',
        a: 'Singh 2023 (Science): human cohort taurine decline with age + pilot human supplementation markers',
        b: 'Liao 2021, Igarashi 2022: RCTs confirming NAD+ elevation + muscle/vascular outcomes',
        verdict: 'tie',
        pmid: '37289866',
        note: 'Different evidence types: taurine deficiency = population signal; NMN = controlled intervention',
      },
      {
        dimension: 'Lifespan extension (animal models)',
        a: '+10–12% median lifespan in mice; worm and primate data also positive (Singh 2023)',
        b: 'Strong in NAD+-depleted rodents; no direct lifespan extension RCT in humans',
        verdict: 'a',
        pmid: '37289866',
      },
      {
        dimension: 'Mechanism breadth',
        a: 'Mitochondrial function, DNA damage, inflammation, immune aging, stem cell pool, telomere length — multi-hallmark',
        b: 'NAD⁺ repletion → SIRT1, PARP1, CD38 axis — deep mechanistic specificity',
        verdict: 'context',
        note: 'Taurine is broad but less mechanistically characterized than NMN',
      },
      {
        dimension: 'NAD+ restoration',
        a: 'Indirect — taurine supports mitochondrial function but does not raise NAD+',
        b: '38% whole-blood NAD⁺ increase at 250 mg/day (Liao 2021)',
        verdict: 'b',
        pmid: '34631532',
      },
      {
        dimension: 'Epigenetic clock signal',
        a: 'Emerging — Singh 2023 shows favorable aging biomarker changes in primates (bone density, glucose, hair)',
        b: 'Horvath clock pilot: −2.1yr avg in small n (not replicated at scale)',
        verdict: 'context',
        note: 'Neither has confirmed robust methylation clock reversal in large human RCT yet',
      },
      {
        dimension: 'Cost (per month)',
        a: '$5–15/month — taurine powder is extremely inexpensive',
        b: '$40–80/month for quality 500 mg capsules',
        verdict: 'a',
        note: 'Taurine is 5–10× cheaper — major advantage for sustained protocol compliance',
      },
      {
        dimension: 'Dose',
        a: '3–6 g/day — once daily or split dose with meals',
        b: '250–500 mg/day — typically morning on empty stomach or with light protein',
        verdict: 'context',
      },
      {
        dimension: 'Safety profile',
        a: 'Outstanding — widely used in clinical nutrition (heart failure, neonatal support); 3 g/day well-established',
        b: 'Excellent in all human trials to date; no serious adverse events',
        verdict: 'tie',
      },
      {
        dimension: 'TNiC stack integration',
        a: 'Full-Spectrum 14 and Full Hybrid stacks',
        b: 'Starter, Mito-NAD+, Full Hybrid, Longevity Pro presets',
        verdict: 'context',
      },
    ],
    whenChooseA: [
      'Budget-constrained — taurine delivers broad multi-hallmark benefit at a fraction of NMN cost',
      'Starting a longevity stack and want maximum coverage per dollar',
      'Cardiovascular or metabolic focus — taurine has a long clinical safety record here',
      'Want multi-species lifespan extension signal in your foundation compounds',
    ],
    whenChooseB: [
      'NAD+ levels are the primary target (confirmed low or suspected from age/fatigue)',
      'SIRT1 activation is the specific goal — NMN is the precision intervention',
      'Pairing with resveratrol for SIRT1 stack (NMN + resveratrol is the standard validated pair)',
      'Muscle recovery and endothelial aging are primary endpoints',
    ],
    relatedHrefs: [
      { label: 'Taurine Guide', href: '/library/compounds/taurine' },
      { label: 'NMN Guide', href: '/library/compounds/nmn' },
      { label: 'NMN vs NR', href: '/library/compare/nmn-vs-nr' },
      { label: 'Mitochondrial Dysfunction hallmark', href: '/library/mitochondrial-dysfunction' },
    ],
    keywords: ['taurine', 'nmn', 'longevity 2023', 'science paper aging', 'nad+', 'lifespan extension', 'taurine deficiency aging'],
  },
  {
    slug: 'cakg-vs-spermidine',
    title: 'Ca-AKG vs Spermidine',
    subtitle: 'Epigenetic reprogramming substrate vs direct autophagy inducer',
    labelA: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    labelB: 'Spermidine',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      'Ca-AKG and spermidine are both emerging longevity compounds with striking epigenetic and autophagy data — but they operate at entirely different nodes. Ca-AKG is a TET DNA demethylase cofactor: it supplies the substrate TET enzymes need to remove methyl groups from aging DNA, potentially reversing epigenetic drift. Spermidine inhibits EP300 acetyltransferase, triggering autophagy flux that clears damaged organelles and proteins. Together they address the two biggest non-NAD+ longevity nodes: epigenetic age and proteostasis.',
    verdict:
      'Ca-AKG leads on epigenetic clock reversal evidence (Rejuvant trial: −8yr biological age). Spermidine leads on autophagy breadth, immune rejuvenation, and observational lifespan data. Stack both if budget allows — they are mechanistically orthogonal and naturally synergistic.',
    rows: [
      {
        dimension: 'Epigenetic clock reversal',
        a: 'Rejuvant trial (Demidenko 2021): −7.5 years biological age (Horvath clock) in 42 adults over 7 months',
        b: 'Indirect — autophagy improves proteostasis which correlates with slower epigenetic drift',
        verdict: 'a',
        pmid: '34708673',
      },
      {
        dimension: 'Autophagy induction',
        a: 'Indirect — AKG is an mTORC1 suppressor; reduces mTOR signaling that blocks autophagy',
        b: 'Direct — EP300 inhibition mimics caloric restriction autophagy trigger at mg-level dosing',
        verdict: 'b',
        pmid: '28026137',
      },
      {
        dimension: 'Mechanism type',
        a: 'TET cofactor → DNA demethylation → epigenetic reprogramming',
        b: 'EP300 inhibitor → autophagic flux → proteostasis + immune renewal',
        verdict: 'context',
        note: 'Upstream epigenetic (Ca-AKG) vs cytoplasmic organelle renewal (spermidine) — orthogonal',
      },
      {
        dimension: 'mTOR modulation',
        a: 'Strong mTORC1 suppression — AKG competes at glutamine-sensing node',
        b: 'Indirect mTOR suppression via AMPK-related signaling',
        verdict: 'a',
        note: 'Ca-AKG is a credible mTOR longevity axis drug — distinct from rapamycin but overlapping',
      },
      {
        dimension: 'Human observational lifespan data',
        a: 'No long-term lifespan cohort data yet',
        b: 'Kiechl 2018 (PMID: 29991564): higher dietary spermidine → 5yr lower mortality in n=829 cohort',
        verdict: 'b',
        pmid: '29991564',
      },
      {
        dimension: 'Immune T-cell rejuvenation',
        a: 'Not a primary mechanism',
        b: 'Phase II: spermidine restored T-cell memory responses in older adults',
        verdict: 'b',
      },
      {
        dimension: 'Cost',
        a: 'Rejuvant/Ca-AKG: $50–80/month for 1 g/day',
        b: 'Spermidine: $40–70/month for standardized 1–2 mg/day; or dietary from wheat germ',
        verdict: 'context',
      },
      {
        dimension: 'Safety profile',
        a: 'Well-tolerated in Rejuvant trial; AKG is endogenous metabolite',
        b: 'Excellent — endogenous polyamine; dietary equivalent dosing used in trials',
        verdict: 'tie',
      },
    ],
    whenChooseA: [
      'Epigenetic age reduction is the primary goal — Rejuvant trial is the strongest clock reversal signal in a single compound',
      'mTOR suppression desired without rapamycin prescription',
      'Running a methylation-focused protocol targeting DNAmAge Horvath clock markers',
    ],
    whenChooseB: [
      'Autophagy enhancement is the primary mechanism target',
      'Immune aging or T-cell rejuvenation is a concern',
      'Dietary longevity pattern alignment — spermidine is the most food-proximate autophagy compound',
      'Already running Ca-AKG and want complementary autophagy coverage',
    ],
    relatedHrefs: [
      { label: 'Ca-AKG Guide', href: '/library/compounds/cakg' },
      { label: 'Spermidine Guide', href: '/library/compounds/spermidine' },
      { label: 'Epigenetic Alterations hallmark', href: '/library/epigenetic-alterations' },
      { label: 'NMN vs Spermidine', href: '/library/compare/nmn-vs-spermidine' },
    ],
    keywords: ['ca-akg', 'alpha-ketoglutarate', 'spermidine', 'epigenetic clock', 'autophagy', 'methylation', 'horvath', 'rejuvant'],
  },
  {
    slug: 'rapamycin-vs-metformin',
    title: 'Rapamycin vs Metformin',
    subtitle: 'Two longevity drugs at opposite ends of the risk-benefit spectrum',
    labelA: 'Rapamycin (mTOR inhibitor)',
    labelB: 'Metformin (AMPK activator)',
    category: 'compound',
    evidenceTier: 'B',
    summary:
      "Rapamycin and metformin are the two most-discussed longevity pharmaceuticals — both with ITP (Interventions Testing Program) lifespan extension data in mice and ongoing human aging trials. They operate on partially overlapping but mechanistically distinct pathways: rapamycin directly inhibits mTORC1 (the longevity program's master switch), while metformin activates AMPK, which in turn suppresses mTORC1 indirectly and improves glucose metabolism. Rapamycin has dramatically stronger preclinical longevity data; metformin has a 60-year human safety record and is the subject of the TAME trial.",
    verdict:
      'Metformin is the accessible, physician-prescribable longevity intervention with excellent safety data. Rapamycin has superior preclinical longevity efficacy but requires physician oversight, cyclic dosing, and immune monitoring. They are not mutually exclusive — some longevity clinicians combine them at low doses with careful monitoring.',
    rows: [
      {
        dimension: 'ITP lifespan extension (mice)',
        a: 'Significant: 9–14% median lifespan increase, starting as late as 20 months old (equivalent to ~60 human years)',
        b: 'Modest: ~5% lifespan increase; some ITP cohorts showed no effect',
        verdict: 'a',
        pmid: '22107967',
        note: 'Rapamycin is the most replicated ITP longevity result; metformin results are inconsistent across labs',
      },
      {
        dimension: 'Primary mechanism',
        a: 'Direct mTORC1 inhibition → autophagy, reduced protein synthesis, immune modulation',
        b: 'AMPK activation → mTORC1 suppression, improved insulin sensitivity, Complex I inhibition',
        verdict: 'context',
        note: 'Rapamycin hits mTOR directly; metformin hits it indirectly via energy-sensing',
      },
      {
        dimension: 'Human safety record',
        a: '30+ years post-transplant use at immunosuppressive doses; cyclic low-dose is under-studied',
        b: '60+ years clinical use; billions of patient-years; one of the best-characterized drugs in medicine',
        verdict: 'b',
        note: 'Metformin has vastly superior safety track record at therapeutic doses',
      },
      {
        dimension: 'Human longevity RCT',
        a: 'PEARL trial (rapamycin, enrolled 2022); no published longevity primary endpoints yet',
        b: 'TAME trial (NCT03107884): n=3,000 registered, targets aging as a disease endpoint; results ~2027',
        verdict: 'tie',
        note: 'Neither has completed a primary endpoint longevity RCT in healthy humans as of 2026',
      },
      {
        dimension: 'OTC accessibility',
        a: 'Prescription only; off-label for longevity in the US; typically $30–80/month at low longevity dose',
        b: 'Prescription in US (widely prescribed for T2D, often covered by insurance); generic ~$4/month',
        verdict: 'b',
      },
      {
        dimension: 'Immune effects',
        a: 'Immunosuppressive at high doses; cyclic low-dose (1–6 mg/week) may enhance immune function in older adults',
        b: 'Immunomodulatory — reduces inflammaging markers; generally no clinically significant immunosuppression',
        verdict: 'b',
        pmid: '14500065',
        note: "Rapamycin's immune effects are dose-dependent and bidirectional — requires monitoring",
      },
      {
        dimension: 'Muscle preservation',
        a: 'Controversial — high doses impair mTORC2/muscle; cyclic dosing may avoid this',
        b: 'Slight reduction in VO2max at high aerobic training loads (Malin 2019); generally neutral to muscle',
        verdict: 'b',
        pmid: '31380906',
        note: 'Neither compound is ideal for athletes; both can blunt training adaptation',
      },
      {
        dimension: 'Physician oversight required',
        a: 'High — requires CBC, metabolic panel, lipid panel, wound-healing monitoring; prescription-only',
        b: 'Moderate — prescription required; basic kidney function monitoring (eGFR); well understood by GPs',
        verdict: 'b',
      },
    ],
    whenChooseA: [
      'Working with a longevity physician who supervises cyclic low-dose rapamycin (1–6 mg/week)',
      'Primary goal is mTOR longevity axis and you are not at elevated infection risk',
      'Interested in the compound with the strongest preclinical lifespan data',
      'Already on a comprehensive monitoring protocol and willing to manage immune considerations',
    ],
    whenChooseB: [
      'Starting a longevity pharmaceutical intervention without specialist oversight',
      'Primary goal is metabolic aging, insulin sensitivity, or glucose regulation',
      'Budget-constrained — metformin is the most evidence-dense, lowest-cost longevity pharmaceutical option',
      'Have diabetes risk or prediabetes — metformin addresses both metabolic and longevity endpoints',
    ],
    relatedHrefs: [
      { label: 'Rapamycin Guide', href: '/library/compounds/rapamycin' },
      { label: 'mTOR & Nutrient Sensing hallmark', href: '/library/deregulated-nutrient-sensing' },
      { label: 'Ca-AKG vs Spermidine', href: '/library/compare/cakg-vs-spermidine' },
      { label: 'Elite 8 LQ Ranking', href: '/elite-8' },
    ],
    keywords: ['rapamycin longevity', 'metformin aging', 'mTOR inhibitor longevity', 'TAME trial', 'PEARL trial rapamycin', 'rapamycin vs metformin', 'longevity drug comparison', 'mTOR metformin'],
  },
  {
    slug: 'coq10-vs-ubiquinol',
    title: 'CoQ10 vs Ubiquinol',
    subtitle: 'Oxidized vs reduced form — does the upgrade justify the price premium?',
    labelA: 'CoQ10 (Ubiquinone)',
    labelB: 'Ubiquinol (Reduced CoQ10)',
    category: 'form',
    evidenceTier: 'B',
    summary:
      'CoQ10 (ubiquinone) and Ubiquinol are two forms of the same molecule. Ubiquinone is the oxidized form; ubiquinol is the reduced, active antioxidant form. Your body interconverts them. The key debate: does supplementing ubiquinol (which bypasses the reduction step) result in meaningfully better plasma levels and clinical outcomes, particularly in older adults whose conversion efficiency declines? The evidence is nuanced — ubiquinol shows superior plasma absorption in most studies, but whether this translates to better clinical outcomes is not consistently established.',
    verdict:
      'Ubiquinol is the preferred form for adults over 50 or anyone on statins — superior plasma absorption is consistently demonstrated. Ubiquinone is adequate for healthy adults under 50 at a significantly lower cost. For heart failure or neurological applications, the clinical trial data mostly used ubiquinone at high doses — switching to ubiquinol is reasonable but evidence is extrapolated.',
    rows: [
      {
        dimension: 'Plasma CoQ10 levels (absorption)',
        a: 'Good absorption; requires stomach acid and dietary fat for optimal uptake',
        b: '3–4× higher plasma CoQ10 after single dose in head-to-head comparison (Schmelzer 2008)',
        verdict: 'b',
        pmid: '18657483',
        note: 'Ubiquinol advantage is clearest in single-dose and short-term kinetic studies; long-term steady-state differences are smaller',
      },
      {
        dimension: 'Conversion efficiency with age',
        a: 'Requires reduction to ubiquinol intracellularly; conversion declines with age and statin use',
        b: 'Pre-reduced — bypasses the NADPH-dependent conversion step that becomes rate-limiting in older adults',
        verdict: 'b',
        note: 'Over 50, the conversion step is less efficient; ubiquinol is the pragmatic choice',
      },
      {
        dimension: 'Clinical trial evidence (heart failure)',
        a: 'Q-SYMBIO trial (PMID 25282031): 300 mg/day reduced cardiac events; most HF trials used ubiquinone',
        b: 'Limited dedicated HF RCTs; bioavailability extrapolation used to support ubiquinol preference',
        verdict: 'a',
        pmid: '25282031',
        note: 'The bulk of published clinical evidence used ubiquinone — ubiquinol is preferred based on pharmacokinetics, not outcomes RCTs',
      },
      {
        dimension: 'Statin depletion recovery',
        a: 'Effective at repleting CoQ10 depleted by statins — most statin CoQ10 trials used ubiquinone',
        b: 'Theoretically superior for statin patients (reduced conversion needed); limited dedicated statin RCTs',
        verdict: 'context',
        note: 'If on a statin, ubiquinol is a reasonable preference; the underlying depletion mechanism supports it',
      },
      {
        dimension: 'Stability and shelf life',
        a: 'Very stable — ubiquinone is the oxidized form, less susceptible to degradation',
        b: 'Less stable — can oxidize back to ubiquinone; requires airtight, light-protected packaging',
        verdict: 'a',
        note: 'Quality matters more for ubiquinol; choose reputable manufacturers with COA testing',
      },
      {
        dimension: 'Cost',
        a: 'Significantly cheaper — ubiquinone 200 mg runs ~$0.15–0.30/day from quality brands',
        b: '2–3× more expensive — ubiquinol 200 mg runs ~$0.40–0.80/day',
        verdict: 'a',
      },
      {
        dimension: 'Neurological applications (Parkinson\'s, migraine)',
        a: 'Most neuroprotection trials used ubiquinone; NINDS Parkinson\'s RCT used ubiquinone',
        b: 'Growing interest; theoretically superior for brain (high conversion demand); limited dedicated RCTs',
        verdict: 'context',
        note: 'Standard neurological evidence base used ubiquinone; ubiquinol is an emerging preference without dedicated outcome data',
      },
    ],
    whenChooseA: [
      'Under 50 with no statin use and no known absorption issues',
      'Budget is a primary consideration — ubiquinone delivers CoQ10 at a fraction of the cost',
      'Using CoQ10 specifically for heart failure support (existing trial evidence base)',
      'Want the most stable form for long-term storage',
    ],
    whenChooseB: [
      'Over 50 — conversion efficiency declines with age, making ubiquinol the practical choice',
      'On statin therapy — statins impair CoQ10 synthesis and conversion; ubiquinol bypasses both steps',
      'Confirmed absorption issues (low stomach acid, fat malabsorption)',
      'Want the highest plasma CoQ10 levels from a given dose',
    ],
    relatedHrefs: [
      { label: 'CoQ10 in Library', href: '/library/compounds/coq10' },
      { label: 'Urolithin A vs CoQ10', href: '/library/compare/urolithina-vs-coq10' },
      { label: 'Mitochondrial Dysfunction hallmark', href: '/library/mitochondrial-dysfunction' },
      { label: 'Elite 8 LQ Ranking', href: '/elite-8' },
    ],
    keywords: ['coq10 vs ubiquinol', 'ubiquinol supplement', 'coq10 form guide', 'ubiquinone vs ubiquinol', 'coq10 for statins', 'coq10 heart health', 'best coq10 supplement'],
  },
  {
    slug: 'omega3-vs-krill-oil',
    title: 'Omega-3 vs Krill Oil',
    subtitle: 'Fish oil triglycerides vs phospholipid-bound EPA/DHA — bioavailability trade-off',
    labelA: 'Fish Oil (Omega-3 Triglycerides)',
    labelB: 'Krill Oil (Phospholipid EPA/DHA)',
    category: 'form',
    evidenceTier: 'A',
    summary:
      'Fish oil and krill oil both deliver EPA and DHA — the two omega-3 fatty acids with robust cardiovascular, cognitive, and anti-inflammatory evidence. The key difference is molecular form: fish oil carries EPA/DHA in triglyceride (TG) form; krill oil carries EPA/DHA bound to phospholipids (PL). Phospholipid-bound omega-3s show superior absorption in some studies and come bundled with choline and astaxanthin. However, krill oil provides dramatically less EPA/DHA per capsule and costs 3–5× more per gram of EPA+DHA. For longevity purposes, total EPA+DHA dose is what the RCT literature supports.',
    verdict:
      'Fish oil wins on cost-effectiveness and total EPA+DHA dose per dollar. Krill oil is not meaningfully superior for longevity-relevant outcomes when EPA+DHA doses are equalized. Choose high-quality fish oil (triglyceride form, ≥70% omega-3 concentrate) over krill oil for most longevity protocols — the dose advantage matters more than the form advantage.',
    rows: [
      {
        dimension: 'EPA+DHA per standard capsule',
        a: 'High: quality concentrates deliver 500–900 mg EPA+DHA per 1 g capsule',
        b: 'Low: typical krill oil capsule delivers 100–250 mg EPA+DHA per 500 mg capsule',
        verdict: 'a',
        note: 'For cardiovascular longevity endpoints, you need 2–4 g/day of EPA+DHA; krill oil makes this very expensive',
      },
      {
        dimension: 'Bioavailability (EPA+DHA absorption)',
        a: 'Good with food; re-esterified triglyceride (rTG) form is superior to ethyl ester form',
        b: 'Phospholipid form may show 10–30% higher absorption in short-term studies (Maki 2009)',
        verdict: 'context',
        pmid: '19345947',
        note: 'Bioavailability advantage is real but smaller than krill oil marketing suggests; dose matters more at equal EPA+DHA',
      },
      {
        dimension: 'Cardiovascular RCT evidence',
        a: 'REDUCE-IT (PMID 30345336): 4 g EPA (Vascepa) reduced major cardiac events 25% — the definitive omega-3 cardiovascular trial',
        b: 'No head-to-head cardiovascular outcome trials at effective EPA+DHA doses',
        verdict: 'a',
        pmid: '30345336',
        note: 'The massive REDUCE-IT and STRENGTH trials used fish oil derivatives, not krill oil',
      },
      {
        dimension: 'Cognitive / anti-inflammatory evidence',
        a: 'Extensive: DHA depletion in Alzheimer\'s brain; EPA for depression; MFOS and VITAL trials for inflammation',
        b: 'Emerging; limited dedicated cognitive RCTs; extrapolated from fish oil data + choline co-delivery',
        verdict: 'a',
      },
      {
        dimension: 'Bonus compounds (astaxanthin, choline)',
        a: 'None — pure EPA+DHA delivery',
        b: 'Contains astaxanthin (2 mg; mild antioxidant) and choline (~50 mg; cognitive support)',
        verdict: 'b',
        note: 'Choline co-delivery is a genuine benefit for those not eating eggs regularly; astaxanthin dose is below therapeutic range',
      },
      {
        dimension: 'Oxidation stability',
        a: 'Vulnerable — buy from brands with oxidation COA testing (TOTOX <26); store refrigerated',
        b: 'More stable — astaxanthin acts as natural antioxidant; fewer oxidation concerns',
        verdict: 'b',
        note: 'Rancid fish oil negates health benefits; COA testing is non-negotiable for quality fish oil',
      },
      {
        dimension: 'Cost per gram EPA+DHA',
        a: '$0.05–0.15/g EPA+DHA from quality rTG concentrates (e.g., Nordic Naturals, Carlson)',
        b: '$0.80–2.00/g EPA+DHA from krill oil — 5–15× more expensive per unit of active omega-3',
        verdict: 'a',
      },
    ],
    whenChooseA: [
      'Primary goal is reaching 2–4 g/day EPA+DHA dose for cardiovascular or cognitive longevity',
      'Budget is a consideration — fish oil delivers the same EPA+DHA at a fraction of the cost',
      'Following REDUCE-IT-protocol EPA supplementation (requires dedicated EPA/fish oil, not krill)',
      'Want the form with the most direct clinical evidence for your endpoint',
    ],
    whenChooseB: [
      'You reliably burp/reflux fish oil capsules (krill oil is often better tolerated)',
      'Want the choline and astaxanthin co-benefits without separate supplements',
      'Budget allows and you prefer a single smaller capsule for travel or compliance',
      'Sustainable sourcing is a priority — krill harvesting has lower ecological impact than some fish oil sources',
    ],
    relatedHrefs: [
      { label: 'Omega-3 in Library', href: '/library/compounds/omega3' },
      { label: 'Mitochondrial Dysfunction hallmark', href: '/library/mitochondrial-dysfunction' },
      { label: 'Best Longevity Supplements 2026', href: '/longevity-supplements-guide' },
      { label: 'Elite 8 LQ Ranking', href: '/elite-8' },
    ],
    keywords: ['omega-3 vs krill oil', 'fish oil vs krill oil', 'krill oil supplement', 'best omega-3 supplement', 'EPA DHA supplement', 'fish oil longevity', 'omega-3 bioavailability'],
  },
];

export function getComparison(slug: string): EvidenceComparison | undefined {
  return evidenceComparisons.find((c) => c.slug === slug);
}

export function getAllComparisonSlugs(): string[] {
  return evidenceComparisons.map((c) => c.slug);
}