import type { HallmarkLibraryEntry } from './types';

export const hallmarkLibrary: HallmarkLibraryEntry[] = [
  {
    id: 'genomic',
    slug: 'genomic-instability',
    number: 1,
    title: 'Genomic Instability',
    tagline: 'When DNA repair can no longer keep pace with damage',
    summary: 'Accumulated DNA lesions — from replication errors, radiation, and oxidative hits — overwhelm repair pathways. Unrepaired damage drives mutations, cellular dysfunction, and cancer risk.',
    mechanism: 'Cells sustain ∼10,000 oxidative DNA lesions per day; base-excision repair (BER) is the primary defense, with PARP1/2 detecting strand breaks and synthesizing PAR chains to recruit repair enzymes. PARP consumes NAD+ in the process — during heavy damage, NAD+ can fall 60–80%, stalling other NAD+-dependent pathways simultaneously. SIRT6, also NAD+-dependent, stabilizes double-strand break repair factors and suppresses LINE-1 transposon transcription; its activity collapses as NAD+ declines with age. NRF2 activation provides upstream leverage by upregulating over 200 cytoprotective genes (NQO1, GST, GCLC, HMOX1) that neutralize the ROS and electrophiles causing most oxidative lesions before they reach DNA. The practical rate-limiting step is NAD+ availability — restoring it via NMN allows both PARP and SIRT6 to function at capacity, while sulforaphane reduces the incoming damage load at the source.',
    keyMolecules: ['PARP1/2', 'SIRT6', 'NRF2', 'KEAP1', 'ATM', 'γ-H2AX', 'NQO1', 'NAD+'],
    whyItMatters: 'Genomic instability is the upstream substrate for cancer AND the trigger for cellular senescence — when ATM/p53 damage signaling cannot be resolved, cells either mutate or permanently arrest. The cross-hallmark impact is broad: damaged transcription factors corrupt epigenetic patterns, impaired SIRT6 accelerates telomere attrition, and mtDNA (with minimal repair capacity) accumulates mutations that drive mitochondrial dysfunction. Clinically, urinary 8-OHdG (oxidative DNA damage) and γ-H2AX foci (double-strand breaks) are measurable proxies — tracking them before and 12 weeks after NAD+ restoration provides a quantifiable signal.',
    visual: 'dna',
    coverage: 85,
    biomarkers: ['8-OHdG', 'γ-H2AX foci', 'micronuclei frequency'],
    relatedCompoundIds: ['nmn', 'sulforaphane', 'glynac'],
    mdxSlug: 'genomic-instability',
    personalPrompts: ['Note any family cancer history', 'Track oxidative stress markers (8-OHdG if tested)', 'Log sleep quality — repair peaks during deep sleep'],
    interventions: [
      { id: 'g1', name: 'NMN / NAD+ restoration', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Replenishes NAD+ pools consumed by PARP during DNA repair. Human trials show restored NAD+ metabolites.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'g2', name: 'Sulforaphane (NRF2)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Activates NQO1, GST, and other phase-II enzymes that protect DNA from oxidative adducts.', compoundId: 'sulforaphane', pmid: '18454171', tnicAvailable: true },
      { id: 'g3', name: 'Sleep optimization (7–9h)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'DNA repair enzymes peak during slow-wave sleep. Chronic restriction increases double-strand breaks.', tnicAvailable: false },
      { id: 'g4', name: 'GlyNAC glutathione support', category: 'compound', evidence: 'A', rank: 4, impact: 7, description: 'Restores glutathione — primary defense against oxidative DNA damage.', compoundId: 'glynac', pmid: '34129059', tnicAvailable: true },
      { id: 'g5', name: 'Metformin', category: 'clinical', evidence: 'B', rank: 5, impact: 6, description: 'TAME trial candidate. Reduces DNA damage via AMPK and reduced ROS in preclinical models.', pmid: '26579537', tnicAvailable: false },
    ],
  },
  {
    id: 'telomeres',
    slug: 'telomere-attrition',
    number: 2,
    title: 'Telomere Attrition',
    tagline: 'The molecular clock at chromosome ends',
    summary: 'Telomeres shorten with each cell division. Critically short telomeres trigger senescence or apoptosis, limiting tissue regenerative capacity.',
    mechanism: 'Each somatic cell division removes 50–200 bp of TTAGGG repeats from chromosome ends because DNA polymerase cannot fully replicate the 3′ lagging strand — the "end-replication problem." Telomerase (hTERT + TERC) compensates in germline and stem cells but is silenced via CpG methylation in most somatic tissue. Beyond replication loss, cortisol-driven ROS preferentially attacks G-quadruplex structures in the telomeric sequence, shortening telomeres non-replicatively; studies show burnout accelerates biological age as much as 8–12 years through this mechanism. When telomeres reach a critical length (∼2–4 kb), they trigger ATM/ATR checkpoint signaling — the cell enters permanent senescence, feeding the SASP cycle. SIRT6, requiring NAD+, deacetylates WRN helicase at telomeres to aid their maintenance; NAD+ decline with age therefore indirectly impairs telomere protection alongside its more direct PARP effects.',
    keyMolecules: ['hTERT', 'TERC', 'SIRT6', 'WRN', 'ATM/ATR', 'p53', 'G-quadruplex', 'NAD+'],
    whyItMatters: 'Telomere length is best understood as a readout of cumulative cellular stress history — not a freely reversible biomarker. The critical downstream consequence is the senescence trigger: short telomeres are a major driver of the accumulating SASP burden that amplifies inflammaging. Key leverage is stress and inflammation reduction upstream: cortisol and chronic NF-κB signaling are the two fastest accelerators, making HRV training and sleep quality interventions more impactful here than most supplements.',
    visual: 'telomere',
    coverage: 62,
    biomarkers: ['Leukocyte telomere length', 'Telomerase activity'],
    relatedCompoundIds: ['nmn', 'omega3', 'glynac'],
    mdxSlug: 'telomere-attrition',
    personalPrompts: ['Record chronic stress periods', 'Note recovery time after illness', 'Compare biological age calculator vs chronological age'],
    interventions: [
      { id: 't1', name: 'Stress reduction / HRV training', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: 'Chronic cortisol accelerates telomere attrition. Meditation and breathwork show measurable telomerase activity increases.', tnicAvailable: false },
      { id: 't2', name: 'NMN / NAD+ support', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'NAD+ supports sirtuin-mediated telomere maintenance and PARP balance.', compoundId: 'nmn', tnicAvailable: true },
      { id: 't3', name: 'Exercise (moderate, consistent)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 7, description: 'Aerobic training associated with longer telomeres vs sedentary controls in meta-analyses.', tnicAvailable: false },
      { id: 't4', name: 'Omega-3 (EPA+DHA)', category: 'compound', evidence: 'A', rank: 4, impact: 6, description: 'Omega-3 supplementation associated with preserved telomere length in adults vs placebo (Brain Behav Immun 2012). EPA+DHA reduce cortisol and oxidative drivers of attrition (PMID 22245710).', compoundId: 'omega3', pmid: '22245710', tnicAvailable: true },
      { id: 't5', name: 'TA-65 / telomerase activators', category: 'emerging', evidence: 'C', rank: 5, impact: 4, description: 'Astragalus-derived compounds. Mouse data promising; human evidence limited and costly.', tnicAvailable: false },
      { id: 't6', name: 'GlyNAC (GSH + telomere protection)', category: 'compound', evidence: 'B', rank: 6, impact: 6, description: 'Glutathione protects the G-rich telomeric sequence from ROS-mediated oxidative cleavage. GlyNAC restores GSH levels shown depleted in aging — the GSH→telomere protection mechanism is mechanistically strong even if RCT telomere length data is indirect.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 't7', name: 'Telomere / biological age testing', category: 'clinical', evidence: 'B', rank: 7, impact: 4, description: 'Leukocyte telomere length (SpectraCell, Life Length) or epigenetic clock (TruAge, DunedinPACE) at baseline and 12-month intervals. Telomere length variability is high (use same lab). DunedinPACE is preferred for tracking intervention-driven attrition rate changes.', tnicAvailable: false },
    ],
  },
  {
    id: 'epigenetic',
    slug: 'epigenetic-alterations',
    number: 3,
    title: 'Epigenetic Alterations',
    tagline: 'When gene expression drifts from its youthful pattern',
    summary: 'DNA methylation, histone modifications, and chromatin remodeling change with age — the "epigenetic clock" — altering which genes are active without changing the DNA sequence.',
    mechanism: 'Three epigenetic layers all drift with age: DNA methylation (5mC at CpG sites, written by DNMT3A/B, erased by TET1/2/3 dioxygenases), histone acetylation (added by HATs, removed by HDACs including SIRT1/3), and histone methylation (H3K27me3 polycomb repression vs H3K4me3 active-gene marks). With age, CpG islands at developmental loci gain aberrant methylation — silencing genes the body needs — while LINE-1 transposable elements lose silencing methylation and can reactivate. TET enzymes require alpha-ketoglutarate (AKG) as a cofactor; declining AKG bioavailability with age directly impairs demethylation fidelity across the genome. SIRT1 deacetylates H3K9ac and H4K16ac to maintain heterochromatin compaction at pericentromeric and telomeric regions; without adequate NAD+, SIRT1 stalls and these regions decondense, reactivating silenced repetitive elements. The OSK Yamanaka factor experiments demonstrate epigenetic age is mechanistically reversible — AKG and NAD+ target the same rate-limiting cofactors that those factors manipulate.',
    keyMolecules: ['DNMT3A/B', 'TET1/2/3', 'SIRT1', 'H3K27me3', 'H3K4me3', 'AKG', 'LINE-1', 'HATs/HDACs'],
    whyItMatters: 'Epigenetic clocks (Horvath, GrimAge, DunedinPACE) predict all-cause mortality and disease risk independent of chronological age — they capture accumulated transcriptional drift better than any single biomarker. The most actionable insight is that AKG and NAD+ hit two of the three epigenetic enzyme classes (TET and sirtuins) — stacking Ca-AKG + NMN targets both the methylation and acetylation drift pathways simultaneously. GrimAge and DunedinPACE panels are now consumer-accessible and can quantify intervention response at 6-month intervals.',
    visual: 'epigenetic',
    coverage: 78,
    biomarkers: ['Horvath / GrimAge clock', 'DNA methylation panels'],
    relatedCompoundIds: ['cakg', 'nmn', 'resveratrol'],
    mdxSlug: 'epigenetic-alterations',
    personalPrompts: ['Log biological age from Defense Calculator', 'Track diet quality (methyl donors: B12, folate, choline)', 'Note energy consistency week-over-week'],
    interventions: [
      { id: 'e1', name: 'Ca-AKG', category: 'compound', evidence: 'A', rank: 1, impact: 8, description: 'AKG is a cofactor for TET dioxygenases that regulate DNA demethylation. Mouse lifespan extension data.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'e2', name: 'NMN → SIRT1 epigenetic control', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'NAD+-dependent sirtuins regulate histone acetylation and heterochromatin stability.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'e3', name: 'Resveratrol → SIRT1 activation', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Phytoalexin that activates SIRT1; synergistic with NAD+ precursors for epigenetic remodeling.', compoundId: 'resveratrol', pmid: '17909917', tnicAvailable: true },
      { id: 'e4', name: 'Caloric moderation / fasting', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Fasting resets methylation patterns in animal models and reduces epigenetic age in pilot human studies.', tnicAvailable: false },
      { id: 'e5', name: 'Epigenetic clock testing', category: 'clinical', evidence: 'B', rank: 5, impact: 5, description: 'GrimAge, DunedinPACE, or TruAge panels to track intervention response over 6–12 months.', tnicAvailable: false },
    ],
  },
  {
    id: 'proteostasis',
    slug: 'loss-of-proteostasis',
    number: 4,
    title: 'Loss of Proteostasis',
    tagline: 'When damaged proteins accumulate faster than cleanup',
    summary: 'The proteostasis network — chaperones, ubiquitin-proteasome, autophagy — fails to clear misfolded proteins, leading to aggregates linked to neurodegeneration.',
    mechanism: 'The proteostasis network has three clearance arms: the HSP70/HSP90 chaperone system (refolds misfolded proteins in real time), the ubiquitin-proteasome system (UPS, degrades short-lived tagged proteins via the 26S proteasome), and autophagy (handles larger aggregates and organelles). With age, proteasome activity falls 20–30% due to decreased β5 subunit expression, and chaperone capacity declines as heat shock factor 1 (HSF1) transcriptional activity drops. Oxidized proteins form covalent crosslinks that physically block proteasome entry and resist refolding — they become a self-amplifying bottleneck. Glutathione (GSH) protects critical cysteine residues in chaperones from irreversible sulfonylation (Cys-SOH → Cys-SO2H); when GSH falls below threshold, chaperones oxidize faster than new protein can replace them, accelerating aggregate accumulation. NRF2 activation (sulforaphane) upregulates PSMB5/β5 (proteasome), HSPA1A (HSP70), GCLC/GCLM (glutathione synthesis), and p62/SQSTM1 (selective autophagy receptor) — the most comprehensive proteostasis intervention available without prescription.',
    keyMolecules: ['HSP70/HSP90', 'PSMB5/β5', 'HSF1', 'GSH', 'p62/SQSTM1', 'NRF2', 'UPS', '26S proteasome'],
    whyItMatters: 'Protein aggregation defines the major neurodegenerative diseases — amyloid-β plaques (Alzheimer\'s), α-synuclein Lewy bodies (Parkinson\'s), TDP-43 inclusions (ALS) — and accumulates in heart and liver tissue long before clinical diagnosis. Cognitive longevity depends on proteostasis more than any other hallmark because neurons cannot be replaced by stem cells once lost. The GSH → chaperone → UPS axis is measurable (GSH/GSSG ratio, protein carbonylation assays) and directly addressable by GlyNAC supplementation, making proteostasis the most pharmacologically tractable hallmark for brain aging.',
    visual: 'protein',
    coverage: 82,
    biomarkers: ['Protein carbonylation', 'GSH/GSSG ratio', 'Ubiquitin conjugates'],
    relatedCompoundIds: ['glynac', 'rala', 'sulforaphane'],
    mdxSlug: 'loss-of-proteostasis',
    personalPrompts: ['Track mental clarity / brain fog', 'Log glutathione index if available', 'Note heat/cold exposure practices'],
    interventions: [
      { id: 'p1', name: 'GlyNAC (glutathione restoration)', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Human trials restore glutathione, reduce oxidative protein damage, improve mitochondrial function.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 'p2', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'Regenerates glutathione and vitamin C/E; supports mitochondrial proteostasis.', compoundId: 'rala', tnicAvailable: true },
      { id: 'p3', name: 'Sulforaphane (proteasome upregulation)', category: 'compound', evidence: 'A', rank: 3, impact: 7, description: 'NRF2 activation increases proteasome activity and heat shock protein expression.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'p4', name: 'Sauna / heat shock exposure', category: 'lifestyle', evidence: 'B', rank: 4, impact: 6, description: 'Heat shock proteins refold damaged proteins. Finnish sauna studies link frequency to reduced mortality.', tnicAvailable: false },
      { id: 'p5', name: 'Time-restricted eating', category: 'lifestyle', evidence: 'B', rank: 5, impact: 6, description: 'Fasting windows activate autophagy-proteostasis crosstalk via AMPK/mTOR.', tnicAvailable: false },
    ],
  },
  {
    id: 'autophagy',
    slug: 'disabled-autophagy',
    number: 5,
    title: 'Disabled Autophagy',
    tagline: 'Cellular recycling slows — junk accumulates',
    summary: 'Autophagy ("self-eating") clears damaged organelles and proteins. mTOR overactivation and NAD+ decline suppress this cleanup with age.',
    mechanism: 'Autophagy flux proceeds through five stages: induction (ULK1 complex phosphorylated by AMPK at Ser317/777), nucleation (BECN1/VPS34 PI3K complex generates the phagophore membrane), elongation (ATG5–12–16L1 complex lipidates LC3-I to LC3-II to coat the autophagosome), fusion with lysosomes, and cargo degradation by lysosomal hydrolases. mTORC1 directly inhibits ULK1 at Ser757, suppressing autophagy initiation when nutrients are abundant; with age, mTORC1 becomes tonically hyperactive, creating a chronic autophagy deficit even during fasting windows. SIRT1 deacetylates ATG5, ATG7, and LC3 to promote autophagosome maturation — NAD+ decline removes this facilitating arm. Cargo specificity matters critically: PINK1/Parkin-driven mitophagy removes dysfunctional mitochondria; ER-phagy (via FAM134B) clears stressed endoplasmic reticulum; lipophagy handles lipid droplets. When any arm fails, the uncleared cargo (damaged mitochondria, misfolded proteins, oxidized lipids) becomes a feedforward damage source for every adjacent hallmark.',
    keyMolecules: ['ULK1', 'BECN1/VPS34', 'LC3-II', 'mTORC1', 'AMPK', 'SIRT1', 'ATG5–12', 'PINK1/Parkin'],
    whyItMatters: 'Autophagy is the convergence point of proteostasis, mitochondrial quality control, and nutrient sensing — suppressing it downstream-impairs all three simultaneously. The most actionable lever is the fasting window: even a 16-hour fast suppresses mTORC1 long enough to allow a full autophagy flux cycle, and this is amplified by low-dose NMN (SIRT1 arm) + resveratrol (AMPK arm) taken at the start of the eating window. Measuring fasting insulin and ketone levels gives indirect proxy evidence of autophagy induction.',
    visual: 'autophagy',
    coverage: 70,
    biomarkers: ['LC3-II/LC3-I ratio (research)', 'p62 levels', 'Fasting glucose / ketones'],
    relatedCompoundIds: ['nmn', 'sulforaphane', 'resveratrol', 'spermidine'],
    mdxSlug: 'disabled-autophagy',
    personalPrompts: ['Log fasting window length', 'Track post-meal energy crashes', 'Note exercise intensity and recovery'],
    interventions: [
      { id: 'a1', name: 'Time-restricted eating (16:8+)', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: 'The most accessible autophagy trigger. mTOR suppression during fasting windows activates cleanup.', tnicAvailable: false },
      { id: 'a2', name: 'NMN → SIRT1 autophagy axis', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'NAD+-SIRT1 pathway deacetylates ATG proteins, promoting autophagosome formation.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'a3', name: 'Resveratrol → AMPK activation', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'AMPK phosphorylation triggers autophagy independent of mTOR.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'a4', name: 'Sulforaphane', category: 'compound', evidence: 'B', rank: 4, impact: 6, description: 'NRF2-mediated upregulation of autophagy-related genes in preclinical models.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'a5', name: 'Spermidine', category: 'compound', evidence: 'B', rank: 5, impact: 6, description: 'Induces autophagy via EP300 inhibition. Madeo 2021 memory RCT; dietary epidemiology links intake to longevity.', compoundId: 'spermidine', pmid: '33932338', tnicAvailable: true },
      { id: 'a6', name: 'Urolithin A (Mitopure)', category: 'compound', evidence: 'A', rank: 6, impact: 8, description: 'Activates mitophagy (selective mitochondria autophagy) in human skeletal muscle — Phase 2 RCT confirmed improved muscle mitochondrial gene expression and endurance in older adults (PMID 35391504).', compoundId: 'urolithina', pmid: '35391504', tnicAvailable: true },
    ],
  },
  {
    id: 'mito',
    slug: 'mitochondrial-dysfunction',
    number: 6,
    title: 'Mitochondrial Dysfunction',
    tagline: 'The energy crisis that drives aging',
    summary: 'Mitochondria produce ATP and ROS. With age, biogenesis slows, membrane potential drops, and dysfunctional mitochondria accumulate — reducing energy and increasing oxidative damage.',
    mechanism: 'Mitochondrial ATP production flows through the electron transport chain (ETC): NADH donates electrons at Complex I; FADH2 at Complex II; electrons move through ubiquinone (CoQ10) to Complex III; cytochrome c carries them to Complex IV (oxygen as terminal acceptor); the proton gradient across the inner membrane drives ATP synthase (Complex V). Three parallel failures converge with age: (1) mtDNA somatic mutations accumulate in ETC subunit genes — especially Complex I ND1-ND6 — reducing transfer efficiency and increasing superoxide "leak"; (2) biogenesis slows as the NAD+→SIRT1/3→PGC-1α axis weakens, reducing the transcription of nuclear-encoded ETC subunits; (3) impaired PINK1/Parkin mitophagy lets defective mitochondria accumulate and poison the healthy network via ROS. The SIRT3 (matrix deacetylase) connection is critical: SIRT3 activates Complex I (NDUFA9), Complex II (SDH), and SOD2 by deacetylation — all require NAD+, so the same NAD+ decline that impairs DNA repair also directly reduces ETC efficiency and antioxidant defense simultaneously. Zone 2 exercise uniquely drives PGC-1α nuclear translocation via CaMKII/p38MAPK, stimulating mitochondrial biogenesis that no supplement alone fully replicates.',
    keyMolecules: ['SIRT3', 'PGC-1α', 'PINK1/Parkin', 'CoQ10', 'Complex I–V', 'TFAM', 'SOD2', 'NAD+'],
    whyItMatters: 'Every high-energy organ — heart, brain, skeletal muscle — is acutely sensitive to mitochondrial output decline; VO2 max falls 7–10% per decade in sedentary adults and 3–4% in active ones, tracking almost perfectly with mitochondrial biogenesis capacity. Mitochondrial dysfunction is arguably the most systemically impactful hallmark because it simultaneously elevates ROS (feeding genomic instability and senescence), reduces SIRT3 antioxidant protection (worsening proteostasis), and impairs AMPK signaling (disabling autophagy). NAD+ (via NMN), CoQ10, and Zone 2 training collectively address Complex I efficiency, electron carrier supply, and biogenesis — three non-redundant mechanisms that compound when stacked.',
    visual: 'mito',
    coverage: 95,
    biomarkers: ['NAD+ metabolites', 'Lactate/pyruvate ratio', 'VO2 max', 'Resting metabolic rate'],
    relatedCompoundIds: ['nmn', 'cakg', 'resveratrol', 'rala', 'taurine'],
    mdxSlug: 'mitochondrial-dysfunction',
    personalPrompts: ['Log subjective energy 1–10 daily', 'Track resting heart rate trend', 'Note NAD+ panel results if tested'],
    interventions: [
      { id: 'm1', name: 'NMN / NAD+ precursors', category: 'compound', evidence: 'A', rank: 1, impact: 10, description: 'Restores NAD+ declined ~50% by age 60. Human trials show improved muscle insulin sensitivity and aerobic capacity.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'm2', name: 'Ca-AKG (TCA cycle)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Fuels mitochondrial respiration and collagen synthesis. 12–14% median lifespan extension in mice.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'm3', name: 'Zone 2 aerobic training', category: 'lifestyle', evidence: 'A', rank: 3, impact: 9, description: 'The single strongest lifestyle intervention for mitochondrial biogenesis via PGC-1α.', tnicAvailable: false },
      { id: 'm4', name: 'Resveratrol (mitophagy)', category: 'compound', evidence: 'B', rank: 4, impact: 7, description: 'Promotes clearance of damaged mitochondria via SIRT1/PINK1 pathway.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'm5', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 5, impact: 7, description: 'Cofactor for pyruvate dehydrogenase and complex enzymes; recycles antioxidants in the mitochondrial matrix.', compoundId: 'rala', tnicAvailable: true },
      { id: 'm6', name: 'Taurine', category: 'compound', evidence: 'B', rank: 6, impact: 6, description: 'Age-depleted osmolyte; Singh 2023 Science links deficiency to hallmarks and extends lifespan in animal models.', compoundId: 'taurine', pmid: '37289866', tnicAvailable: true },
      { id: 'm7', name: 'CoQ10 (Ubiquinol)', category: 'compound', evidence: 'B', rank: 7, impact: 7, description: 'Essential electron carrier in Complex I–III of the electron transport chain. Declines ~50% by age 60; ubiquinol form achieves 3× higher plasma levels. Meta-analysis of 17 RCTs confirms reduced hs-CRP and IL-6 (PMID 26267690).', compoundId: 'coq10', pmid: '26267690', tnicAvailable: true },
      { id: 'm8', name: 'Urolithin A (mitophagy)', category: 'compound', evidence: 'A', rank: 8, impact: 8, description: 'Phase 2 RCT confirmed urolithin A activates mitophagy and improves aerobic capacity and muscle strength in adults ≥65 vs placebo (PMID 35391504).', compoundId: 'urolithina', pmid: '35391504', tnicAvailable: true },
    ],
  },
  {
    id: 'senescence',
    slug: 'cellular-senescence',
    number: 7,
    title: 'Cellular Senescence',
    tagline: 'Zombie cells that poison their neighbors',
    summary: 'Senescent cells stop dividing but resist apoptosis, secreting SASP factors (IL-6, MMPs) that drive inflammation and tissue dysfunction.',
    mechanism: 'Senescence is triggered by three main stimuli: critical telomere shortening (replicative senescence, via ATM/p53 DDR), oncogene hyperactivation (OIS, via p16INK4a/Rb pathway), and genotoxic or oxidative stress (SIPS). All three converge on p21CIP1 (p53-dependent) or p16INK4a (p53-independent) — both hypophosphorylate Rb, permanently blocking E2F transcription factors and locking the cell out of division. Rather than dying, senescent cells upregulate the Senescence-Associated Secretory Phenotype (SASP): NF-κB and C/EBPβ drive constitutive secretion of IL-6, IL-8, MMP2/9, VEGF, PAI-1, and TGF-β. These paracrine signals spread dysfunction to neighbors, pushing healthy bystander cells toward senescence (the "infectious" senescence loop). SIRT1 normally suppresses SASP by deacetylating RelA/p65; NAD+ decline with age removes this brake. While senescent cells are only 1–3% of cells in young tissue, they can reach 10–15% in aged or obese tissue, making disproportionately large contributions to systemic inflammation relative to their number.',
    keyMolecules: ['p16INK4a', 'p21CIP1', 'NF-κB', 'C/EBPβ', 'BCL-2/BCL-XL', 'SASP', 'SIRT1', 'RelA/p65'],
    whyItMatters: 'Senescent cells are now recognized as the primary cellular source of the chronic low-grade inflammation (inflammaging) that drives cardiovascular disease, metabolic syndrome, neurodegeneration, and loss of physical function. The transformative finding from ITP lifespan studies is that clearing senescent cells — even starting in midlife — extends healthspan by 20–30% in mice. hs-CRP tracks SASP burden imperfectly but is the most accessible clinical proxy; p16INK4a expression in blood (available via some longevity testing panels) is a more specific readout. Fisetin and D+Q (dasatinib + quercetin) are the most evidence-backed senolytics, with Mayo Clinic RCT data now available for fisetin.',
    visual: 'senescence',
    coverage: 75,
    biomarkers: ['p16INK4a expression', 'SASP cytokine panel', 'Senescence-associated β-gal'],
    relatedCompoundIds: ['nmn', 'resveratrol'],
    mdxSlug: 'cellular-senescence',
    personalPrompts: ['Track hs-CRP as SASP proxy', 'Note joint stiffness / slow healing', 'Log inflammation after poor sleep'],
    interventions: [
      { id: 's1', name: 'Fisetin (senolytic)', category: 'emerging', evidence: 'B', rank: 1, impact: 7, description: 'Mayo Clinic trials underway. Flavonoid selectively clears senescent cells in mouse models.', pmid: '30279143', tnicAvailable: false },
      { id: 's2', name: 'NMN (senescence prevention)', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'NAD+ restoration delays senescence entry in cell culture via sirtuin-mediated genome stability.', compoundId: 'nmn', tnicAvailable: true },
      { id: 's3', name: 'Resveratrol (SASP modulation)', category: 'compound', evidence: 'B', rank: 3, impact: 6, description: 'Reduces NF-κB-driven SASP secretion in preclinical senescence models.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 's4', name: 'Exercise', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Clears senescent cells via immune surveillance and reduces SASP in adipose tissue.', tnicAvailable: false },
      { id: 's5', name: 'Dasatinib + Quercetin protocol', category: 'clinical', evidence: 'B', rank: 5, impact: 7, description: 'Physician-supervised senolytic combo. Human pilot data in IPF and diabetic kidney disease.', pmid: '30616957', tnicAvailable: false },
      { id: 's6', name: 'Fisetin (senolytic flavonoid)', category: 'compound', evidence: 'B', rank: 6, impact: 7, description: 'Mayo Clinic pilot RCT showed pulse-dose fisetin (20mg/kg × 2 days/month) significantly reduced p16INK4A and p21 senescence markers and improved physical function in older adults (PMID 31760212). Multiple Phase 2 trials active.', compoundId: 'fisetin', pmid: '31760212', tnicAvailable: true },
    ],
  },
  {
    id: 'stem',
    slug: 'stem-cell-exhaustion',
    number: 8,
    title: 'Stem Cell Exhaustion',
    tagline: 'Regenerative capacity runs dry',
    summary: 'Tissue-specific stem cell pools decline in number and function, impairing repair of muscle, skin, blood, and gut lining.',
    mechanism: 'Tissue-resident stem cells maintain organs by balancing symmetric self-renewal with asymmetric differentiation. With age, both pool size and functional capacity decline: hematopoietic stem cells (HSCs) expand numerically but show myeloid skewing (reduced lymphoid output, explaining immune narrowing); intestinal LGR5+ crypt cells decline impairing gut renewal; muscle satellite cells lose Notch-dependent activation after injury. The niche microenvironment drives much of the decline — SASP from adjacent senescent cells signals via Wnt antagonists and TGF-β to suppress quiescence-exit; systemic inflammaging activates p38-MAPK in stem cells, triggering premature differentiation before self-renewal is complete. NAD+-SIRT1 signaling maintains stem cell quiescence by repressing genes that drive premature differentiation; AKG as a TET dioxygenase cofactor keeps the promoters of pluripotency/self-renewal genes (OCT4, SOX2, NANOG) hypomethylated and accessible. Parabiosis experiments (young-to-old blood exchange) partially restore aged satellite cell activation via circulating TIMP2, GDF11, and β2-microglobulin normalization, confirming niche signaling reversibility.',
    keyMolecules: ['LGR5+', 'SIRT1', 'Notch', 'WNT/β-catenin', 'p38-MAPK', 'TGF-β', 'AKG', 'OCT4/SOX2'],
    whyItMatters: 'Stem cell decline is the cellular basis for slower wound healing, sarcopenia (accelerating after 60 at 1–2% muscle mass per year), immune repertoire narrowing (thymic involution), and impaired gut mucosal renewal. Unlike many hallmarks, stem exhaustion has a strong lifestyle leverage point: progressive resistance training is the most robust stimulus for muscle satellite cell activation in humans, with documented retention of satellite cell number and function in masters athletes vs sedentary peers. Reducing inflammaging (NRF2 stack + fisetin senolytics) addresses the niche suppression mechanism in parallel.',
    visual: 'stem',
    coverage: 68,
    biomarkers: ['CD34+ cell count', 'Wound healing time', 'Muscle recovery rate'],
    relatedCompoundIds: ['cakg', 'nmn'],
    mdxSlug: 'stem-cell-exhaustion',
    personalPrompts: ['Track workout recovery days needed', 'Note skin healing after cuts', 'Log illness recovery duration'],
    interventions: [
      { id: 'st1', name: 'Ca-AKG (stem niche support)', category: 'compound', evidence: 'A', rank: 1, impact: 7, description: 'Supports collagen synthesis and stem cell quiescence in bone marrow niches.', compoundId: 'cakg', tnicAvailable: true },
      { id: 'st2', name: 'NMN (NAD+ stem maintenance)', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'NAD+ required for stem cell self-renewal and differentiation in hematopoietic models.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'st3', name: 'Resistance training', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'Satellite cell activation in muscle is the best-studied stem cell stimulus in humans.', tnicAvailable: false },
      { id: 'st4', name: 'Reduce chronic inflammation', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Inflammaging suppresses stem cell niches. NRF2 stack targets upstream SASP drivers.', tnicAvailable: false },
      { id: 'st5', name: 'Young plasma / exosome therapies', category: 'emerging', evidence: 'C', rank: 5, impact: 4, description: 'Parabiosis research intriguing but not clinically available for consumers.', tnicAvailable: false },
    ],
  },
  {
    id: 'communication',
    slug: 'altered-intercellular-communication',
    number: 9,
    title: 'Altered Intercellular Communication',
    tagline: 'When cells stop talking correctly',
    summary: 'Hormonal, neuronal, and immune signaling networks become dysregulated. SASP from senescent cells hijacks normal paracrine signaling.',
    mechanism: 'Intercellular communication uses four modalities that all degrade with age: (1) endocrine — GH pulse amplitude halves per decade after 30, DHEA-S declines 80% by age 70, sex steroid rhythms flatten, and insulin resistance desensitizes receptor networks; (2) paracrine/autocrine — SASP cytokines (IL-6, TNF-α, MMP-3) hijack local receptor binding sites, reducing signal-to-noise for legitimate growth factor communication; (3) neuronal — vagal tone declines, increasing sympathetic dominance and elevating resting cortisol/norepinephrine, which suppresses immune function and amplifies NF-κB; (4) extracellular vesicle (EV/exosome) signaling — aged cells release EVs loaded with inflammatory miRNAs (miR-21, miR-146a) and dysfunctional proteins that prime recipient cells for senescence. The hypothalamus-pituitary axis is a systemic aging pacemaker: GnRH production declines, driving downstream reproductive axis collapse, and hypothalamic NF-κB activation directly accelerates systemic aging in mouse models via this neuroendocrine hub. Resolvins and protectins (EPA/DHA-derived SPMs) bind GPR32 and FPR2 to actively terminate paracrine inflammatory cascades — making omega-3 status a rate-limiter for signal clarity restoration.',
    keyMolecules: ['NF-κB', 'GnRH', 'GPR32/FPR2', 'TNF-α', 'IL-6', 'miR-21', 'DHEA-S', 'SPMs'],
    whyItMatters: 'Altered intercellular communication is uniquely positioned as both upstream (driving other hallmarks via neuroendocrine and paracrine disruption) and downstream (receiving SASP and immune signals from senescence and inflammation). Cortisol rhythm normalization — achieved through sleep consistency, stress reduction, and HRV training — has the broadest cross-hallmark benefit: it reduces hypothalamic NF-κB, improves GH pulsatility, and restores insulin receptor sensitivity simultaneously. Track the combo of fasting insulin (HOMA-IR) + hs-CRP + 24h cortisol rhythm as the three-pillar intercellular communication readout.',
    visual: 'signaling',
    coverage: 68,
    biomarkers: ['IL-6', 'TNF-α', 'Insulin / HOMA-IR', 'Cortisol rhythm'],
    relatedCompoundIds: ['resveratrol', 'sulforaphane', 'glynac', 'omega3', 'taurine'],
    mdxSlug: 'altered-intercellular-communication',
    personalPrompts: ['Track mood and social energy', 'Log blood sugar patterns', 'Note hormone panel dates'],
    interventions: [
      { id: 'c1', name: 'Anti-inflammatory stack (NRF2)', category: 'compound', evidence: 'A', rank: 1, impact: 7, description: 'Sulforaphane + GlyNAC reduce SASP-driven signaling disruption at the source.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'c2', name: 'Resveratrol (NF-κB modulation)', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'Inhibits inflammatory transcription factors that amplify intercellular damage signals.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'c3', name: 'Sleep / circadian alignment', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'Melatonin, cortisol, and GH pulses coordinate tissue repair. Misalignment disrupts all signaling.', tnicAvailable: false },
      { id: 'c4', name: 'Insulin sensitivity optimization', category: 'lifestyle', evidence: 'A', rank: 4, impact: 8, description: 'Metabolic health is the master regulator of intercellular hormone signaling.', tnicAvailable: false },
      { id: 'c5', name: 'Fisetin (senolytic, SASP removal)', category: 'compound', evidence: 'B', rank: 5, impact: 7, description: 'Removing SASP-secreting senescent cells restores normal paracrine signaling. Fisetin Mayo pilot (PMID 31760212) confirmed reduced p16/p21 burden and improved function — the most accessible consumer senolytic option.', compoundId: 'fisetin', pmid: '31760212', tnicAvailable: true },
      { id: 'c6', name: 'Omega-3 SPM axis (cytokine resolution)', category: 'compound', evidence: 'A', rank: 6, impact: 7, description: 'EPA/DHA-derived resolvins (D1/D2/E1) and protectins (NPD1) bind GPR32 and FPR2 to actively terminate paracrine cytokine cascades — not passive suppressors but active resolution mediators. REDUCE-IT (PMID 30145934) confirmed 25% cardiovascular event reduction; mechanistic data shows SPM restoration of normal paracrine signaling.', compoundId: 'omega3', pmid: '30145934', tnicAvailable: true },
      { id: 'c7', name: 'Taurine (neuroendocrine support)', category: 'compound', evidence: 'B', rank: 7, impact: 6, description: 'Taurine declines ∼80% with age (Singh 2023, Science) and serves as an osmolyte and Ca2+ buffer in neuroendocrine secretory cells — GH, LH/FSH, and cortisol pulse regulators depend on taurine for vesicle exocytosis. Taurine supplementation restored GH pulsatility in aging mouse models; human data on endocrine signaling emerging.', compoundId: 'taurine', pmid: '37289866', tnicAvailable: true },
      { id: 'c8', name: 'Hormone panel baseline', category: 'clinical', evidence: 'A', rank: 8, impact: 7, description: 'Comprehensive panel (fasting insulin, IGF-1, DHEA-S, total/free testosterone, estradiol, cortisol AM/PM) at baseline and 12-month intervals. Neuroendocrine decline is the most under-tracked driver of intercellular communication failure — clinical optimization targets are well-established for each axis.', tnicAvailable: false },
    ],
  },
  {
    id: 'inflammation',
    slug: 'chronic-inflammation',
    number: 10,
    title: 'Chronic Inflammation',
    tagline: 'Inflammaging — the silent accelerator',
    summary: 'Low-grade systemic inflammation increases with age (inflammaging), driven by SASP, gut permeability, and immune senescence. Measured clinically by hs-CRP.',
    mechanism: 'Inflammaging is fueled by three converging sources: (1) SASP from accumulating senescent cells — NF-κB and C/EBPβ drive constitutive IL-6, IL-8, and MMP secretion independent of pathogen presence; (2) gut barrier leak — LPS endotoxin from gram-negative bacteria crosses a permeable intestinal epithelium and binds TLR4 on macrophages, activating MyD88/TRIF/NF-κB to produce TNF-α, IL-1β, and IL-6; (3) mtDNA damage — dysfunctional mitochondria release mtDNA and cardiolipin into the cytoplasm, where cGAS detects cytosolic DNA and activates STING → TBK1 → IRF3, producing type I interferons and additional NF-κB activation. NF-κB activation requires IKKβ phosphorylation to release the IκB inhibitor; GSH-S-nitrosylation of IKKβ normally holds it inactive — when glutathione falls below threshold, IKKβ becomes constitutively active at sub-threshold stimuli. NRF2 counterbalances via HO-1 upregulation (degrades pro-inflammatory heme), direct KEAP1-competitive NF-κB suppression, and GCLC/GCLM-driven GSH resynthesis. EPA/DHA-derived specialized pro-resolving mediators (resolvins D/E, protectins, maresins) actively terminate inflammatory cascades via dedicated GPCRs — they are the body\'s resolution system, not mere suppressants.',
    keyMolecules: ['NF-κB', 'IKKβ', 'TLR4', 'MyD88', 'cGAS-STING', 'HO-1', 'GSH', 'NRF2'],
    whyItMatters: 'hs-CRP above 1 mg/L doubles 10-year cardiovascular risk; above 3 mg/L it triples — and ∼40% of "healthy" adults over 50 are in this range. Inflammaging drives every other hallmark: it shortens telomeres via ROS, silences PGC-1α to suppress mitochondrial biogenesis, exhausts stem niches via IL-6 and p38-MAPK, and accelerates the epigenetic clock via DNMT3A recruitment. The practical first-order priority is fixing hs-CRP — targeting sulforaphane + GlyNAC + omega-3 together addresses NF-κB, GSH-IKKβ, and SPM resolution arms simultaneously.',
    visual: 'inflammation',
    coverage: 88,
    biomarkers: ['hs-CRP', 'IL-6', 'Homocysteine', 'Fibrinogen'],
    relatedCompoundIds: ['sulforaphane', 'glynac', 'resveratrol'],
    mdxSlug: 'chronic-inflammation',
    personalPrompts: ['Log hs-CRP in Lab Tracker', 'Track post-meal bloating', 'Note joint pain patterns'],
    interventions: [
      { id: 'i1', name: 'Sulforaphane (NRF2 anti-inflammatory)', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Suppresses NF-κB via NRF2-ARE pathway. Reduces CRP in human airway studies.', compoundId: 'sulforaphane', pmid: '27356680', tnicAvailable: true },
      { id: 'i2', name: 'GlyNAC (glutathione / ROS)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Reduces oxidative drivers of inflammation. Human trials show improved inflammatory markers.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 'i3', name: 'Resveratrol (NF-κB / SIRT1)', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Modulates inflammatory gene expression via SIRT1 deacetylation of NF-κB subunits.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'i4', name: 'Omega-3 (EPA+DHA)', category: 'compound', evidence: 'A', rank: 4, impact: 8, description: 'EPA/DHA generate resolvins, protectins, and maresins — specialized pro-resolving mediators that actively terminate inflammation. REDUCE-IT trial: 4g/day EPA reduced cardiovascular events 25% (PMID 30145934). Meta-analysis: significant hs-CRP and IL-6 reduction.', compoundId: 'omega3', pmid: '30145934', tnicAvailable: true },
      { id: 'i5', name: 'Zone 2 + resistance exercise', category: 'lifestyle', evidence: 'A', rank: 5, impact: 8, description: 'Myokines (IL-6 transient, IL-10 sustained) reprogram immune tone with training.', tnicAvailable: false },
    ],
  },
  {
    id: 'dysbiosis',
    slug: 'dysbiosis',
    number: 11,
    title: 'Dysbiosis',
    tagline: 'When the microbiome turns against you',
    summary: 'Age-related shifts in gut microbiota composition increase permeability ("leaky gut"), endotoxin translocation, and systemic inflammation.',
    mechanism: 'The gut-inflammaging axis operates through three parallel channels: (1) barrier permeability — tight junction proteins (claudin-1, occludin, ZO-1) require constant renewal from LGR5+ crypt stem cells every 3–5 days; age-related stem cell decline and NF-κB-driven inflammation loosen junctions, allowing LPS endotoxin (from gram-negative bacteria) to translocate and activate TLR4 on lamina propria macrophages; (2) SCFA deficit — Faecalibacterium prausnitzii and Bifidobacterium species ferment dietary fiber to butyrate, propionate, and acetate; butyrate fuels colonocytes, activates HCAR2/GPR109a to suppress NF-κB, and inhibits HDAC1/2/3 in immune cells to reduce inflammatory gene expression; fiber-restricted diets collapse butyrate production within days; (3) microbiome–NAD+ axis — Akkermansia muciniphila and related commensals synthesize NMN/NR precursors that contribute to the host NAD+ pool; dysbiosis reduces this microbial NAD+ contribution. Zonulin (prehaptoglobin 2) is the only clinically available gut permeability biomarker and precedes CRP elevation, providing an early-warning signal before systemic inflammaging takes hold.',
    keyMolecules: ['ZO-1/claudin-1', 'TLR4', 'HCAR2/GPR109a', 'HDAC1/2/3', 'butyrate', 'Akkermansia', 'zonulin', 'LPS'],
    whyItMatters: 'The gut is a systems multiplier: it directly controls ∼70% of systemic serotonin (affecting mood and gut motility), trains 70% of the immune system (gut-associated lymphoid tissue), and modulates systemic NAD+ availability via microbial synthesis. A single course of broad-spectrum antibiotics can reduce microbiome diversity by 50% with incomplete recovery over 1–2 years, illustrating how fragile this system is. Food-first is non-negotiable: no compound in the TNiC library corrects the metabolic dysfunction caused by sub-25g/day fiber intake — diverse plant foods must come before any supplement consideration.',
    visual: 'gut',
    coverage: 52,
    biomarkers: ['Zonulin', 'Calprotectin', 'Microbiome diversity index', 'SCFA levels'],
    relatedCompoundIds: ['sulforaphane', 'omega3'],
    mdxSlug: 'dysbiosis',
    personalPrompts: ['Log fiber intake daily', 'Track digestive symptoms', 'Note antibiotic courses'],
    interventions: [
      { id: 'd1', name: 'Diverse fiber / prebiotics', category: 'lifestyle', evidence: 'A', rank: 1, impact: 9, description: '30+ plant species per week feeds SCFA-producing taxa (F. prausnitzii, Bifidobacterium) that produce butyrate — the primary colonocyte fuel and NF-κB suppressor via HCAR2/GPR109a. Strongest, most replicable gut intervention available.', tnicAvailable: false },
      { id: 'd2', name: 'Fermented foods (6 servings/day)', category: 'lifestyle', evidence: 'A', rank: 2, impact: 8, description: 'Stanford RCT (n=36, Cell 2021, PMID 34256014): 10-week high-fermented-food diet increased microbiome diversity 26% and reduced 19 inflammatory proteins including IL-6 and IL-12 — outperforming a matched high-fiber group for anti-inflammatory remodeling. Kefir, kimchi, sauerkraut, yogurt all qualify.', pmid: '34256014', tnicAvailable: false },
      { id: 'd3', name: 'Sulforaphane (gut NRF2 + barrier)', category: 'compound', evidence: 'B', rank: 3, impact: 6, description: 'NRF2 activation in gut epithelium upregulates tight-junction proteins (claudin-1, ZO-1) in preclinical models; reduces LPS-driven NF-κB activation in gut macrophages. The most relevant TNiC compound for gut barrier support.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'd4', name: 'Omega-3 (EPA/DHA gut barrier)', category: 'compound', evidence: 'B', rank: 4, impact: 6, description: 'EPA and DHA reduce intestinal permeability by modulating tight junction expression, shift microbiota composition toward anti-inflammatory species, and reduce LPS translocation. Strong mechanistic + observational data; randomized human gut-specific trials emerging.', compoundId: 'omega3', tnicAvailable: true },
      { id: 'd5', name: 'Targeted probiotics', category: 'compound', evidence: 'B', rank: 5, impact: 5, description: 'Akkermansia muciniphila (Pendulum) and Bifidobacterium longum strains show promise in improving barrier function and reducing metabolic endotoxemia in pilot RCTs. Strain-specific — random multi-strain products have minimal replication.', tnicAvailable: false },
      { id: 'd6', name: 'Microbiome testing', category: 'clinical', evidence: 'B', rank: 6, impact: 4, description: 'Viome, Thorne Onegevity, or clinical metagenomics (Genova, Doctor\'s Data) to baseline diversity and track intervention response at 8–12 weeks. Useful for identifying SIBO, Akkermansia deficit, or dysbiosis-specific interventions.', tnicAvailable: false },
    ],
  },
  {
    id: 'nutrient',
    slug: 'disabled-macroautophagy',
    number: 12,
    title: 'Disabled Macroautophagy',
    tagline: 'Nutrient sensing gone wrong',
    summary: 'mTOR and AMPK — the nutrient sensing kinases — become dysregulated. Chronic nutrient surplus suppresses autophagy; AMPK activity declines with age.',
    mechanism: 'Two antagonistic kinase complexes implement nutrient sensing: mTORC1 (activated by amino acids via Ragulator/Rag GTPases sensing intra-lysosomal amino acids, by growth factors via PI3K/Akt, and by ROS) promotes protein synthesis, lipogenesis, and ribosome biogenesis while directly phosphorylating and inactivating ULK1 at Ser757 to suppress autophagy; AMPK (activated by rising AMP:ATP ratio via LKB1, and by CAMKK2 during Ca2+ transients) counteracts mTORC1 by phosphorylating Raptor at Ser792 and activating ULK1 at Ser317/777. With age, mTORC1 becomes chronically hyperactivated via three mechanisms: impaired AMPK sensitivity as mitochondrial efficiency declines; elevated branched-chain amino acids from sarcopenic muscle catabolism constitutively stimulating Ragulator; and broken S6K1 negative feedback (S6K1 normally phosphorylates IRS-1 Ser307 to limit insulin signaling, but chronic S6K1 activity converts this to pathological insulin resistance). Rapamycin inhibits mTORC1 by forming an FKBP12 complex that occludes the active site; this mechanism explains its 10–15% mean lifespan extension across 20+ mammalian studies. Metformin and berberine activate AMPK via Complex I inhibition, raising AMP:ATP; caloric restriction works by reducing Ragulator amino acid sensing input — all three therefore restore autophagy and reduce anabolic mTOR overdrive via the same AMPK/mTOR balance.',
    keyMolecules: ['mTORC1', 'AMPK', 'Raptor', 'ULK1', 'S6K1', 'FKBP12', 'Ragulator', 'LKB1'],
    whyItMatters: 'Rapamycin is the single most replicated longevity drug across mammalian models, demonstrating that mTOR dysregulation is not merely correlated with aging but causally drives it. The consumer-accessible equivalent is optimizing the fasting/feeding cycle: even 14–16 hours of fasting allows AMPK to suppress mTOR, trigger autophagy, and initiate cellular maintenance programs that continuous eating blocks. Fasting insulin (HOMA-IR) and ketone bodies are the two most accessible clinical readouts of mTOR/AMPK balance — a fasting insulin below 5 μIU/mL indicates well-calibrated nutrient sensing.',
    visual: 'nutrient',
    coverage: 72,
    biomarkers: ['Fasting insulin', 'IGF-1', 'Ketone bodies', 'mTOR activity proxies'],
    relatedCompoundIds: ['resveratrol', 'nmn'],
    mdxSlug: 'disabled-macroautophagy',
    personalPrompts: ['Log daily eating window', 'Track fasting glucose', 'Note protein intake timing'],
    interventions: [
      { id: 'n1', name: 'Caloric moderation / fasting', category: 'lifestyle', evidence: 'A', rank: 1, impact: 9, description: 'Caloric restriction is the oldest lifespan intervention in mammals. mTOR suppression is the mechanism.', tnicAvailable: false },
      { id: 'n2', name: 'Resveratrol → AMPK', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'Activates AMPK, mimicking energy deficit and promoting autophagy and mitochondrial biogenesis.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'n3', name: 'NMN → SIRT1/mTOR balance', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Sirtuins counterbalance mTOR signaling; NAD+ decline removes this brake with age.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'n4', name: 'Metformin (AMPK activator)', category: 'clinical', evidence: 'B', rank: 4, impact: 7, description: 'TAME trial — first FDA-approved trial targeting biological aging itself. Metformin activates AMPK via Complex I inhibition. Diabetics on metformin outlive age-matched non-diabetic controls — extraordinary longevity signal (PMID 32910831).', pmid: '32910831', tnicAvailable: false },
      { id: 'n6', name: 'Berberine (AMPK activator)', category: 'compound', evidence: 'A', rank: 6, impact: 7, description: 'Activates AMPK comparably to metformin. Head-to-head RCT: berberine 500mg TID reduced HbA1c 2.0% and fasting glucose 20% — equivalent to metformin (PMID 18396172). AMPK activation inhibits mTOR and restores autophagy signaling.', compoundId: 'berberine', pmid: '18396172', tnicAvailable: true },
      { id: 'n5', name: 'Rapamycin (mTOR inhibitor)', category: 'emerging', evidence: 'B', rank: 5, impact: 8, description: 'PEARL trial and dog aging studies. Prescription-only; immunosuppressive risks require physician oversight.', pmid: '19587683', tnicAvailable: false },
    ],
  },
];

export function getHallmarkBySlug(slug: string) {
  return hallmarkLibrary.find((h) => h.slug === slug);
}

export function getHallmarkById(id: string) {
  return hallmarkLibrary.find((h) => h.id === id);
}