/** High-intent routes — request indexing in GSC and surface in footer/HTML sitemap first */
export const PRIORITY_INDEX_PATHS = [
  '/',
  '/supplement-guides',
  '/longevity-supplements-guide',
  '/library',
  '/library/compare',
  '/library/compare/nmn-vs-nr',
  '/library/compare/glynac-vs-liposomal-glutathione',
  '/library/compare/sulforaphane-vs-curcumin',
  '/library/compare/resveratrol-vs-pterostilbene',
  '/library/compare/berberine-vs-metformin',
  '/library/compare/fisetin-vs-quercetin',
  '/library/compare/taurine-vs-nmn',
  '/library/compare/cakg-vs-spermidine',
  '/library/compare/rapamycin-vs-metformin',
  '/library/compare/coq10-vs-ubiquinol',
  '/library/compare/omega3-vs-krill-oil',
  '/library/compounds/nmn',
  '/library/compounds/nr',
  '/library/compounds/glynac',
  '/library/compounds/sulforaphane',
  '/library/compounds/taurine',
  '/library/compounds/berberine',
  '/library/compounds/spermidine',
  '/library/compounds/cakg',
  '/library/compounds/urolithina',
  '/library/compounds/rapamycin',
  '/library/compounds/pterostilbene',
  '/library/mitochondrial-dysfunction',
  '/library/cellular-senescence',
  '/library/genomic-instability',
  '/faq',
  '/quiz',
  '/stacks',
  '/learn',
  '/brief',
  '/products',
  '/shop',
  '/elite-8',
  '/nad-supplement-guide',
  '/glynac-supplement-guide',
  '/berberine-supplement-guide',
  '/taurine-supplement-guide',
  '/sulforaphane-supplement-guide',
  '/spermidine-supplement-guide',
  '/site-map',
] as const;

export const POPULAR_GUIDE_LINKS = [
  { href: '/supplement-guides', label: 'All Supplement Guides Hub' },
  { href: '/longevity-supplements-guide', label: 'Best Longevity Supplements 2026' },
  { href: '/nad-supplement-guide', label: 'NAD+ Supplement Guide 2026' },
  { href: '/glynac-supplement-guide', label: 'GlyNAC Supplement Guide 2026' },
  { href: '/berberine-supplement-guide', label: "Berberine Guide — Nature's Ozempic Reality Check" },
  { href: '/taurine-supplement-guide', label: 'Taurine Longevity Guide — Science 2023 Paper' },
  { href: '/sulforaphane-supplement-guide', label: 'Sulforaphane & NRF2 Guide' },
  { href: '/spermidine-supplement-guide', label: 'Spermidine Guide — Autophagy & ITP Data' },
  { href: '/library/compare/nmn-vs-nr', label: 'NMN vs NR' },
  { href: '/library/compounds/nmn', label: 'NMN Guide' },
  { href: '/library/compounds/nr', label: 'NR Guide' },
  { href: '/library/compounds/glynac', label: 'GlyNAC Guide' },
  { href: '/library/compounds/sulforaphane', label: 'Sulforaphane' },
  { href: '/library/compounds/taurine', label: 'Taurine Guide' },
  { href: '/library/compounds/berberine', label: 'Berberine Guide' },
  { href: '/library/compounds/spermidine', label: 'Spermidine Guide' },
  { href: '/library/compounds/cakg', label: 'Ca-AKG Guide' },
  { href: '/library/compounds/pterostilbene', label: 'Pterostilbene Guide' },
  { href: '/elite-8', label: 'Elite 8 LQ Ranking' },
  { href: '/library/mitochondrial-dysfunction', label: 'Mitochondrial Health' },
  { href: '/library/compare/fisetin-vs-quercetin', label: 'Fisetin vs Quercetin' },
  { href: '/library/compare/taurine-vs-nmn', label: 'Taurine vs NMN' },
  { href: '/library/compare/rapamycin-vs-metformin', label: 'Rapamycin vs Metformin' },
  { href: '/library/compare/coq10-vs-ubiquinol', label: 'CoQ10 vs Ubiquinol' },
  { href: '/library/compare/omega3-vs-krill-oil', label: 'Omega-3 vs Krill Oil' },
  { href: '/library/compare', label: 'All Comparisons' },
  { href: '/faq', label: 'Longevity FAQ' },
] as const;