/** High-intent routes — request indexing in GSC and surface in footer/HTML sitemap first */
export const PRIORITY_INDEX_PATHS = [
  '/',
  '/library',
  '/library/compare',
  '/library/compare/nmn-vs-nr',
  '/library/compare/glynac-vs-liposomal-glutathione',
  '/library/compare/sulforaphane-vs-curcumin',
  '/library/compare/resveratrol-vs-pterostilbene',
  '/library/compounds/nmn',
  '/library/compounds/nr',
  '/library/compounds/glynac',
  '/library/compounds/sulforaphane',
  '/library/compounds/rapamycin',
  '/library/compounds/taurine',
  '/library/compounds/spermidine',
  '/library/compounds/pterostilbene',
  '/library/compounds/urolithin-a',
  '/library/compounds/quercetin',
  '/library/compounds/fisetin',
  '/library/compounds/apigenin',
  '/library/compounds/omega3',
  '/library/compounds/coq10',
  '/library/compounds/magnesium',
  '/library/compounds/vitamin-d3',
  '/library/compounds/berberine',
  '/library/compounds/curcumin',
  '/library/compounds/egcg',
  '/library/compounds/creatine',
  '/library/compounds/tmg',
  '/library/compounds/ashwagandha',
  '/library/compounds/lions-mane',
  '/library/compounds/astaxanthin',
  '/library/compounds/lithium-orotate',
  '/library/compounds/collagen',
  '/library/compounds/melatonin',
  '/library/compounds/glycine',
  '/library/compounds/glucosamine',
  '/library/compounds/alpha-gpc',
  '/library/compounds/selenium',
  '/library/compounds/zinc',
  '/library/compounds/pqq',
  '/library/compounds/ergothioneine',
  '/library/compounds/phosphatidylserine',
  '/library/compounds/saffron',
  '/library/compounds/boron',
  '/library/compounds/liposomal-glutathione',
  '/library/compounds/beta-glucan',
  '/library/compounds/hyaluronic-acid',
  '/library/compounds/bacopa',
  '/library/compounds/ghk-cu',
  '/library/compounds/carnosine',
  '/library/compounds/nicotinamide',
  '/library/compounds/5-ala',
  '/library/compounds/rhodiola',
  '/library/compounds/honokiol',
  '/library/compounds/shilajit',
  '/library/mitochondrial-dysfunction',
  '/library/cellular-senescence',
  '/hallmarks',
  '/hallmarks/genomic-instability',
  '/hallmarks/telomere-attrition',
  '/hallmarks/epigenetic-alterations',
  '/hallmarks/loss-of-proteostasis',
  '/hallmarks/disabled-autophagy',
  '/hallmarks/mitochondrial-dysfunction',
  '/hallmarks/cellular-senescence',
  '/hallmarks/stem-cell-exhaustion',
  '/hallmarks/altered-intercellular-communication',
  '/hallmarks/chronic-inflammation',
  '/hallmarks/dysbiosis',
  '/hallmarks/disabled-macroautophagy',
  '/faq',
  '/quiz',
  '/stacks',
  '/learn',
  '/brief',
  '/products',
  '/shop',
  '/elite-8',
  '/site-map',
] as const;

export const POPULAR_GUIDE_LINKS = [
  { href: '/hallmarks/chronic-inflammation', label: 'Chronic Inflammation' },
  { href: '/hallmarks/mitochondrial-dysfunction', label: 'Mitochondrial Dysfunction' },
  { href: '/hallmarks/cellular-senescence', label: 'Cellular Senescence' },
  { href: '/hallmarks/telomere-attrition', label: 'Telomere Attrition' },
  { href: '/library/compare/nmn-vs-nr', label: 'NMN vs NR' },
  { href: '/library/compounds/nmn', label: 'NMN Guide' },
  { href: '/library/compounds/glynac', label: 'GlyNAC Guide' },
  { href: '/library/compounds/sulforaphane', label: 'Sulforaphane' },
  { href: '/elite-8', label: 'Elite 8 LQ Ranking' },
  { href: '/library/compare', label: 'All Comparisons' },
  { href: '/faq', label: 'Longevity FAQ' },
] as const;