import type { EvidenceTier } from './types';

export type LibraryModuleCategory = 'compounds' | 'synergies' | 'lifestyle' | 'guides';

export interface LibraryModule {
  slug: string;
  category: LibraryModuleCategory;
  title: string;
  tagline: string;
  summary: string;
  evidenceTier: EvidenceTier;
  relatedHallmarkIds: string[];
  compoundId?: string;
  synergyCompoundIds?: string[];
  relatedSynergySlugs?: string[];
  requiresDisclaimer?: boolean;
  outline: string[];
  mdxSlug: string;
}

export const libraryCategoryMeta: Record<
  LibraryModuleCategory,
  { label: string; description: string; hubOrder: number }
> = {
  compounds: {
    label: 'Compound Deep-Dives',
    description:
      'Mechanism, evidence tiers, dosing protocols, monitoring checklists, and personal results templates for each intervention.',
    hubOrder: 1,
  },
  synergies: {
    label: 'Synergy Guides',
    description:
      'Multi-compound combinations with mechanistic rationale, trial data, timing choreography, and contraindication notes.',
    hubOrder: 2,
  },
  lifestyle: {
    label: 'Lifestyle Pillars',
    description:
      'Exercise, sleep, nutrition, and stress — mapped to hallmarks with actionable protocols and biomarker tie-ins.',
    hubOrder: 3,
  },
  guides: {
    label: 'Testing & Monitoring',
    description:
      'What to test, when to retest, how to interpret trends, and how lab data connects to your stack.',
    hubOrder: 4,
  },
};

export const libraryModules: LibraryModule[] = [
  // ── Compounds ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac',
    category: 'compounds',
    title: 'GlyNAC (Glycine + NAC)',
    tagline: 'Flagship glutathione restoration — human RCT backbone',
    summary:
      'Dual-precursor strategy rebuilding the glutathione triad (GSH, cysteine, glycine). Tier A human data for oxidative stress, mitochondrial function, and inflammaging markers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation', 'genomic'],
    compoundId: 'glynac',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & hallmark mapping',
      'Mechanism: GSH synthesis bottleneck',
      'Evidence summary (Kumar et al. RCTs)',
      'Dosing protocol (AM/PM, cycling)',
      'Monitoring: GSH, 8-OHdG, hs-CRP',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'glynac',
  },
  {
    slug: 'nmn',
    category: 'compounds',
    title: 'NMN (Nicotinamide Mononucleotide)',
    tagline: 'NAD+ precursor — sirtuin and PARP fuel',
    summary:
      'Direct NAD+ precursor bypassing NAMPT rate-limiting step. Restores NAD+ pools that decline ~50% between ages 40–60, activating SIRT1/3, DNA repair, and mitophagy.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    compoundId: 'nmn',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & NAD+ decline curve',
      'Mechanism: NMN → NAD+ → SIRT/PARP axis',
      'Evidence summary (human PK + biomarkers)',
      'Dosing protocol & resveratrol pairing',
      'Monitoring: NAD+ index, metabolic markers',
      'Safety & methyl donor considerations',
      'Personal results template',
    ],
    mdxSlug: 'nmn',
  },
  {
    slug: 'nr',
    category: 'compounds',
    title: 'NR (Nicotinamide Riboside)',
    tagline: 'NAD+ precursor alternative — human RCT data, manual stack substitution',
    summary:
      'Legitimate NAD+ precursor with human trial footprint. TNiC defaults to NMN for stack integration; this module covers when NR is the right choice, dosing, buyer verification, and compare-table evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    relatedSynergySlugs: ['nad-mito-stack', 'nmn-resveratrol-sirt1'],
    outline: [
      'Overview & NR → NMN → NAD+ pathway',
      'When to choose NR vs NMN',
      'Evidence summary (Martens, Trammell)',
      'Dosing & NR-Cl form requirements',
      'TNiC stack substitution guide',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'nr',
  },
  {
    slug: 'rapamycin',
    category: 'compounds',
    title: 'Rapamycin (Sirolimus)',
    tagline: 'mTORC1 inhibition — strongest preclinical lifespan drug',
    summary:
      'Educational deep-dive on the most replicated lifespan-extending pharmacological intervention. Prescription-only; immunosuppressive risks require physician oversight.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'nutrient', 'senescence', 'mito'],
    requiresDisclaimer: true,
    relatedSynergySlugs: [],
    outline: [
      'Overview & mTOR/AMPK balance',
      'Mechanism: mTORC1 → autophagy induction',
      'Evidence: mouse, dog, PEARL trial',
      'Decision tree & physician checklist',
      'Dosing paradigms (pulse vs continuous)',
      'Monitoring: CBC, lipids, infection vigilance',
      'Buyer/sourcing guide (Rx only)',
      'Personal results template (physician-supervised)',
    ],
    mdxSlug: 'rapamycin',
  },
  {
    slug: 'tudca',
    category: 'compounds',
    title: 'TUDCA (Tauroursodeoxycholic Acid)',
    tagline: 'ER stress chaperone — proteostasis & mitochondrial support',
    summary:
      'Bile acid derivative stabilizing protein folding, reducing ER stress, and supporting mitochondrial membrane integrity. Strong preclinical data; emerging human hepatoprotection studies.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'mito', 'autophagy'],
    relatedSynergySlugs: [],
    outline: [
      'Overview & proteostasis link',
      'Mechanism: UPR modulation & chaperone activity',
      'Evidence summary (preclinical + pilot human)',
      'Decision tree & stack placement',
      'Dosing protocol & compliance checklist',
      'Monitoring: liver panel, GGT',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'tudca',
  },
  {
    slug: 'sulforaphane',
    category: 'compounds',
    title: 'Sulforaphane',
    tagline: 'NRF2 master regulator — 200+ cytoprotective genes',
    summary:
      'Isothiocyanate from broccoli sprouts that covalently modifies KEAP1, releasing NRF2 to drive phase-II detox, proteasome upregulation, and anti-inflammatory gene expression.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'proteostasis'],
    compoundId: 'sulforaphane',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & NRF2 pathway',
      'Mechanism: KEAP1 modification',
      'Evidence summary',
      'Dosing & myrosinase activation',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'sulforaphane',
  },
  {
    slug: 'rala',
    category: 'compounds',
    title: 'R-Alpha Lipoic Acid (R-ALA)',
    tagline: 'Mitochondrial redox recycler — NRF2 stack completion',
    summary:
      'Recycles oxidized glutathione, vitamins C and E. Cofactor for pyruvate dehydrogenase in mitochondria. Completes the NRF2 Defense Triad (substrate → signal → recycle). Tier B in healthy adults; strong mechanistic and metabolic syndrome data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation'],
    compoundId: 'rala',
    relatedSynergySlugs: ['glynac-nrf2-triad', 'nad-mito-stack'],
    outline: [
      'Overview & NRF2 triad placement',
      'Mechanism: redox recycling hub',
      'Evidence summary (neuropathy, metabolic data)',
      'Dosing protocol & enantiomer note',
      'NRF2 Defense Triad choreography',
      'Monitoring: GSH, 8-OHdG, glucose',
      'Safety & interactions',
      'Personal results template',
    ],
    mdxSlug: 'rala',
  },
  {
    slug: 'cakg',
    category: 'compounds',
    title: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    tagline: 'Epigenetic cofactor & TCA fuel — highest hallmark breadth per gram',
    summary:
      'TCA cycle intermediate and obligate cofactor for TET, JMJ, and PHD enzymes that reverse age-related DNA and histone methylation drift. Mouse lifespan +12%; emerging human metabolic and clock data from 2024.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['epigenetic', 'mito', 'stem'],
    compoundId: 'cakg',
    relatedSynergySlugs: ['nad-mito-stack'],
    outline: [
      'Overview & AKG decline curve',
      'Mechanism: TCA anaplerosis + TET/JMJ cofactor',
      'Evidence summary (mouse lifespan + human 2024)',
      'Dosing protocol & titration',
      'NAD+ Mito Stack ramp-in schedule',
      'Monitoring: glucose, hs-CRP, epigenetic clock',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'cakg',
  },
  {
    slug: 'resveratrol',
    category: 'compounds',
    title: 'Trans-Resveratrol',
    tagline: 'SIRT1 activator — caloric restriction mimetic',
    summary:
      'Phytoalexin activating SIRT1 and AMPK. Synergistic with NAD+ precursors for epigenetic and mitochondrial remodeling. Tier B — strong mechanism, mixed human outcomes.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation', 'senescence'],
    compoundId: 'resveratrol',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & SIRT1 axis',
      'Mechanism & bioavailability',
      'Evidence summary',
      'Dosing & NMN pairing (PM timing)',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'resveratrol',
  },
  {
    slug: 'taurine',
    category: 'compounds',
    title: 'Taurine',
    tagline: 'Age-depleted osmolyte — Science 2023 lifespan signals',
    summary:
      'Sulfonic amino acid buffering mitochondrial stress and declining ~80% with age. Tier B: strong Singh 2023 Science mechanism and animal lifespan data; limited human longevity RCT.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic'],
    compoundId: 'taurine',
    outline: [
      'Overview & taurine decline with age',
      'Mechanism: membrane + mitochondrial buffering',
      'Evidence: Singh 2023 Science',
      'Dosing protocol',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'taurine',
  },
  {
    slug: 'spermidine',
    category: 'compounds',
    title: 'Spermidine',
    tagline: 'Autophagy polyamine — Madeo 2021 memory RCT',
    summary:
      'Dietary and supplemental polyamine inducing autophagy via EP300 inhibition. Tier B: human pilot memory outcomes; strong mechanistic autophagy data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'epigenetic', 'senescence'],
    compoundId: 'spermidine',
    outline: [
      'Overview & autophagy induction',
      'Mechanism: EP300 / eIF5A',
      'Evidence: Madeo 2021 Cell RCT',
      'Dosing & dietary sources',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'spermidine',
  },
  {
    slug: 'pterostilbene',
    category: 'compounds',
    title: 'Pterostilbene',
    tagline: 'Methylated resveratrol — 4× bioavailability',
    summary:
      'Stilbenoid SIRT1 activator with superior human PK vs trans-resveratrol. Tier B: Kapetanovic 2011 safety/PK; compare with resveratrol for stack pairing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation'],
    compoundId: 'pterostilbene',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1'],
    outline: [
      'Overview vs resveratrol',
      'Mechanism & bioavailability advantage',
      'Evidence summary',
      'Dosing & NMN pairing',
      'Compare table link',
      'Personal results template',
    ],
    mdxSlug: 'pterostilbene',
  },
  {
    slug: 'nr',
    category: 'compounds',
    title: 'NR (Nicotinamide Riboside)',
    tagline: 'NAD+ precursor alternative — human RCT backbone',
    summary:
      'Orally bioavailable NAD+ precursor with a well-established human trial footprint. Elevates whole-blood NAD+ within days; competes with NMN on cost and is superior for some tissue distributions. Tier A evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    compoundId: 'nr',
    relatedSynergySlugs: ['nad-mito-stack', 'nmn-resveratrol-sirt1'],
    outline: [
      'Overview & NR → NMN → NAD+ pathway',
      'Mechanism: CD73 conversion & tissue distribution',
      'Evidence: Martens 2018, Trammell 2016 RCTs',
      'NR vs NMN decision tree',
      'Dosing protocol (AM, with fat)',
      'Monitoring: NAD+ index, hs-CRP',
      'Buyer guide & NR-Cl form requirements',
      'Personal results template',
    ],
    mdxSlug: 'nr',
  },
  {
    slug: 'urolithin-a',
    category: 'compounds',
    title: 'Urolithin A (Mitopure)',
    tagline: 'Mitophagy activator — Amazentis Phase 2 muscle data',
    summary:
      'Gut-derived polyphenol metabolite that selectively induces mitophagy via PINK1/Parkin pathway. Phase 2 RCT showed significant improvement in muscle strength and endurance in older adults.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'autophagy', 'senescence', 'stem'],
    compoundId: 'urolithin-a',
    outline: [
      'Overview & gut microbiome conversion',
      'Mechanism: PINK1/Parkin mitophagy axis',
      'Evidence: Amazentis Nat Med 2016 + JAMA 2022 RCT',
      'Who cannot convert: urolithin producer status',
      'Dosing protocol (500–1000 mg AM)',
      'Monitoring: muscle function, mitochondrial markers',
      'Buyer guide: Mitopure vs generic UA',
      'Personal results template',
    ],
    mdxSlug: 'urolithin-a',
  },
  {
    slug: 'quercetin',
    category: 'compounds',
    title: 'Quercetin',
    tagline: 'Flavonoid senolytic — dasatinib partner in human pilot',
    summary:
      'Broad-spectrum flavonoid with senolytic activity at high doses (dasatinib + quercetin protocol) and anti-inflammatory NRF2 effects at daily doses. First human senolytic trial published in EBioMedicine 2019.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'inflammation', 'autophagy'],
    compoundId: 'quercetin',
    outline: [
      'Overview & senolytic vs daily dosing modes',
      'Mechanism: Bcl-2 inhibition + NRF2 activation',
      'Evidence: Kirkland EBioMedicine 2019, Mayo pilot',
      'D+Q protocol vs daily quercetin phytosome',
      'Dosing: pulse 1,000 mg × 3 days vs 500 mg/day',
      'Monitoring: p16, SA-β-gal proxies, hs-CRP',
      'Safety: drug interactions (warfarin, antibiotics)',
      'Personal results template',
    ],
    mdxSlug: 'quercetin',
  },
  {
    slug: 'fisetin',
    category: 'compounds',
    title: 'Fisetin',
    tagline: 'Potent flavonoid senolytic — Mayo Clinic preclinical lead',
    summary:
      'Flavonol with the strongest senolytic potency among tested polyphenols in Mayo Clinic screening. Clears senescent cells via apoptosis induction; improves healthspan in aging mouse models. Human pilot data emerging.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'inflammation', 'genomic'],
    compoundId: 'fisetin',
    outline: [
      'Overview & senolytic ranking vs quercetin',
      'Mechanism: Bcl-2/Bcl-xL inhibition, SIRT1 activation',
      'Evidence: Yousefzadeh 2018 EBioMedicine + mouse lifespan',
      'Pulse dosing protocol (20 mg/kg equivalent)',
      'Bioavailability: liposomal form advantage',
      'Monitoring: inflammatory markers, skin markers',
      'Safety & drug interaction notes',
      'Personal results template',
    ],
    mdxSlug: 'fisetin',
  },
  {
    slug: 'apigenin',
    category: 'compounds',
    title: 'Apigenin',
    tagline: 'CD38 inhibitor — NAD+ salvage pathway support',
    summary:
      'Flavone from parsley and chamomile that inhibits CD38 ectoenzyme — the dominant consumer of cellular NAD+. Synergizes with NMN/NR by reducing NAD+ degradation, not just increasing synthesis.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'senescence'],
    compoundId: 'apigenin',
    outline: [
      'Overview & CD38 as NAD+ drain',
      'Mechanism: CD38 inhibition → NAD+ sparing',
      'Evidence: Escande 2013 Chemistry & Biology, Chini 2020',
      'Synergy with NMN/NR (complementary mechanisms)',
      'Dosing protocol (50–100 mg with fat)',
      'Monitoring: NAD+ index, inflammatory markers',
      'Buyer guide: apigenin vs luteolin',
      'Personal results template',
    ],
    mdxSlug: 'apigenin',
  },
  {
    slug: 'omega3',
    category: 'compounds',
    title: 'Omega-3 (EPA + DHA)',
    tagline: 'Tier A anti-inflammatory — telomere and cardiovascular anchor',
    summary:
      'Long-chain polyunsaturated fatty acids EPA and DHA resolve chronic inflammation via SPM pathways, protect telomere length, support mitochondrial membrane integrity, and reduce cardiovascular events in large RCTs.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['inflammation', 'telomere', 'mito', 'genomic', 'stem'],
    compoundId: 'omega3',
    outline: [
      'Overview & SPM resolution pathway',
      'Mechanism: EPA/DHA → SPM → NF-κB suppression',
      'Evidence: REDUCE-IT (NEJM 2019), omega-3 index data',
      'Telomere protection: Farzaneh-Far 2010 JAMA',
      'Dosing: 2–4 g/day EPA+DHA (triglyceride form)',
      'Omega-3 index target (>8%)',
      'Buyer guide: triglyceride vs ethyl ester, IFOS testing',
      'Personal results template',
    ],
    mdxSlug: 'omega3',
  },
  {
    slug: 'coq10',
    category: 'compounds',
    title: 'CoQ10 (Ubiquinol)',
    tagline: 'Mitochondrial electron transport essential — Tier A',
    summary:
      'Fat-soluble quinone essential for Complex I–III electron transfer in the mitochondrial ETC. Plasma CoQ10 declines ~50% between ages 20–80. Ubiquinol (reduced form) has 3–8× superior absorption vs ubiquinone.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'inflammation'],
    compoundId: 'coq10',
    outline: [
      'Overview & ETC placement (Complex I-III)',
      'Mechanism: electron carrier + membrane antioxidant',
      'Evidence: SHIELD trial (HF), statin depletion data',
      'Ubiquinol vs ubiquinone bioavailability comparison',
      'Dosing: 100–300 mg/day with fat (PM preferred)',
      'Who needs it most: statin users, >50 yo',
      'Monitoring: plasma CoQ10 levels',
      'Buyer guide & softgel form requirements',
    ],
    mdxSlug: 'coq10',
  },
  {
    slug: 'magnesium',
    category: 'compounds',
    title: 'Magnesium L-Threonate',
    tagline: 'Cofactor for 300+ enzymes — brain-penetrant form',
    summary:
      'Magnesium participates in ATP synthesis, DNA repair, and 300+ enzymatic reactions. L-Threonate form crosses the blood-brain barrier; clinical trial showed cognitive improvement. >50% of adults are deficient.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['genomic', 'inflammation', 'mito'],
    compoundId: 'magnesium',
    outline: [
      'Overview & magnesium deficiency epidemic',
      'Mechanism: ATP cofactor, DNA repair, Ca2+ antagonism',
      'Evidence: Slutsky 2010 Neuron, TACT-2 cardiac data',
      'L-Threonate vs glycinate vs malate forms',
      'Dosing: 144 mg elemental Mg L-threonate (PM)',
      'Monitoring: RBC magnesium (not serum)',
      'Buyer guide: elemental magnesium content per form',
      'Personal results template',
    ],
    mdxSlug: 'magnesium',
  },
  {
    slug: 'vitamin-d3',
    category: 'compounds',
    title: 'Vitamin D3 + K2',
    tagline: 'Genomic hormone — Tier A immune, bone, and longevity data',
    summary:
      'Vitamin D3 is a genomic hormone regulating 200+ gene targets including immune modulation, telomere maintenance, and calcium metabolism. K2 (MK-7) directs calcium to bone and away from arteries. Tier A evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'telomere', 'senescence', 'stem'],
    compoundId: 'vitamin-d3',
    outline: [
      'Overview & vitamin D as genomic hormone',
      'Mechanism: VDR activation → 200+ gene targets',
      'Evidence: VITAL trial (NEJM 2019), Pludowski meta-analysis',
      'K2 synergy: carboxylation of MGP and osteocalcin',
      'Dosing: 2,000–5,000 IU D3 + 100–200 mcg MK-7',
      'Target 25-OH-D: 40–60 ng/mL',
      'Monitoring: 25-OH-D, calcium, PTH',
      'Buyer guide: D3 vs D2, oil-based capsules',
    ],
    mdxSlug: 'vitamin-d3',
  },
  {
    slug: 'berberine',
    category: 'compounds',
    title: 'Berberine',
    tagline: 'AMPK activator — metformin-class metabolic intervention',
    summary:
      'Isoquinoline alkaloid from Berberis plants that activates AMPK (like metformin), inhibits mTOR, improves insulin sensitivity, and modulates the gut microbiome. Strong RCT data for glucose, lipids, and metabolic health.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'inflammation', 'dysbiosis', 'senescence'],
    compoundId: 'berberine',
    outline: [
      'Overview & AMPK mimicry of metformin',
      'Mechanism: AMPK activation + mTOR inhibition + gut flora',
      'Evidence: Yin 2008 Metabolism RCT, Zhang 2010 lipid data',
      'Berberine vs metformin comparison',
      'Dosing: 500 mg × 3/day with meals (cycling)',
      'Gut effects: Akkermansia upregulation',
      'Monitoring: fasting glucose, HbA1c, lipids',
      'Buyer guide: DHB vs berberine HCl bioavailability',
    ],
    mdxSlug: 'berberine',
  },
  {
    slug: 'curcumin',
    category: 'compounds',
    title: 'Curcumin (Theracurmin / Longvida)',
    tagline: 'NF-κB and NRF2 modulator — bioavailability-critical',
    summary:
      'Polyphenol from turmeric with potent NF-κB inhibition and NRF2 activation. Standard curcumin has <1% oral bioavailability; Theracurmin and Longvida formulations achieve 27–185× improvement. Strong anti-inflammatory RCT data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'proteostasis', 'autophagy', 'genomic'],
    compoundId: 'curcumin',
    outline: [
      'Overview & NF-κB/NRF2 dual action',
      'Mechanism: IKKβ inhibition + KEAP1 modification',
      'Evidence: Lopresti 2018 JACI + Rainey-Smith 2017 RCTs',
      'Bioavailability crisis: standard vs Theracurmin vs Longvida',
      'Dosing: 400 mg Theracurmin or 400 mg Longvida daily',
      'Monitoring: hs-CRP, IL-6, cognitive markers',
      'Safety: iron chelation, blood thinner interaction',
      'Buyer guide: what to look for on labels',
    ],
    mdxSlug: 'curcumin',
  },
  {
    slug: 'egcg',
    category: 'compounds',
    title: 'EGCG (Green Tea Extract)',
    tagline: 'Autophagy inducer and senolytic — polyphenol powerhouse',
    summary:
      'Epigallocatechin gallate — the dominant catechin in green tea — inhibits DNMT1 for epigenetic remodeling, induces autophagy, inhibits PI3K/mTOR, and exhibits senolytic activity at therapeutic doses.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'epigenetic', 'inflammation', 'senescence', 'dysbiosis'],
    compoundId: 'egcg',
    outline: [
      'Overview & catechin spectrum',
      'Mechanism: DNMT1 inhibition + mTOR/PI3K suppression',
      'Evidence: Yang 2011 MolNutr + preclinical autophagy data',
      'Epigenetic effects: global DNA hypomethylation',
      'Dosing: 400–800 mg EGCG (decaffeinated, with food)',
      'Timing: AM, away from iron supplements',
      'Liver caution: EGCG hepatotoxicity at >800 mg/day',
      'Buyer guide: standardized catechin %',
    ],
    mdxSlug: 'egcg',
  },
  {
    slug: 'creatine',
    category: 'compounds',
    title: 'Creatine Monohydrate',
    tagline: 'ATP buffer and mitochondrial support — Tier A',
    summary:
      'Creatine phosphate system buffers ATP during high-demand periods, supports mitochondrial creatine kinase shuttle, reduces oxidative stress, and shows emerging cognitive and longevity benefits. Best-studied supplement in sports science with crossover longevity data.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'stem', 'intercell'],
    compoundId: 'creatine',
    outline: [
      'Overview & creatine phosphate system',
      'Mechanism: PCr shuttle + mitochondrial CK',
      'Evidence: Rawson 2011 meta-analysis + cognitive data',
      'Longevity crossover: muscle, bone, neuroprotection',
      'Dosing: 3–5 g/day creatine monohydrate (no loading)',
      'Who benefits most: vegetarians, >50 yo, cognitively active',
      'Monitoring: serum creatinine (expected rise)',
      'Buyer guide: creatine monohydrate vs HCl',
    ],
    mdxSlug: 'creatine',
  },
  {
    slug: 'tmg',
    category: 'compounds',
    title: 'TMG (Trimethylglycine / Betaine)',
    tagline: 'Methyl donor — homocysteine clearance and epigenetic support',
    summary:
      'Trimethylglycine donates methyl groups for homocysteine remethylation to methionine, supporting SAM pool for epigenetic maintenance. Critical co-supplement when using NMN/NR to counter methyl donor depletion.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['epigenetic', 'genomic', 'inflammation'],
    compoundId: 'tmg',
    outline: [
      'Overview & methyl donor hierarchy',
      'Mechanism: betaine-homocysteine methyltransferase (BHMT)',
      'Evidence: Olthof 2003 AJCN + Schwab 2002 metabolic data',
      'NMN/NR pairing: methyl drain and TMG as antidote',
      'Dosing: 500–1,000 mg/day TMG (with meals)',
      'Monitoring: homocysteine, SAM:SAH ratio',
      'Safety: fishy odor at high doses',
      'Buyer guide: betaine anhydrous vs betaine HCl',
    ],
    mdxSlug: 'tmg',
  },
  {
    slug: 'ashwagandha',
    category: 'compounds',
    title: 'Ashwagandha (KSM-66)',
    tagline: 'HPA axis adaptogen — cortisol and telomere protection',
    summary:
      'Withania somnifera root extract standardized to withanolides. Reduces cortisol 27% in RCTs, improves HRV, protects telomeres from stress-induced attrition, and shows anabolic effects on muscle and thyroid in multiple human trials.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['telomere', 'inflammation', 'stem', 'intercell'],
    compoundId: 'ashwagandha',
    outline: [
      'Overview & adaptogen classification',
      'Mechanism: HPA axis modulation + cortisol → DHEA ratio',
      'Evidence: Chandrasekhar 2012 JICM + Wankhede 2015 RCTs',
      'Telomere protection: stress → cortisol → telomere link',
      'Dosing: 300 mg KSM-66 × 2/day (AM + PM with food)',
      'Thyroid interaction: monitor TSH',
      'Monitoring: salivary cortisol, HRV, DHEA-S',
      'Buyer guide: KSM-66 vs Sensoril vs generic',
    ],
    mdxSlug: 'ashwagandha',
  },
  {
    slug: 'lions-mane',
    category: 'compounds',
    title: "Lion's Mane (Hericium erinaceus)",
    tagline: 'NGF inducer — neurogenesis and intercellular communication',
    summary:
      "Medicinal mushroom producing hericenones and erinacines that cross the blood-brain barrier to stimulate NGF (nerve growth factor) synthesis. Supports neurogenesis, myelination, and intercellular signaling in aging brains.",
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'stem'],
    compoundId: 'lions-mane',
    outline: [
      "Overview & hericenone/erinacine duality",
      'Mechanism: NGF induction → TrkA signaling',
      'Evidence: Mori 2009 Phytother Res RCT + animal neurogenesis',
      'Dual-extract requirement: fruiting body + mycelium',
      'Dosing: 500–1,000 mg 2× /day (standardized extract)',
      "Cognitive timeline: onset 4–8 weeks",
      'Monitoring: cognitive function tests, mood',
      'Buyer guide: beta-glucan % + erinacine testing',
    ],
    mdxSlug: 'lions-mane',
  },
  {
    slug: 'astaxanthin',
    category: 'compounds',
    title: 'Astaxanthin (AstaREAL)',
    tagline: 'Carotenoid antioxidant — mitochondrial membrane protector',
    summary:
      'Xanthophyll carotenoid spanning mitochondrial membrane bilayer to quench singlet oxygen and peroxyl radicals 6,000× more potent than vitamin C. AstaREAL is the only form with human clinical trial data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic', 'telomere'],
    compoundId: 'astaxanthin',
    outline: [
      'Overview & unique membrane-spanning structure',
      'Mechanism: singlet O2 quenching + NRF2 activation',
      'Evidence: Nir 2000 AJCN + Choi 2011 MSSE human data',
      'Why AstaREAL: only clinically validated form',
      'Dosing: 4–12 mg/day AstaREAL (with fat, AM)',
      'Synergy with CoQ10 and omega-3',
      'Monitoring: skin oxidative stress, hs-CRP',
      'Buyer guide: synthetic vs natural (haematococcus)',
    ],
    mdxSlug: 'astaxanthin',
  },
  {
    slug: 'lithium-orotate',
    category: 'compounds',
    title: 'Lithium Orotate (Low-dose)',
    tagline: 'Trace mineral neuroprotectant — GSK-3β inhibitor',
    summary:
      'At sub-prescription doses (1–5 mg elemental lithium), lithium orotate inhibits GSK-3β to promote neurogenesis, reduce tau phosphorylation, and increase gray matter volume. Epidemiological data links trace lithium in drinking water to reduced dementia mortality.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'genomic'],
    compoundId: 'lithium-orotate',
    outline: [
      'Overview & trace vs therapeutic dose distinction',
      'Mechanism: GSK-3β inhibition → tau + neurogenesis',
      'Evidence: Nunes 2013 + Fiorentini 2021 epidemiology',
      'Low-dose vs prescription lithium carbonate',
      'Dosing: 1–5 mg elemental lithium orotate (PM)',
      'Population dose benchmark: water studies',
      'Monitoring: kidney function, thyroid (at doses >10 mg)',
      'Buyer guide: orotate vs carbonate, elemental calculation',
    ],
    mdxSlug: 'lithium-orotate',
  },
  {
    slug: 'collagen',
    category: 'compounds',
    title: 'Collagen Peptides (Verisol / Peptan)',
    tagline: 'Extracellular matrix support — skin, joints, gut integrity',
    summary:
      'Hydrolyzed collagen peptides provide substrates for ECM repair and signal fibroblasts to upregulate endogenous collagen synthesis. Verisol (skin) and Peptan (joint/bone) are the clinically validated branded forms with human RCT data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['stem', 'intercell', 'inflammation'],
    compoundId: 'collagen',
    outline: [
      'Overview & ECM decline with age',
      'Mechanism: peptide absorption → fibroblast signaling',
      'Evidence: Proksch 2014 Skin Pharmacol + Bello 2006 joint RCT',
      'Verisol vs Peptan vs generic hydrolyzed',
      'Dosing: 2.5–10 g/day with vitamin C (AM, fasted)',
      'Vitamin C co-requirement for hydroxylation',
      'Monitoring: skin elasticity, joint ROM scores',
      'Buyer guide: molecular weight, amino acid profile',
    ],
    mdxSlug: 'collagen',
  },
  {
    slug: 'melatonin',
    category: 'compounds',
    title: 'Melatonin (Extended-release)',
    tagline: 'Pineal chronobiotic — mitochondrial antioxidant at physiologic dose',
    summary:
      'Pineal hormone that synchronizes circadian rhythm, drives mitochondrial antioxidant defense (UCP3, MnSOD upregulation), and declines >80% by age 70. Extended-release form prevents pharmacologic spike and morning grogginess.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'inflammation'],
    compoundId: 'melatonin',
    outline: [
      'Overview & pineal gland decline with age',
      'Mechanism: MT1/MT2 → circadian + mitochondrial UCP3/MnSOD',
      'Evidence: Reiter 2013 + Tan 2016 mitochondrial antioxidant data',
      'Physiologic (0.3 mg) vs pharmacologic (5–10 mg) debate',
      'Dosing: 0.3–1 mg extended-release (30–60 min pre-sleep)',
      'Circadian light hygiene prerequisite',
      'Monitoring: sleep quality scores, morning temperature',
      'Buyer guide: extended-release vs immediate, purity',
    ],
    mdxSlug: 'melatonin',
  },

  {
    slug: 'glycine',
    category: 'compounds',
    title: 'Glycine',
    tagline: 'Lifespan-extending amino acid — glutathione substrate and mTOR modulator',
    summary:
      'Glycine extends lifespan in mice, inhibits mTOR via GCN2, provides substrate for glutathione synthesis, deepens slow-wave sleep via CNS glycine receptors, and spares the methyl pool. The most underrated, cheapest longevity compound.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'inflammation'],
    compoundId: 'glycine',
    outline: [
      'Overview & why glycine is underrated',
      'Mechanism: GCN2 → mTOR inhibition',
      'Glutathione substrate: the GlyNAC connection',
      'Evidence: Miller 2019 lifespan extension + sleep RCT',
      'Dosing: 3–5g PM for sleep; 3g AM for glutathione',
      'Methyl donor sparing: TMG and glycine partnership',
      'Monitoring: plasma glycine, GSH, sleep scores',
      'Buyer guide: bulk powder vs capsule',
    ],
    mdxSlug: 'glycine',
  },
  {
    slug: 'glucosamine',
    category: 'compounds',
    title: 'Glucosamine Sulfate',
    tagline: 'AMPK activator — BMJ longevity cohort + autophagy induction',
    summary:
      'Glucosamine inhibits glycolysis to activate AMPK, inducing autophagy and suppressing NF-κB. A 495,000-person BMJ cohort found regular use associated with 22% lower cardiovascular mortality and 15% lower all-cause mortality.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'inflammation', 'nutrient'],
    compoundId: 'glucosamine',
    outline: [
      'Overview & mechanism beyond joint health',
      'AMPK activation: caloric restriction mimicry',
      'Evidence: Zheng 2020 BMJ cohort (n=495,000)',
      'Animal longevity: C. elegans and mouse lifespan extension',
      'Dosing: 1,500mg sulfate form (not HCl)',
      'Synergy with chondroitin for ECM support',
      'Monitoring: inflammatory markers, joint function',
      'Buyer guide: sulfate vs HCl form critical difference',
    ],
    mdxSlug: 'glucosamine',
  },
  {
    slug: 'alpha-gpc',
    category: 'compounds',
    title: 'Alpha-GPC',
    tagline: 'BBB-penetrant choline — acetylcholine, GH release, neuroprotection',
    summary:
      'Highest-bioavailability choline source crossing the blood-brain barrier to fuel acetylcholine synthesis, activate PKC neuroprotection, and stimulate growth hormone release. Strongest human cognitive data of any choline source.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'stem', 'inflammation'],
    compoundId: 'alpha-gpc',
    outline: [
      'Overview & choline form hierarchy',
      'Mechanism: BBB penetration → ACh synthesis → PKC',
      'Evidence: De Jesus Moreno 2003 Alzheimer\'s RCT + GH data',
      'Alpha-GPC vs CDP-choline vs choline bitartrate',
      'Dosing: 300–600mg AM (600mg for GH: 90 min pre-exercise)',
      'Synergy with Lion\'s Mane and Bacopa for cognitive stack',
      'Monitoring: choline biomarkers, cognitive tests',
      'Buyer guide: 50% vs 99% alpha-GPC forms',
    ],
    mdxSlug: 'alpha-gpc',
  },
  {
    slug: 'selenium',
    category: 'compounds',
    title: 'Selenium (Selenomethionine)',
    tagline: 'GPx4 / ferroptosis defense / thyroid — 25 selenoproteins',
    summary:
      'Obligate cofactor for 25 selenoproteins including GPx4 (the sole ferroptosis defense enzyme), thioredoxin reductase, and thyroid deiodinases. KiSel-10 trial: selenium + CoQ10 reduced cardiovascular mortality 54% in elderly Swedes.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'proteostasis'],
    compoundId: 'selenium',
    outline: [
      'Overview & selenium as trace element essential for longevity',
      'GPx4: the only ferroptosis defense enzyme',
      'Mechanism: UGA selenocysteine codon → 25 selenoproteins',
      'Evidence: KiSel-10 trial + Rayman 2012 Lancet review',
      'Thyroid connection: T4 → T3 via deiodinase',
      'Dosing: 100–200mcg selenomethionine (not selenite)',
      'Target plasma Se: 120–150 ng/mL',
      'Buyer guide: selenomethionine vs SeMC vs selenite',
    ],
    mdxSlug: 'selenium',
  },
  {
    slug: 'zinc',
    category: 'compounds',
    title: 'Zinc Bis-Glycinate',
    tagline: 'p53 metalloprotein / 300+ enzymes / thymic immunosenescence reversal',
    summary:
      'Zinc cofactor for 300+ enzymes, 2,000+ zinc-finger transcription factors, p53 tumor suppressor folding, and thymulin hormone for T-cell maturation. Bis-glycinate chelate is 2.8× more bioavailable than zinc oxide. Deficiency accelerates immunosenescence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'stem'],
    compoundId: 'zinc',
    outline: [
      'Overview & zinc deficiency prevalence (30–40% elderly)',
      'p53 zinc-finger: tumor suppression depends on zinc',
      'Mechanism: thymulin → T-cell maturation, SOD1 cofactor',
      'Evidence: Prasad 2007 immune + oxidative stress RCT',
      'Dosing: 15–30mg elemental zinc bis-glycinate (PM)',
      'Copper balance: 8:1 zinc:copper ratio required',
      'Monitoring: plasma zinc, RBC zinc, T-cell counts',
      'Buyer guide: elemental zinc content per form',
    ],
    mdxSlug: 'zinc',
  },
  {
    slug: 'pqq',
    category: 'compounds',
    title: 'PQQ (Pyrroloquinoline Quinone)',
    tagline: 'Mitochondrial biogenesis — only nutraceutical with PGC-1α human data',
    summary:
      'Redox cofactor activating PGC-1α and CREB to stimulate new mitochondria formation — the only nutraceutical with human data showing mitochondrial biogenesis. Also stimulates NGF and BDNF synergistically with Lion\'s Mane.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'genomic', 'intercell'],
    compoundId: 'pqq',
    outline: [
      'Overview & why PGC-1α matters for longevity',
      'Mechanism: PQQ → CREB → PGC-1α → mitochondrial biogenesis',
      'Evidence: Harris 2013 human energy/cognitive pilot RCT',
      'PQQ vs CoQ10: complementary electron carrier mechanisms',
      'NGF stimulation: synergy with Lion\'s Mane',
      'Dosing: 10–20mg with CoQ10 (AM with fat)',
      'Monitoring: mitochondrial function markers, energy',
      'Buyer guide: BioPQQ (COGAPLEX Japan standard)',
    ],
    mdxSlug: 'pqq',
  },
  {
    slug: 'ergothioneine',
    category: 'compounds',
    title: 'Ergothioneine',
    tagline: 'Dedicated TETS transporter — the "longevity vitamin" from mushrooms',
    summary:
      'Sulfur-containing amino acid with a dedicated high-affinity TETS transporter concentrating it in the most oxidatively stressed tissues. Blood ergothioneine inversely correlates with frailty and mortality. Classified as a longevity vitamin — humans cannot synthesize it.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'genomic', 'inflammation'],
    compoundId: 'ergothioneine',
    outline: [
      'Overview & TETS transporter specificity',
      'Why a dedicated transporter implies biological importance',
      'Evidence: mortality correlation + MCI blood levels study',
      'Halliwell 2018: "longevity vitamin" hypothesis',
      'Dietary sources: mushrooms (King Oyster highest)',
      'Dosing: 5–30mg/day (supplement or mushroom-based)',
      'Monitoring: plasma ergothioneine levels',
      'Buyer guide: standalone vs mushroom complex',
    ],
    mdxSlug: 'ergothioneine',
  },
  {
    slug: 'phosphatidylserine',
    category: 'compounds',
    title: 'Phosphatidylserine (PS)',
    tagline: 'Neuronal membrane phospholipid — cortisol blunting and efferocytosis',
    summary:
      'Dominant acidic phospholipid in neuronal inner membranes; blunts cortisol 20–30% in stress RCTs, maintains membrane fluidity, and signals efferocytosis of senescent cell debris. FDA allows a qualified health claim for cognitive function.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'intercell', 'inflammation'],
    compoundId: 'phosphatidylserine',
    outline: [
      'Overview & PS as neuronal architectural lipid',
      'Cortisol blunting: HPA axis modulation mechanism',
      'Efferocytosis: PS as the "eat me" signal for senescent cells',
      'Evidence: Cenacchi 1993 elderly memory RCT + FDA claim',
      'Dosing: 100–300mg PS (soy-free preferred, PM)',
      'Synergy with omega-3 for enhanced neuronal delivery',
      'Monitoring: salivary cortisol, HRV, cognitive scores',
      'Buyer guide: soy-derived vs sunflower-derived PS',
    ],
    mdxSlug: 'phosphatidylserine',
  },
  {
    slug: 'saffron',
    category: 'compounds',
    title: 'Saffron (Crocus sativus)',
    tagline: 'BDNF / MAO inhibition / neuroprotection — 30+ human RCTs',
    summary:
      'Crocins and safranal modulate monoamine neurotransmission, inhibit MAO-A/B, upregulate BDNF, and block NMDA excitotoxicity. Comparable to SSRIs for depression in meta-analysis; also protects retinal photoreceptors in AMD.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'senescence'],
    compoundId: 'saffron',
    outline: [
      'Overview: from spice to neuroprotectant',
      'Crocin mechanism: SERT inhibition + BDNF + NMDA modulation',
      'Safranal: GABAergic anxiolytic and sedative',
      'Evidence: Hausenblas 2013 meta-analysis + Falsini 2010 AMD',
      'Affron standardization (3.5% lepticrosalide) explained',
      'Dosing: 30mg standardized (AM or split AM/PM)',
      'Monitoring: mood scores, sleep quality, cognitive function',
      'Buyer guide: Affron vs generic saffron extract',
    ],
    mdxSlug: 'saffron',
  },
  {
    slug: 'boron',
    category: 'compounds',
    title: 'Boron (Boron Glycinate)',
    tagline: 'Sex hormone half-life extender — free testosterone +28%, NF-κB suppressor',
    summary:
      'Boron inhibits 24-hydroxylase to extend testosterone, estradiol, and DHEA half-lives; activates vitamin D3 conversion; potentiates magnesium; and suppresses NF-κB via IKKβ inhibition. Human RCT: 10mg/day raised free testosterone 28% in 4 weeks.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'stem', 'genomic'],
    compoundId: 'boron',
    outline: [
      'Overview & boron deficiency prevalence',
      '24-hydroxylase inhibition: sex hormone and vitamin D protection',
      'Evidence: Naghii 2011 testosterone/DHEA/hs-CRP RCT',
      'Bone mineralization: boron → collagen cross-linking',
      'Dosing: 3–10mg boron glycinate (AM with food)',
      'Synergy with vitamin D3 and zinc',
      'Monitoring: free testosterone, DHEA-S, 25-OH-D',
      'Buyer guide: glycinate vs borax vs boric acid forms',
    ],
    mdxSlug: 'boron',
  },
  {
    slug: 'liposomal-glutathione',
    category: 'compounds',
    title: 'Liposomal Glutathione (L-GSH)',
    tagline: 'Direct GSH delivery — bypasses gut degradation, complements GlyNAC',
    summary:
      'Liposomal encapsulation delivers intact reduced glutathione past gastrointestinal peptidases. First RCT showed 40% increase in whole-blood GSH and 25% in lymphocyte GSH. Complements GlyNAC for rapid GSH replenishment.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['genomic', 'proteostasis', 'inflammation'],
    compoundId: 'liposomal-glutathione',
    outline: [
      'Overview & why oral GSH normally fails',
      'Liposomal delivery mechanism: phospholipid encapsulation',
      'Evidence: Richie 2015 Eur J Nutr first human RCT',
      'GlyNAC vs liposomal GSH: upstream vs direct approach',
      'NK cell function: GSH-dependent cytotoxicity',
      'Dosing: 250–500mg liposomal GSH (AM, fasted)',
      'Monitoring: whole-blood GSH, lymphocyte GSH, 8-OHdG',
      'Buyer guide: ReadiSorb vs LipoNano vs generic',
    ],
    mdxSlug: 'liposomal-glutathione',
  },
  {
    slug: 'beta-glucan',
    category: 'compounds',
    title: 'Beta-Glucan (1,3/1,6-D)',
    tagline: 'Trained innate immunity via Dectin-1 — NK cells and gut barrier',
    summary:
      'Fungal beta-(1,3/1,6)-D-glucans bind Dectin-1 to epigenetically reprogram monocytes for trained innate immunity lasting 3–6 months. Simultaneously fermented to SCFAs for gut barrier integrity. Reduced URTI 23% in athletes.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'dysbiosis', 'intercell'],
    compoundId: 'beta-glucan',
    outline: [
      'Overview & trained innate immunity concept',
      'Dectin-1 → Syk-CARD9 → epigenetic monocyte reprogramming',
      'Evidence: Vetvicka 2019 review + Talbott URTI reduction',
      'Gut prebiotic effects: SCFA production, barrier integrity',
      'Fungal (1,3/1,6) vs oat (1,3/1,4) beta-glucan differences',
      'Dosing: 250–500mg Wellmune or equivalent (AM)',
      'Cycling: 6 weeks on, 2 weeks off',
      'Buyer guide: Wellmune vs generic, purity testing',
    ],
    mdxSlug: 'beta-glucan',
  },
  {
    slug: 'hyaluronic-acid',
    category: 'compounds',
    title: 'Hyaluronic Acid (HMW)',
    tagline: 'CD44 stem cell niche maintenance — form (>500 kDa) is everything',
    summary:
      'High-molecular-weight HA (>500 kDa) signals through CD44/RHAMM to maintain stem cell niches and suppress inflammation. Low-MW fragments trigger the opposite — inflammatory danger signaling. Oral HMW-HA confirmed in joint fluid at 2 weeks.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['stem', 'intercell', 'inflammation'],
    compoundId: 'hyaluronic-acid',
    outline: [
      'Overview & HA molecular weight paradox',
      'CD44/RHAMM → PI3K/Akt → stem cell niche signaling',
      'HMW-HA vs LMW-HA: opposite biological effects',
      'Evidence: Tashiro 2012 joint RCT + skin hydration data',
      'Oral bioavailability: endocytosis pathway confirmed',
      'Dosing: 120–240mg HMW-HA (AM with food)',
      'Monitoring: joint function scores, skin hydration',
      'Buyer guide: molecular weight specification critical',
    ],
    mdxSlug: 'hyaluronic-acid',
  },
  {
    slug: 'bacopa',
    category: 'compounds',
    title: 'Bacopa Monnieri (Synapsa)',
    tagline: 'Dendritic arborization / AChE inhibition / BDNF — cumulative onset 4–8 weeks',
    summary:
      'Bacosides inhibit AChE, stimulate dendritic sprouting via BDNF, activate 5-HT1A, and act as an adaptogen. Multiple double-blind RCTs show cumulative memory benefits. Must be taken consistently; full effect at 8–12 weeks.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'senescence'],
    compoundId: 'bacopa',
    outline: [
      'Overview & adaptogenic-nootropic dual classification',
      'Mechanism: bacoside A/B → AChE inhibition + dendritic sprouting',
      'BDNF upregulation and serotonin 5-HT1A activation',
      'Evidence: Stough 2001 memory RCT + Morgan 2010 elderly RCT',
      'Cumulative onset timeline: 4, 8, 12 weeks',
      'Dosing: 300–450mg Synapsa (45% bacosides) with fat',
      'Monitoring: cognitive function tests, anxiety scores',
      'Buyer guide: Synapsa vs generic, bacoside % standardization',
    ],
    mdxSlug: 'bacopa',
  },
  {
    slug: 'ghk-cu',
    category: 'compounds',
    title: 'GHK-Cu (Copper Peptide)',
    tagline: '4,000+ gene activation — stem cell chemo-attractant and tissue remodeler',
    summary:
      'Tripeptide-copper complex that declines with age and activates 4,000+ genes per microarray analysis — resetting gene expression toward a younger phenotype. Recruits stem cells and macrophages for tissue repair. Beyond topical use: systemic biology at 1–3mg.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['stem', 'intercell', 'genomic'],
    compoundId: 'ghk-cu',
    outline: [
      'Overview & GHK-Cu age-related decline',
      'Gene activation: 4,000 genes — anti-aging vs pro-aging',
      'Stem cell recruitment: chemo-attractant mechanism',
      'Evidence: Pickart 2015 microarray + wound healing data',
      'Topical vs oral: systemic effects of oral GHK-Cu',
      'Dosing: 1–3mg oral (AM) or topical as directed',
      'Copper balance: monitor serum copper at therapeutic doses',
      'Buyer guide: authentic GHK-Cu vs imitations',
    ],
    mdxSlug: 'ghk-cu',
  },
  {
    slug: 'carnosine',
    category: 'compounds',
    title: 'L-Carnosine',
    tagline: 'Anti-glycation dipeptide — AGE inhibitor and pH buffer',
    summary:
      'Beta-alanyl-L-histidine quenches reactive carbonyl species to prevent AGE formation, chelates pro-oxidant metals, buffers intramuscular pH, and reduces HbA1c in T2D RCTs. Rejuvenates senescent cells in culture by extending cellular lifespan.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'inflammation', 'genomic'],
    compoundId: 'carnosine',
    outline: [
      'Overview & AGE formation in aging tissues',
      'Mechanism: carbonyl quenching → AGE prevention',
      'Metal chelation: Cu2+ and Zn2+ catalysis prevention',
      'Evidence: Boldyrev 2013 Physiol Rev + HbA1c RCT data',
      'Cell culture: carnosine extends cellular lifespan',
      'Dosing: 500–1,000mg (AM, away from carnosinase-rich foods)',
      'Carnosinase issue: why meat eaters may need more',
      'Monitoring: HbA1c, oxidized LDL, skin AGE proxy',
    ],
    mdxSlug: 'carnosine',
  },
  {
    slug: 'nicotinamide',
    category: 'compounds',
    title: 'Nicotinamide (Niacinamide)',
    tagline: 'NAD+ salvage / skin cancer prevention 23% — ONTRAC NEJM trial',
    summary:
      'Amide form of B3 entering the NAD+ salvage pathway without flushing. ONTRAC (NEJM 2015): 500mg twice daily reduced non-melanoma skin cancers 23% via keratinocyte DNA repair. Critical dose ceiling: >1g/day inhibits SIRT1.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'senescence', 'inflammation'],
    compoundId: 'nicotinamide',
    outline: [
      'Overview & B3 family: niacin vs nicotinamide vs NMN vs NR',
      'NAMPT pathway: same entry as NR, different distribution',
      'ONTRAC trial: 500mg × 2/day, NEJM 2015 (n=386)',
      'Skin cancer: UV → NAD+ depletion → unrepaired DNA',
      'SIRT1 dose ceiling: >1g/day inhibits sirtuin activity',
      'Dosing: 500mg AM + 500mg PM (strict ceiling at 1g/day)',
      'Monitoring: liver enzymes at higher doses',
      'Buyer guide: niacinamide vs niacin, flush warning',
    ],
    mdxSlug: 'nicotinamide',
  },
  {
    slug: '5-ala',
    category: 'compounds',
    title: '5-Aminolevulinic Acid (5-ALA)',
    tagline: 'Mitochondrial Complex IV precursor — targets the ETC step no other compound reaches',
    summary:
      '5-ALA is the universal heme precursor that enhances mitochondrial Complex IV (cytochrome c oxidase) activity — the terminal, rate-limiting ETC step. With sodium ferrous citrate, significantly reduces HbA1c in T2D RCTs. Fills the Complex IV gap in every mito stack.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'nutrient', 'genomic'],
    compoundId: '5-ala',
    outline: [
      'Overview & the ETC gap: why Complex IV matters',
      'Mechanism: 5-ALA → porphyrin → heme → cytochrome c oxidase',
      'Why combine with sodium ferrous citrate (SFC)',
      'Evidence: Okamoto 2014 Diabetes Obes Metab RCT',
      'Where 5-ALA fits: NMN targets I-III, 5-ALA targets IV',
      'Dosing: 15–50mg 5-ALA + 48mg SFC (AM before breakfast)',
      'Monitoring: HbA1c, fasting glucose, VO2max proxy',
      'Buyer guide: NEOAGE vs Japanese pharmaceutical grade',
    ],
    mdxSlug: '5-ala',
  },
  {
    slug: 'rhodiola',
    category: 'compounds',
    title: 'Rhodiola Rosea',
    tagline: 'FOXO3a activator / AMPK / MAO-B — the longevity adaptogen',
    summary:
      'Rosavins + salidroside activate AMPK, inhibit MAO-B, and uniquely activate FOXO3a — one of the most replicated longevity transcription factors in centenarian genetics. Tier A human anti-fatigue data. The only adaptogen with a longevity gene mechanism.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'inflammation', 'intercell'],
    compoundId: 'rhodiola',
    outline: [
      'Overview & the adaptogen-longevity distinction',
      'Salidroside → FOXO3a: centenarian genetic link',
      'Rosavin → MAO-B inhibition: monoamine protection',
      'AMPK activation: mTOR suppression + autophagy',
      'Evidence: Darbinyan 2000 + Shevtsov 2003 double-blind RCTs',
      'Dosing: 200–400mg SHR-5 standardized (AM, before food)',
      'Timing: AM only — can be stimulating (delays sleep)',
      'Buyer guide: SHR-5, Rhodiolife, 3% rosavins minimum',
    ],
    mdxSlug: 'rhodiola',
  },
  {
    slug: 'honokiol',
    category: 'compounds',
    title: 'Honokiol',
    tagline: 'SIRT3 activator / BBB-penetrant senolytic — bridges mito and senolytic stacks',
    summary:
      'Lipophilic neolignan from magnolia bark with exceptional BBB penetrance. Directly activates SIRT3 (the mitochondrial sirtuin), acts as a senolytic via p21-selective apoptosis, and inhibits mTORC1 independent of AMPK. Uniquely bridges the mitochondrial and senolytic stacks.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'senescence', 'epigenetic'],
    compoundId: 'honokiol',
    outline: [
      'Overview & magnolia bark vs honokiol extract',
      'SIRT3 activation: mitochondrial deacetylation (IDH2, SOD2)',
      'Senolytic mechanism: p21-high cell selective apoptosis',
      'Evidence: Pillai 2015 Aging Cell lifespan data + Farooqi 2019',
      'BBB penetrance: why this matters for neurological aging',
      'Dosing: 100–250mg standardized honokiol (PM with fat)',
      'Synergy: NMN fuels NAD+ → SIRT3, honokiol activates SIRT3',
      'Buyer guide: standardized magnolia extract vs generic',
    ],
    mdxSlug: 'honokiol',
  },
  {
    slug: 'shilajit',
    category: 'compounds',
    title: 'Shilajit (PrimaVie)',
    tagline: 'Fulvic acid electron carrier — CoQ10 synergy +29%, testosterone, VO2max',
    summary:
      'Humic-fulvic acid complex with dibenzo-alpha-pyrones acting as mitochondrial electron carriers. PrimaVie RCT: 29% increase in plasma CoQ10 when co-administered, improved VO2max, and raised testosterone levels. Only PrimaVie has human data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'stem', 'inflammation'],
    compoundId: 'shilajit',
    outline: [
      'Overview & Himalayan humic-fulvic complex',
      'Dibenzo-alpha-pyrones (DBPs): CoQ10 mimetic mechanism',
      'Fulvic acid: electron carrier + trace mineral delivery',
      'Evidence: Surapaneni 2012 CoQ10 synergy + Bhardwaj 2016 testosterone RCT',
      'PrimaVie standardization: why generic shilajit fails',
      'Dosing: 250–500mg PrimaVie (AM with CoQ10)',
      'CoQ10 synergy: stack design and timing',
      'Buyer guide: PrimaVie certificate, heavy metal testing critical',
    ],
    mdxSlug: 'shilajit',
  },

  // ── Synergies ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac-nrf2-triad',
    category: 'synergies',
    title: 'NRF2 Defense Triad',
    tagline: 'GlyNAC + Sulforaphane + R-ALA',
    summary:
      'The foundational TNiC NRF2 stack: glutathione substrate (GlyNAC), gene transcription (sulforaphane), and redox recycling (R-ALA) — three layers of antioxidant defense.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'proteostasis', 'inflammation'],
    synergyCompoundIds: ['glynac', 'sulforaphane', 'rala'],
    outline: [
      'Rationale: substrate + signal + recycle',
      'Mechanistic synergy map',
      'Evidence per compound + combination logic',
      'AM choreography & spacing',
      'Biomarker targets (GSH, oxLDL)',
      'Contraindications',
    ],
    mdxSlug: 'glynac-nrf2-triad',
  },
  {
    slug: 'nmn-resveratrol-sirt1',
    category: 'synergies',
    title: 'SIRT1 Activation Pair',
    tagline: 'NMN + Trans-Resveratrol',
    summary:
      'NAD+ provides the fuel; resveratrol activates the enzyme. Combined SIRT1 signaling drives mitochondrial biogenesis, epigenetic stability, and senescence resistance.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'senescence', 'nutrient'],
    synergyCompoundIds: ['nmn', 'resveratrol'],
    outline: [
      'Rationale: cofactor + activator',
      'SIRT1 mechanism deep-dive',
      'Trial data & PK considerations',
      'AM NMN / PM resveratrol timing',
      'Monitoring: NAD+ index',
      'When to skip resveratrol',
    ],
    mdxSlug: 'nmn-resveratrol-sirt1',
  },
  {
    slug: 'nad-mito-stack',
    category: 'synergies',
    title: 'NAD+ Mitochondrial Stack',
    tagline: 'NMN + Ca-AKG + Resveratrol',
    summary:
      'Triple-axis mitochondrial support: NAD+ restoration (NMN), TCA cycle & epigenetic cofactor (Ca-AKG), and sirtuin-driven biogenesis (resveratrol). Highest hallmark coverage combo.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'epigenetic', 'stem', 'genomic'],
    synergyCompoundIds: ['nmn', 'cakg', 'resveratrol'],
    outline: [
      'Rationale: energy + epigenetics + biogenesis',
      'Hallmark coverage matrix',
      'Evidence per leg',
      'Full-day dosing schedule',
      'Biomarker panel (NAD+, AKG)',
      'Cost & simplicity tiers',
    ],
    mdxSlug: 'nad-mito-stack',
  },

  // ── Lifestyle ──────────────────────────────────────────────────────────────
  {
    slug: 'exercise',
    category: 'lifestyle',
    title: 'Exercise',
    tagline: 'The intervention no compound can replace',
    summary:
      'Zone 2 aerobic base, resistance training, and VO2max work — mapped to mitochondrial biogenesis, senescence clearance, telomere maintenance, and nutrient sensing.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'senescence', 'telomeres', 'nutrient', 'inflammation', 'stem'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — sedentary vs trained vs deload',
      'Zone 2 vs HIIT vs resistance pyramid',
      'Weekly protocol template',
      'Lab tie-ins (hs-CRP, NAD+ index)',
      'Wearable signals (Zone 2, RHR, HRV)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'exercise',
  },
  {
    slug: 'sleep',
    category: 'lifestyle',
    title: 'Sleep',
    tagline: 'When repair happens — glymphatic, DNA, hormonal',
    summary:
      '7–9 hours with adequate slow-wave and REM sleep drives DNA repair, glymphatic clearance, growth hormone release, and cortisol normalization. Non-negotiable longevity pillar.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'proteostasis', 'inflammation', 'telomeres', 'communication'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — debt vs OSA vs stack timing',
      'Sleep architecture & repair windows',
      'Protocol: timing, light, temperature',
      'Lab tie-ins (hs-CRP, 8-OHdG)',
      'Wearable metrics (deep sleep, wake SD)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'sleep',
  },
  {
    slug: 'nutrition',
    category: 'lifestyle',
    title: 'Nutrition',
    tagline: 'Methyl donors, protein thresholds, and nutrient sensing',
    summary:
      'Protein adequacy for glycine/NAC synthesis, methyl donor support (B12, folate, choline), time-restricted eating, and low-glycemic patterns that modulate mTOR/AMPK.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'epigenetic', 'dysbiosis', 'inflammation', 'autophagy'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — TRE readiness vs methyl donors',
      'Macro framework (protein, fiber, polyphenols)',
      'Methyl donor checklist',
      'Lab tie-ins (hs-CRP, AKG)',
      'Wearable proxies (fiber, eating window)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'nutrition',
  },
  {
    slug: 'stress',
    category: 'lifestyle',
    title: 'Stress & Recovery',
    tagline: 'Cortisol, HPA axis, and inflammaging acceleration',
    summary:
      'Chronic stress accelerates telomere attrition, elevates hs-CRP, impairs sleep architecture, and diverts resources from repair to survival signaling.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['telomeres', 'inflammation', 'communication', 'genomic', 'senescence'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — acute stress vs HRV collapse',
      'HPA axis & cortisol curve',
      'HRV training & breathwork protocols',
      'Lab tie-ins (hs-CRP, GSH)',
      'Wearable signals (HRV, stress score)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'stress',
  },

  // ── Guides ──────────────────────────────────────────────────────────────
  {
    slug: 'testing-and-monitoring',
    category: 'guides',
    title: 'Testing & Monitoring Guide',
    tagline: 'What to test, when, and how to interpret',
    summary:
      'Comprehensive lab panel roadmap tied to TNiC biomarkers, hallmark risks, retest cadence, trend interpretation, and stack-adjustment triggers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'inflammation', 'epigenetic', 'proteostasis'],
    outline: [
      'Tier 1 baseline panel',
      'Tier 2 advanced panel',
      'Retest cadence & decision tree',
      'Interpretation playbook & compare block',
      'Stack-adjustment triggers + compare links',
      'Lab day checklist & CSV upload',
      'Hallmark → biomarker reference',
    ],
    mdxSlug: 'testing-and-monitoring',
  },
];

export function getModuleBySlug(category: LibraryModuleCategory, slug: string): LibraryModule | undefined {
  return libraryModules.find((m) => m.category === category && m.slug === slug);
}

export function getModulesByCategory(category: LibraryModuleCategory): LibraryModule[] {
  return libraryModules.filter((m) => m.category === category);
}

export function getAllModuleParams(): { slug: LibraryModuleCategory; moduleSlug: string }[] {
  return libraryModules.map((m) => ({ slug: m.category, moduleSlug: m.slug }));
}

export function getModulePath(module: LibraryModule): string {
  return `/library/${module.category}/${module.slug}`;
}