import type { EvidenceTier } from './types';

export type LibraryModuleCategory = 'compounds' | 'synergies' | 'lifestyle' | 'guides';

export interface LibraryModule {
  slug: string;
  category: LibraryModuleCategory;
  title: string;
  tagline: string;
  summary: string;
  evidenceTier: EvidenceTier;
  relatedHallmarkIds: string[];
  compoundId?: string;
  synergyCompoundIds?: string[];
  relatedSynergySlugs?: string[];
  requiresDisclaimer?: boolean;
  outline: string[];
  mdxSlug: string;
}

export const libraryCategoryMeta: Record<
  LibraryModuleCategory,
  { label: string; description: string; hubOrder: number }
> = {
  compounds: {
    label: 'Compound Deep-Dives',
    description:
      'Mechanism, evidence tiers, dosing protocols, monitoring checklists, and personal results templates for each intervention.',
    hubOrder: 1,
  },
  synergies: {
    label: 'Synergy Guides',
    description:
      'Multi-compound combinations with mechanistic rationale, trial data, timing choreography, and contraindication notes.',
    hubOrder: 2,
  },
  lifestyle: {
    label: 'Lifestyle Pillars',
    description:
      'Exercise, sleep, nutrition, and stress — mapped to hallmarks with actionable protocols and biomarker tie-ins.',
    hubOrder: 3,
  },
  guides: {
    label: 'Testing & Monitoring',
    description:
      'What to test, when to retest, how to interpret trends, and how lab data connects to your stack.',
    hubOrder: 4,
  },
};

export const libraryModules: LibraryModule[] = [
  // ── Compounds ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac',
    category: 'compounds',
    title: 'GlyNAC (Glycine + NAC)',
    tagline: 'Flagship glutathione restoration — human RCT backbone',
    summary:
      'Dual-precursor strategy rebuilding the glutathione triad (GSH, cysteine, glycine). Tier A human data for oxidative stress, mitochondrial function, and inflammaging markers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation', 'genomic'],
    compoundId: 'glynac',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & hallmark mapping',
      'Mechanism: GSH synthesis bottleneck',
      'Evidence summary (Kumar et al. RCTs)',
      'Dosing protocol (AM/PM, cycling)',
      'Monitoring: GSH, 8-OHdG, hs-CRP',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'glynac',
  },
  {
    slug: 'nmn',
    category: 'compounds',
    title: 'NMN (Nicotinamide Mononucleotide)',
    tagline: 'NAD+ precursor — sirtuin and PARP fuel',
    summary:
      'Direct NAD+ precursor bypassing NAMPT rate-limiting step. Restores NAD+ pools that decline ~50% between ages 40–60, activating SIRT1/3, DNA repair, and mitophagy.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    compoundId: 'nmn',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & NAD+ decline curve',
      'Mechanism: NMN → NAD+ → SIRT/PARP axis',
      'Evidence summary (human PK + biomarkers)',
      'Dosing protocol & resveratrol pairing',
      'Monitoring: NAD+ index, metabolic markers',
      'Safety & methyl donor considerations',
      'Personal results template',
    ],
    mdxSlug: 'nmn',
  },
  {
    slug: 'nr',
    category: 'compounds',
    title: 'NR (Nicotinamide Riboside)',
    tagline: 'NAD+ precursor alternative — human RCT data, manual stack substitution',
    summary:
      'Legitimate NAD+ precursor with human trial footprint. TNiC defaults to NMN for stack integration; this module covers when NR is the right choice, dosing, buyer verification, and compare-table evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    relatedSynergySlugs: ['nad-mito-stack', 'nmn-resveratrol-sirt1'],
    outline: [
      'Overview & NR → NMN → NAD+ pathway',
      'When to choose NR vs NMN',
      'Evidence summary (Martens, Trammell)',
      'Dosing & NR-Cl form requirements',
      'TNiC stack substitution guide',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'nr',
  },
  {
    slug: 'rapamycin',
    category: 'compounds',
    title: 'Rapamycin (Sirolimus)',
    tagline: 'mTORC1 inhibition — strongest preclinical lifespan drug',
    summary:
      'Educational deep-dive on the most replicated lifespan-extending pharmacological intervention. Prescription-only; immunosuppressive risks require physician oversight.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'nutrient', 'senescence', 'mito'],
    requiresDisclaimer: true,
    relatedSynergySlugs: [],
    outline: [
      'Overview & mTOR/AMPK balance',
      'Mechanism: mTORC1 → autophagy induction',
      'Evidence: mouse, dog, PEARL trial',
      'Decision tree & physician checklist',
      'Dosing paradigms (pulse vs continuous)',
      'Monitoring: CBC, lipids, infection vigilance',
      'Buyer/sourcing guide (Rx only)',
      'Personal results template (physician-supervised)',
    ],
    mdxSlug: 'rapamycin',
  },
  {
    slug: 'tudca',
    category: 'compounds',
    title: 'TUDCA (Tauroursodeoxycholic Acid)',
    tagline: 'ER stress chaperone — proteostasis & mitochondrial support',
    summary:
      'Bile acid derivative stabilizing protein folding, reducing ER stress, and supporting mitochondrial membrane integrity. Strong preclinical data; emerging human hepatoprotection studies.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'mito', 'autophagy'],
    relatedSynergySlugs: [],
    outline: [
      'Overview & proteostasis link',
      'Mechanism: UPR modulation & chaperone activity',
      'Evidence summary (preclinical + pilot human)',
      'Decision tree & stack placement',
      'Dosing protocol & compliance checklist',
      'Monitoring: liver panel, GGT',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'tudca',
  },
  {
    slug: 'sulforaphane',
    category: 'compounds',
    title: 'Sulforaphane',
    tagline: 'NRF2 master regulator — 200+ cytoprotective genes',
    summary:
      'Isothiocyanate from broccoli sprouts that covalently modifies KEAP1, releasing NRF2 to drive phase-II detox, proteasome upregulation, and anti-inflammatory gene expression.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'proteostasis'],
    compoundId: 'sulforaphane',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & NRF2 pathway',
      'Mechanism: KEAP1 modification',
      'Evidence summary',
      'Dosing & myrosinase activation',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'sulforaphane',
  },
  {
    slug: 'rala',
    category: 'compounds',
    title: 'R-Alpha Lipoic Acid (R-ALA)',
    tagline: 'Mitochondrial redox recycler — NRF2 stack completion',
    summary:
      'Recycles oxidized glutathione, vitamins C and E. Cofactor for pyruvate dehydrogenase in mitochondria. Completes the NRF2 Defense Triad (substrate → signal → recycle). Tier B in healthy adults; strong mechanistic and metabolic syndrome data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation'],
    compoundId: 'rala',
    relatedSynergySlugs: ['glynac-nrf2-triad', 'nad-mito-stack'],
    outline: [
      'Overview & NRF2 triad placement',
      'Mechanism: redox recycling hub',
      'Evidence summary (neuropathy, metabolic data)',
      'Dosing protocol & enantiomer note',
      'NRF2 Defense Triad choreography',
      'Monitoring: GSH, 8-OHdG, glucose',
      'Safety & interactions',
      'Personal results template',
    ],
    mdxSlug: 'rala',
  },
  {
    slug: 'cakg',
    category: 'compounds',
    title: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    tagline: 'Epigenetic cofactor & TCA fuel — highest hallmark breadth per gram',
    summary:
      'TCA cycle intermediate and obligate cofactor for TET, JMJ, and PHD enzymes that reverse age-related DNA and histone methylation drift. Mouse lifespan +12%; emerging human metabolic and clock data from 2024.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['epigenetic', 'mito', 'stem'],
    compoundId: 'cakg',
    relatedSynergySlugs: ['nad-mito-stack'],
    outline: [
      'Overview & AKG decline curve',
      'Mechanism: TCA anaplerosis + TET/JMJ cofactor',
      'Evidence summary (mouse lifespan + human 2024)',
      'Dosing protocol & titration',
      'NAD+ Mito Stack ramp-in schedule',
      'Monitoring: glucose, hs-CRP, epigenetic clock',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'cakg',
  },
  {
    slug: 'resveratrol',
    category: 'compounds',
    title: 'Trans-Resveratrol',
    tagline: 'SIRT1 activator — caloric restriction mimetic',
    summary:
      'Phytoalexin activating SIRT1 and AMPK. Synergistic with NAD+ precursors for epigenetic and mitochondrial remodeling. Tier B — strong mechanism, mixed human outcomes.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation', 'senescence'],
    compoundId: 'resveratrol',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & SIRT1 axis',
      'Mechanism & bioavailability',
      'Evidence summary',
      'Dosing & NMN pairing (PM timing)',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'resveratrol',
  },
  {
    slug: 'taurine',
    category: 'compounds',
    title: 'Taurine',
    tagline: 'Age-depleted osmolyte — Science 2023 lifespan signals',
    summary:
      'Sulfonic amino acid buffering mitochondrial stress and declining ~80% with age. Tier B: strong Singh 2023 Science mechanism and animal lifespan data; limited human longevity RCT.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic'],
    compoundId: 'taurine',
    outline: [
      'Overview & taurine decline with age',
      'Mechanism: membrane + mitochondrial buffering',
      'Evidence: Singh 2023 Science',
      'Dosing protocol',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'taurine',
  },
  {
    slug: 'spermidine',
    category: 'compounds',
    title: 'Spermidine',
    tagline: 'Autophagy polyamine — Madeo 2021 memory RCT',
    summary:
      'Dietary and supplemental polyamine inducing autophagy via EP300 inhibition. Tier B: human pilot memory outcomes; strong mechanistic autophagy data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'epigenetic', 'senescence'],
    compoundId: 'spermidine',
    outline: [
      'Overview & autophagy induction',
      'Mechanism: EP300 / eIF5A',
      'Evidence: Madeo 2021 Cell RCT',
      'Dosing & dietary sources',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'spermidine',
  },
  {
    slug: 'pterostilbene',
    category: 'compounds',
    title: 'Pterostilbene',
    tagline: 'Methylated resveratrol — 4× bioavailability',
    summary:
      'Stilbenoid SIRT1 activator with superior human PK vs trans-resveratrol. Tier B: Kapetanovic 2011 safety/PK; compare with resveratrol for stack pairing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation'],
    compoundId: 'pterostilbene',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1'],
    outline: [
      'Overview vs resveratrol',
      'Mechanism & bioavailability advantage',
      'Evidence summary',
      'Dosing & NMN pairing',
      'Compare table link',
      'Personal results template',
    ],
    mdxSlug: 'pterostilbene',
  },
  {
    slug: 'nr',
    category: 'compounds',
    title: 'NR (Nicotinamide Riboside)',
    tagline: 'NAD+ precursor alternative — human RCT backbone',
    summary:
      'Orally bioavailable NAD+ precursor with a well-established human trial footprint. Elevates whole-blood NAD+ within days; competes with NMN on cost and is superior for some tissue distributions. Tier A evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    compoundId: 'nr',
    relatedSynergySlugs: ['nad-mito-stack', 'nmn-resveratrol-sirt1'],
    outline: [
      'Overview & NR → NMN → NAD+ pathway',
      'Mechanism: CD73 conversion & tissue distribution',
      'Evidence: Martens 2018, Trammell 2016 RCTs',
      'NR vs NMN decision tree',
      'Dosing protocol (AM, with fat)',
      'Monitoring: NAD+ index, hs-CRP',
      'Buyer guide & NR-Cl form requirements',
      'Personal results template',
    ],
    mdxSlug: 'nr',
  },
  {
    slug: 'urolithin-a',
    category: 'compounds',
    title: 'Urolithin A (Mitopure)',
    tagline: 'Mitophagy activator — Amazentis Phase 2 muscle data',
    summary:
      'Gut-derived polyphenol metabolite that selectively induces mitophagy via PINK1/Parkin pathway. Phase 2 RCT showed significant improvement in muscle strength and endurance in older adults.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'autophagy', 'senescence', 'stem'],
    compoundId: 'urolithin-a',
    outline: [
      'Overview & gut microbiome conversion',
      'Mechanism: PINK1/Parkin mitophagy axis',
      'Evidence: Amazentis Nat Med 2016 + JAMA 2022 RCT',
      'Who cannot convert: urolithin producer status',
      'Dosing protocol (500–1000 mg AM)',
      'Monitoring: muscle function, mitochondrial markers',
      'Buyer guide: Mitopure vs generic UA',
      'Personal results template',
    ],
    mdxSlug: 'urolithin-a',
  },
  {
    slug: 'quercetin',
    category: 'compounds',
    title: 'Quercetin',
    tagline: 'Flavonoid senolytic — dasatinib partner in human pilot',
    summary:
      'Broad-spectrum flavonoid with senolytic activity at high doses (dasatinib + quercetin protocol) and anti-inflammatory NRF2 effects at daily doses. First human senolytic trial published in EBioMedicine 2019.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'inflammation', 'autophagy'],
    compoundId: 'quercetin',
    outline: [
      'Overview & senolytic vs daily dosing modes',
      'Mechanism: Bcl-2 inhibition + NRF2 activation',
      'Evidence: Kirkland EBioMedicine 2019, Mayo pilot',
      'D+Q protocol vs daily quercetin phytosome',
      'Dosing: pulse 1,000 mg × 3 days vs 500 mg/day',
      'Monitoring: p16, SA-β-gal proxies, hs-CRP',
      'Safety: drug interactions (warfarin, antibiotics)',
      'Personal results template',
    ],
    mdxSlug: 'quercetin',
  },
  {
    slug: 'fisetin',
    category: 'compounds',
    title: 'Fisetin',
    tagline: 'Potent flavonoid senolytic — Mayo Clinic preclinical lead',
    summary:
      'Flavonol with the strongest senolytic potency among tested polyphenols in Mayo Clinic screening. Clears senescent cells via apoptosis induction; improves healthspan in aging mouse models. Human pilot data emerging.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'inflammation', 'genomic'],
    compoundId: 'fisetin',
    outline: [
      'Overview & senolytic ranking vs quercetin',
      'Mechanism: Bcl-2/Bcl-xL inhibition, SIRT1 activation',
      'Evidence: Yousefzadeh 2018 EBioMedicine + mouse lifespan',
      'Pulse dosing protocol (20 mg/kg equivalent)',
      'Bioavailability: liposomal form advantage',
      'Monitoring: inflammatory markers, skin markers',
      'Safety & drug interaction notes',
      'Personal results template',
    ],
    mdxSlug: 'fisetin',
  },
  {
    slug: 'apigenin',
    category: 'compounds',
    title: 'Apigenin',
    tagline: 'CD38 inhibitor — NAD+ salvage pathway support',
    summary:
      'Flavone from parsley and chamomile that inhibits CD38 ectoenzyme — the dominant consumer of cellular NAD+. Synergizes with NMN/NR by reducing NAD+ degradation, not just increasing synthesis.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'senescence'],
    compoundId: 'apigenin',
    outline: [
      'Overview & CD38 as NAD+ drain',
      'Mechanism: CD38 inhibition → NAD+ sparing',
      'Evidence: Escande 2013 Chemistry & Biology, Chini 2020',
      'Synergy with NMN/NR (complementary mechanisms)',
      'Dosing protocol (50–100 mg with fat)',
      'Monitoring: NAD+ index, inflammatory markers',
      'Buyer guide: apigenin vs luteolin',
      'Personal results template',
    ],
    mdxSlug: 'apigenin',
  },
  {
    slug: 'omega3',
    category: 'compounds',
    title: 'Omega-3 (EPA + DHA)',
    tagline: 'Tier A anti-inflammatory — telomere and cardiovascular anchor',
    summary:
      'Long-chain polyunsaturated fatty acids EPA and DHA resolve chronic inflammation via SPM pathways, protect telomere length, support mitochondrial membrane integrity, and reduce cardiovascular events in large RCTs.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['inflammation', 'telomere', 'mito', 'genomic', 'stem'],
    compoundId: 'omega3',
    outline: [
      'Overview & SPM resolution pathway',
      'Mechanism: EPA/DHA → SPM → NF-κB suppression',
      'Evidence: REDUCE-IT (NEJM 2019), omega-3 index data',
      'Telomere protection: Farzaneh-Far 2010 JAMA',
      'Dosing: 2–4 g/day EPA+DHA (triglyceride form)',
      'Omega-3 index target (>8%)',
      'Buyer guide: triglyceride vs ethyl ester, IFOS testing',
      'Personal results template',
    ],
    mdxSlug: 'omega3',
  },
  {
    slug: 'coq10',
    category: 'compounds',
    title: 'CoQ10 (Ubiquinol)',
    tagline: 'Mitochondrial electron transport essential — Tier A',
    summary:
      'Fat-soluble quinone essential for Complex I–III electron transfer in the mitochondrial ETC. Plasma CoQ10 declines ~50% between ages 20–80. Ubiquinol (reduced form) has 3–8× superior absorption vs ubiquinone.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'inflammation'],
    compoundId: 'coq10',
    outline: [
      'Overview & ETC placement (Complex I-III)',
      'Mechanism: electron carrier + membrane antioxidant',
      'Evidence: SHIELD trial (HF), statin depletion data',
      'Ubiquinol vs ubiquinone bioavailability comparison',
      'Dosing: 100–300 mg/day with fat (PM preferred)',
      'Who needs it most: statin users, >50 yo',
      'Monitoring: plasma CoQ10 levels',
      'Buyer guide & softgel form requirements',
    ],
    mdxSlug: 'coq10',
  },
  {
    slug: 'magnesium',
    category: 'compounds',
    title: 'Magnesium L-Threonate',
    tagline: 'Cofactor for 300+ enzymes — brain-penetrant form',
    summary:
      'Magnesium participates in ATP synthesis, DNA repair, and 300+ enzymatic reactions. L-Threonate form crosses the blood-brain barrier; clinical trial showed cognitive improvement. >50% of adults are deficient.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['genomic', 'inflammation', 'mito'],
    compoundId: 'magnesium',
    outline: [
      'Overview & magnesium deficiency epidemic',
      'Mechanism: ATP cofactor, DNA repair, Ca2+ antagonism',
      'Evidence: Slutsky 2010 Neuron, TACT-2 cardiac data',
      'L-Threonate vs glycinate vs malate forms',
      'Dosing: 144 mg elemental Mg L-threonate (PM)',
      'Monitoring: RBC magnesium (not serum)',
      'Buyer guide: elemental magnesium content per form',
      'Personal results template',
    ],
    mdxSlug: 'magnesium',
  },
  {
    slug: 'vitamin-d3',
    category: 'compounds',
    title: 'Vitamin D3 + K2',
    tagline: 'Genomic hormone — Tier A immune, bone, and longevity data',
    summary:
      'Vitamin D3 is a genomic hormone regulating 200+ gene targets including immune modulation, telomere maintenance, and calcium metabolism. K2 (MK-7) directs calcium to bone and away from arteries. Tier A evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'telomere', 'senescence', 'stem'],
    compoundId: 'vitamin-d3',
    outline: [
      'Overview & vitamin D as genomic hormone',
      'Mechanism: VDR activation → 200+ gene targets',
      'Evidence: VITAL trial (NEJM 2019), Pludowski meta-analysis',
      'K2 synergy: carboxylation of MGP and osteocalcin',
      'Dosing: 2,000–5,000 IU D3 + 100–200 mcg MK-7',
      'Target 25-OH-D: 40–60 ng/mL',
      'Monitoring: 25-OH-D, calcium, PTH',
      'Buyer guide: D3 vs D2, oil-based capsules',
    ],
    mdxSlug: 'vitamin-d3',
  },
  {
    slug: 'berberine',
    category: 'compounds',
    title: 'Berberine',
    tagline: 'AMPK activator — metformin-class metabolic intervention',
    summary:
      'Isoquinoline alkaloid from Berberis plants that activates AMPK (like metformin), inhibits mTOR, improves insulin sensitivity, and modulates the gut microbiome. Strong RCT data for glucose, lipids, and metabolic health.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'inflammation', 'dysbiosis', 'senescence'],
    compoundId: 'berberine',
    outline: [
      'Overview & AMPK mimicry of metformin',
      'Mechanism: AMPK activation + mTOR inhibition + gut flora',
      'Evidence: Yin 2008 Metabolism RCT, Zhang 2010 lipid data',
      'Berberine vs metformin comparison',
      'Dosing: 500 mg × 3/day with meals (cycling)',
      'Gut effects: Akkermansia upregulation',
      'Monitoring: fasting glucose, HbA1c, lipids',
      'Buyer guide: DHB vs berberine HCl bioavailability',
    ],
    mdxSlug: 'berberine',
  },
  {
    slug: 'curcumin',
    category: 'compounds',
    title: 'Curcumin (Theracurmin / Longvida)',
    tagline: 'NF-κB and NRF2 modulator — bioavailability-critical',
    summary:
      'Polyphenol from turmeric with potent NF-κB inhibition and NRF2 activation. Standard curcumin has <1% oral bioavailability; Theracurmin and Longvida formulations achieve 27–185× improvement. Strong anti-inflammatory RCT data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'proteostasis', 'autophagy', 'genomic'],
    compoundId: 'curcumin',
    outline: [
      'Overview & NF-κB/NRF2 dual action',
      'Mechanism: IKKβ inhibition + KEAP1 modification',
      'Evidence: Lopresti 2018 JACI + Rainey-Smith 2017 RCTs',
      'Bioavailability crisis: standard vs Theracurmin vs Longvida',
      'Dosing: 400 mg Theracurmin or 400 mg Longvida daily',
      'Monitoring: hs-CRP, IL-6, cognitive markers',
      'Safety: iron chelation, blood thinner interaction',
      'Buyer guide: what to look for on labels',
    ],
    mdxSlug: 'curcumin',
  },
  {
    slug: 'egcg',
    category: 'compounds',
    title: 'EGCG (Green Tea Extract)',
    tagline: 'Autophagy inducer and senolytic — polyphenol powerhouse',
    summary:
      'Epigallocatechin gallate — the dominant catechin in green tea — inhibits DNMT1 for epigenetic remodeling, induces autophagy, inhibits PI3K/mTOR, and exhibits senolytic activity at therapeutic doses.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'epigenetic', 'inflammation', 'senescence', 'dysbiosis'],
    compoundId: 'egcg',
    outline: [
      'Overview & catechin spectrum',
      'Mechanism: DNMT1 inhibition + mTOR/PI3K suppression',
      'Evidence: Yang 2011 MolNutr + preclinical autophagy data',
      'Epigenetic effects: global DNA hypomethylation',
      'Dosing: 400–800 mg EGCG (decaffeinated, with food)',
      'Timing: AM, away from iron supplements',
      'Liver caution: EGCG hepatotoxicity at >800 mg/day',
      'Buyer guide: standardized catechin %',
    ],
    mdxSlug: 'egcg',
  },
  {
    slug: 'creatine',
    category: 'compounds',
    title: 'Creatine Monohydrate',
    tagline: 'ATP buffer and mitochondrial support — Tier A',
    summary:
      'Creatine phosphate system buffers ATP during high-demand periods, supports mitochondrial creatine kinase shuttle, reduces oxidative stress, and shows emerging cognitive and longevity benefits. Best-studied supplement in sports science with crossover longevity data.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'stem', 'intercell'],
    compoundId: 'creatine',
    outline: [
      'Overview & creatine phosphate system',
      'Mechanism: PCr shuttle + mitochondrial CK',
      'Evidence: Rawson 2011 meta-analysis + cognitive data',
      'Longevity crossover: muscle, bone, neuroprotection',
      'Dosing: 3–5 g/day creatine monohydrate (no loading)',
      'Who benefits most: vegetarians, >50 yo, cognitively active',
      'Monitoring: serum creatinine (expected rise)',
      'Buyer guide: creatine monohydrate vs HCl',
    ],
    mdxSlug: 'creatine',
  },
  {
    slug: 'tmg',
    category: 'compounds',
    title: 'TMG (Trimethylglycine / Betaine)',
    tagline: 'Methyl donor — homocysteine clearance and epigenetic support',
    summary:
      'Trimethylglycine donates methyl groups for homocysteine remethylation to methionine, supporting SAM pool for epigenetic maintenance. Critical co-supplement when using NMN/NR to counter methyl donor depletion.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['epigenetic', 'genomic', 'inflammation'],
    compoundId: 'tmg',
    outline: [
      'Overview & methyl donor hierarchy',
      'Mechanism: betaine-homocysteine methyltransferase (BHMT)',
      'Evidence: Olthof 2003 AJCN + Schwab 2002 metabolic data',
      'NMN/NR pairing: methyl drain and TMG as antidote',
      'Dosing: 500–1,000 mg/day TMG (with meals)',
      'Monitoring: homocysteine, SAM:SAH ratio',
      'Safety: fishy odor at high doses',
      'Buyer guide: betaine anhydrous vs betaine HCl',
    ],
    mdxSlug: 'tmg',
  },
  {
    slug: 'ashwagandha',
    category: 'compounds',
    title: 'Ashwagandha (KSM-66)',
    tagline: 'HPA axis adaptogen — cortisol and telomere protection',
    summary:
      'Withania somnifera root extract standardized to withanolides. Reduces cortisol 27% in RCTs, improves HRV, protects telomeres from stress-induced attrition, and shows anabolic effects on muscle and thyroid in multiple human trials.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['telomere', 'inflammation', 'stem', 'intercell'],
    compoundId: 'ashwagandha',
    outline: [
      'Overview & adaptogen classification',
      'Mechanism: HPA axis modulation + cortisol → DHEA ratio',
      'Evidence: Chandrasekhar 2012 JICM + Wankhede 2015 RCTs',
      'Telomere protection: stress → cortisol → telomere link',
      'Dosing: 300 mg KSM-66 × 2/day (AM + PM with food)',
      'Thyroid interaction: monitor TSH',
      'Monitoring: salivary cortisol, HRV, DHEA-S',
      'Buyer guide: KSM-66 vs Sensoril vs generic',
    ],
    mdxSlug: 'ashwagandha',
  },
  {
    slug: 'lions-mane',
    category: 'compounds',
    title: "Lion's Mane (Hericium erinaceus)",
    tagline: 'NGF inducer — neurogenesis and intercellular communication',
    summary:
      "Medicinal mushroom producing hericenones and erinacines that cross the blood-brain barrier to stimulate NGF (nerve growth factor) synthesis. Supports neurogenesis, myelination, and intercellular signaling in aging brains.",
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'stem'],
    compoundId: 'lions-mane',
    outline: [
      "Overview & hericenone/erinacine duality",
      'Mechanism: NGF induction → TrkA signaling',
      'Evidence: Mori 2009 Phytother Res RCT + animal neurogenesis',
      'Dual-extract requirement: fruiting body + mycelium',
      'Dosing: 500–1,000 mg 2× /day (standardized extract)',
      "Cognitive timeline: onset 4–8 weeks",
      'Monitoring: cognitive function tests, mood',
      'Buyer guide: beta-glucan % + erinacine testing',
    ],
    mdxSlug: 'lions-mane',
  },
  {
    slug: 'astaxanthin',
    category: 'compounds',
    title: 'Astaxanthin (AstaREAL)',
    tagline: 'Carotenoid antioxidant — mitochondrial membrane protector',
    summary:
      'Xanthophyll carotenoid spanning mitochondrial membrane bilayer to quench singlet oxygen and peroxyl radicals 6,000× more potent than vitamin C. AstaREAL is the only form with human clinical trial data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic', 'telomere'],
    compoundId: 'astaxanthin',
    outline: [
      'Overview & unique membrane-spanning structure',
      'Mechanism: singlet O2 quenching + NRF2 activation',
      'Evidence: Nir 2000 AJCN + Choi 2011 MSSE human data',
      'Why AstaREAL: only clinically validated form',
      'Dosing: 4–12 mg/day AstaREAL (with fat, AM)',
      'Synergy with CoQ10 and omega-3',
      'Monitoring: skin oxidative stress, hs-CRP',
      'Buyer guide: synthetic vs natural (haematococcus)',
    ],
    mdxSlug: 'astaxanthin',
  },
  {
    slug: 'lithium-orotate',
    category: 'compounds',
    title: 'Lithium Orotate (Low-dose)',
    tagline: 'Trace mineral neuroprotectant — GSK-3β inhibitor',
    summary:
      'At sub-prescription doses (1–5 mg elemental lithium), lithium orotate inhibits GSK-3β to promote neurogenesis, reduce tau phosphorylation, and increase gray matter volume. Epidemiological data links trace lithium in drinking water to reduced dementia mortality.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['intercell', 'inflammation', 'genomic'],
    compoundId: 'lithium-orotate',
    outline: [
      'Overview & trace vs therapeutic dose distinction',
      'Mechanism: GSK-3β inhibition → tau + neurogenesis',
      'Evidence: Nunes 2013 + Fiorentini 2021 epidemiology',
      'Low-dose vs prescription lithium carbonate',
      'Dosing: 1–5 mg elemental lithium orotate (PM)',
      'Population dose benchmark: water studies',
      'Monitoring: kidney function, thyroid (at doses >10 mg)',
      'Buyer guide: orotate vs carbonate, elemental calculation',
    ],
    mdxSlug: 'lithium-orotate',
  },
  {
    slug: 'collagen',
    category: 'compounds',
    title: 'Collagen Peptides (Verisol / Peptan)',
    tagline: 'Extracellular matrix support — skin, joints, gut integrity',
    summary:
      'Hydrolyzed collagen peptides provide substrates for ECM repair and signal fibroblasts to upregulate endogenous collagen synthesis. Verisol (skin) and Peptan (joint/bone) are the clinically validated branded forms with human RCT data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['stem', 'intercell', 'inflammation'],
    compoundId: 'collagen',
    outline: [
      'Overview & ECM decline with age',
      'Mechanism: peptide absorption → fibroblast signaling',
      'Evidence: Proksch 2014 Skin Pharmacol + Bello 2006 joint RCT',
      'Verisol vs Peptan vs generic hydrolyzed',
      'Dosing: 2.5–10 g/day with vitamin C (AM, fasted)',
      'Vitamin C co-requirement for hydroxylation',
      'Monitoring: skin elasticity, joint ROM scores',
      'Buyer guide: molecular weight, amino acid profile',
    ],
    mdxSlug: 'collagen',
  },
  {
    slug: 'melatonin',
    category: 'compounds',
    title: 'Melatonin (Extended-release)',
    tagline: 'Pineal chronobiotic — mitochondrial antioxidant at physiologic dose',
    summary:
      'Pineal hormone that synchronizes circadian rhythm, drives mitochondrial antioxidant defense (UCP3, MnSOD upregulation), and declines >80% by age 70. Extended-release form prevents pharmacologic spike and morning grogginess.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'inflammation'],
    compoundId: 'melatonin',
    outline: [
      'Overview & pineal gland decline with age',
      'Mechanism: MT1/MT2 → circadian + mitochondrial UCP3/MnSOD',
      'Evidence: Reiter 2013 + Tan 2016 mitochondrial antioxidant data',
      'Physiologic (0.3 mg) vs pharmacologic (5–10 mg) debate',
      'Dosing: 0.3–1 mg extended-release (30–60 min pre-sleep)',
      'Circadian light hygiene prerequisite',
      'Monitoring: sleep quality scores, morning temperature',
      'Buyer guide: extended-release vs immediate, purity',
    ],
    mdxSlug: 'melatonin',
  },

  // ── Synergies ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac-nrf2-triad',
    category: 'synergies',
    title: 'NRF2 Defense Triad',
    tagline: 'GlyNAC + Sulforaphane + R-ALA',
    summary:
      'The foundational TNiC NRF2 stack: glutathione substrate (GlyNAC), gene transcription (sulforaphane), and redox recycling (R-ALA) — three layers of antioxidant defense.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'proteostasis', 'inflammation'],
    synergyCompoundIds: ['glynac', 'sulforaphane', 'rala'],
    outline: [
      'Rationale: substrate + signal + recycle',
      'Mechanistic synergy map',
      'Evidence per compound + combination logic',
      'AM choreography & spacing',
      'Biomarker targets (GSH, oxLDL)',
      'Contraindications',
    ],
    mdxSlug: 'glynac-nrf2-triad',
  },
  {
    slug: 'nmn-resveratrol-sirt1',
    category: 'synergies',
    title: 'SIRT1 Activation Pair',
    tagline: 'NMN + Trans-Resveratrol',
    summary:
      'NAD+ provides the fuel; resveratrol activates the enzyme. Combined SIRT1 signaling drives mitochondrial biogenesis, epigenetic stability, and senescence resistance.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'senescence', 'nutrient'],
    synergyCompoundIds: ['nmn', 'resveratrol'],
    outline: [
      'Rationale: cofactor + activator',
      'SIRT1 mechanism deep-dive',
      'Trial data & PK considerations',
      'AM NMN / PM resveratrol timing',
      'Monitoring: NAD+ index',
      'When to skip resveratrol',
    ],
    mdxSlug: 'nmn-resveratrol-sirt1',
  },
  {
    slug: 'nad-mito-stack',
    category: 'synergies',
    title: 'NAD+ Mitochondrial Stack',
    tagline: 'NMN + Ca-AKG + Resveratrol',
    summary:
      'Triple-axis mitochondrial support: NAD+ restoration (NMN), TCA cycle & epigenetic cofactor (Ca-AKG), and sirtuin-driven biogenesis (resveratrol). Highest hallmark coverage combo.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'epigenetic', 'stem', 'genomic'],
    synergyCompoundIds: ['nmn', 'cakg', 'resveratrol'],
    outline: [
      'Rationale: energy + epigenetics + biogenesis',
      'Hallmark coverage matrix',
      'Evidence per leg',
      'Full-day dosing schedule',
      'Biomarker panel (NAD+, AKG)',
      'Cost & simplicity tiers',
    ],
    mdxSlug: 'nad-mito-stack',
  },

  // ── Lifestyle ──────────────────────────────────────────────────────────────
  {
    slug: 'exercise',
    category: 'lifestyle',
    title: 'Exercise',
    tagline: 'The intervention no compound can replace',
    summary:
      'Zone 2 aerobic base, resistance training, and VO2max work — mapped to mitochondrial biogenesis, senescence clearance, telomere maintenance, and nutrient sensing.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'senescence', 'telomeres', 'nutrient', 'inflammation', 'stem'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — sedentary vs trained vs deload',
      'Zone 2 vs HIIT vs resistance pyramid',
      'Weekly protocol template',
      'Lab tie-ins (hs-CRP, NAD+ index)',
      'Wearable signals (Zone 2, RHR, HRV)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'exercise',
  },
  {
    slug: 'sleep',
    category: 'lifestyle',
    title: 'Sleep',
    tagline: 'When repair happens — glymphatic, DNA, hormonal',
    summary:
      '7–9 hours with adequate slow-wave and REM sleep drives DNA repair, glymphatic clearance, growth hormone release, and cortisol normalization. Non-negotiable longevity pillar.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'proteostasis', 'inflammation', 'telomeres', 'communication'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — debt vs OSA vs stack timing',
      'Sleep architecture & repair windows',
      'Protocol: timing, light, temperature',
      'Lab tie-ins (hs-CRP, 8-OHdG)',
      'Wearable metrics (deep sleep, wake SD)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'sleep',
  },
  {
    slug: 'nutrition',
    category: 'lifestyle',
    title: 'Nutrition',
    tagline: 'Methyl donors, protein thresholds, and nutrient sensing',
    summary:
      'Protein adequacy for glycine/NAC synthesis, methyl donor support (B12, folate, choline), time-restricted eating, and low-glycemic patterns that modulate mTOR/AMPK.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'epigenetic', 'dysbiosis', 'inflammation', 'autophagy'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — TRE readiness vs methyl donors',
      'Macro framework (protein, fiber, polyphenols)',
      'Methyl donor checklist',
      'Lab tie-ins (hs-CRP, AKG)',
      'Wearable proxies (fiber, eating window)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'nutrition',
  },
  {
    slug: 'stress',
    category: 'lifestyle',
    title: 'Stress & Recovery',
    tagline: 'Cortisol, HPA axis, and inflammaging acceleration',
    summary:
      'Chronic stress accelerates telomere attrition, elevates hs-CRP, impairs sleep architecture, and diverts resources from repair to survival signaling.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['telomeres', 'inflammation', 'communication', 'genomic', 'senescence'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — acute stress vs HRV collapse',
      'HPA axis & cortisol curve',
      'HRV training & breathwork protocols',
      'Lab tie-ins (hs-CRP, GSH)',
      'Wearable signals (HRV, stress score)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'stress',
  },

  // ── Guides ──────────────────────────────────────────────────────────────
  {
    slug: 'testing-and-monitoring',
    category: 'guides',
    title: 'Testing & Monitoring Guide',
    tagline: 'What to test, when, and how to interpret',
    summary:
      'Comprehensive lab panel roadmap tied to TNiC biomarkers, hallmark risks, retest cadence, trend interpretation, and stack-adjustment triggers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'inflammation', 'epigenetic', 'proteostasis'],
    outline: [
      'Tier 1 baseline panel',
      'Tier 2 advanced panel',
      'Retest cadence & decision tree',
      'Interpretation playbook & compare block',
      'Stack-adjustment triggers + compare links',
      'Lab day checklist & CSV upload',
      'Hallmark → biomarker reference',
    ],
    mdxSlug: 'testing-and-monitoring',
  },
];

export function getModuleBySlug(category: LibraryModuleCategory, slug: string): LibraryModule | undefined {
  return libraryModules.find((m) => m.category === category && m.slug === slug);
}

export function getModulesByCategory(category: LibraryModuleCategory): LibraryModule[] {
  return libraryModules.filter((m) => m.category === category);
}

export function getAllModuleParams(): { slug: LibraryModuleCategory; moduleSlug: string }[] {
  return libraryModules.map((m) => ({ slug: m.category, moduleSlug: m.slug }));
}

export function getModulePath(module: LibraryModule): string {
  return `/library/${module.category}/${module.slug}`;
}