import type { NextUpItem } from './types';

/** Near-term functional improvements — distinct from long-horizon `roadmap` in data.ts */
export const nextUpImprovements: NextUpItem[] = [
  // Shipped (recent) — condensed highlights
  {
    id: 'library-batch-2',
    title: 'Full library elevation (12/12 hallmarks)',
    desc: 'All hallmark MDX modules at template standard.',
    status: 'shipped',
    sprint: 'Sprint 4–5',
    href: '/library',
    tags: ['content', 'library'],
  },
  {
    id: 'quiz-architect-handoff',
    title: '3-Min Quiz → Stack Architect handoff',
    desc: 'Dedicated /quiz, preset handoff, Builder tab auto-open.',
    status: 'shipped',
    sprint: 'Sprint 5',
    href: '/quiz',
    tags: ['conversion', 'os'],
  },
  {
    id: 'library-compare',
    title: 'Evidence comparison tables',
    desc: 'Six /library/compare routes with PMID anchors.',
    status: 'shipped',
    sprint: 'Sprint 6',
    href: '/library/compare',
    tags: ['library', 'tools'],
  },
  {
    id: 'protocol-shop',
    title: 'Protocol shop (affiliate, unbiased)',
    desc: 'Stack-filtered verification at /shop — zero inventory conflict.',
    status: 'shipped',
    sprint: 'Sprint 7',
    href: '/shop',
    tags: ['commerce', 'trust'],
  },
  {
    id: 'compare-og-sitemap',
    title: 'Compare OG images + search index',
    desc: 'OG cards for compare/brief/shop; library search indexes comparisons.',
    status: 'shipped',
    sprint: 'Sprint 8',
    href: '/library/compare',
    tags: ['seo'],
  },
  {
    id: 'lab-partner-api',
    title: 'Lab partner import (beta)',
    desc: 'Partner v1 CSV/JSON import, POST /api/labs/partner-import, Partner Beta tab on Labs hub.',
    status: 'shipped',
    sprint: 'Sprint 9',
    href: '/labs#partner-import',
    tags: ['labs', 'api'],
  },
  {
    id: 'lab-partner-api-live',
    title: 'Lab partner CSV auto-import API',
    desc: 'Stateless JSON normalizer live; OAuth order-at-home + webhook auto-pull Q3–Q4 2026.',
    status: 'shipped',
    sprint: 'Sprint 9',
    href: '/api/labs/partner-import',
    tags: ['labs', 'api'],
  },
  {
    id: 'brief-email-backend',
    title: 'Protocol Brief automated delivery',
    desc: 'RSS + JSON feeds at /brief/feed.xml; POST /api/brief/subscribe with optional webhook env.',
    status: 'shipped',
    sprint: 'Sprint 9',
    href: '/brief#brief-subscribe',
    tags: ['retention', 'api'],
  },
  {
    id: 'lab-partner-oauth',
    title: 'Lab partner OAuth order flow',
    desc: 'Demo OAuth connect, at-home panel orders, auto-import via /api/labs/partner/order + webhook.',
    status: 'shipped',
    sprint: 'Sprint 10',
    href: '/labs#lab-partner-oauth',
    tags: ['labs', 'api'],
  },
  {
    id: 'brief-resend-delivery',
    title: 'Native weekly email send (Resend)',
    desc: 'Resend audience subscribe + GET /api/cron/brief weekly digest — env-gated on deploy.',
    status: 'shipped',
    sprint: 'Sprint 10',
    href: '/brief#brief-subscribe',
    tags: ['retention', 'api'],
  },
  {
    id: 'lab-partner-live',
    title: 'Longevity Direct live OAuth',
    desc: 'Env-gated live partner OAuth, order proxy, status polling, and webhook order_id on panel complete.',
    status: 'shipped',
    sprint: 'Sprint 11',
    href: '/labs#lab-partner-oauth',
    tags: ['labs', 'api'],
  },
  {
    id: 'brief-digest-rotation',
    title: 'Brief issue rotation + unsubscribe',
    desc: 'ISO-week issue rotation in cron; signed one-click unsubscribe via GET /api/brief/unsubscribe.',
    status: 'shipped',
    sprint: 'Sprint 11',
    href: '/brief#brief-subscribe',
    tags: ['retention', 'api'],
  },
  {
    id: 'lab-partner-push',
    title: 'Lab order push notifications',
    desc: 'Webhook event poll + browser Notification on panel.complete; auto-import pending orders.',
    status: 'shipped',
    sprint: 'Sprint 12',
    href: '/labs#lab-partner-oauth',
    tags: ['labs', 'retention'],
  },
  {
    id: 'brief-welcome-email',
    title: 'Protocol Brief welcome email',
    desc: 'Instant Resend welcome on subscribe with rotating issue preview, RSS/JSON links.',
    status: 'shipped',
    sprint: 'Sprint 12',
    href: '/brief#brief-subscribe',
    tags: ['retention', 'api'],
  },
  {
    id: 'labs-export-partner',
    title: 'Export labs in partner v1 format',
    desc: 'Partner JSON export on Labs hub — latest panel as TNiC Partner v1 for re-import or handoff.',
    status: 'shipped',
    sprint: 'Sprint 13',
    href: '/labs',
    tags: ['labs', 'api'],
  },
  {
    id: 'shop-stack-deep-links',
    title: 'Shop stack deep links',
    desc: 'Shareable /shop?stack= URLs — preset keys or compound ids; copy link + deep-link banner.',
    status: 'shipped',
    sprint: 'Sprint 13',
    href: '/shop',
    tags: ['commerce', 'conversion'],
  },
  {
    id: 'compare-share-cards',
    title: 'Compare table share cards',
    desc: 'Copy link, social snippet, and markdown per compare route — OG-friendly share panel on hub + detail.',
    status: 'shipped',
    sprint: 'Sprint 14',
    href: '/library/compare',
    tags: ['seo', 'library'],
  },
  {
    id: 'dashboard-status-export',
    title: 'Dashboard status card export',
    desc: 'Copy/download markdown + canvas PNG snapshot of Longevity OS status for N=1 journaling.',
    status: 'shipped',
    sprint: 'Sprint 14',
    href: '/dashboard#dashboard-status',
    tags: ['os', 'retention'],
  },
  // Planned
  {
    id: 'quiz-result-share',
    title: 'Quiz result share card',
    desc: 'Copyable quiz outcome + preset deep link to /stacks and /shop for referral-style handoff.',
    status: 'shipped',
    sprint: 'Sprint 15',
    href: '/quiz',
    tags: ['conversion', 'seo'],
  },
  {
    id: 'trust-citation-export',
    title: 'Citation bundle export',
    desc: 'BibTeX/JSON export of PMID registry for researchers building on TNiC evidence index.',
    status: 'shipped',
    sprint: 'Sprint 15',
    href: '/trust',
    tags: ['trust', 'api'],
  },
  // Sprint 16
  {
    id: 'research-protocol-links',
    title: 'Research intel protocol links',
    desc: 'Every intel feed study links to hallmark modules, compound deep-dives, and stack presets.',
    status: 'shipped',
    sprint: 'Sprint 16',
    href: '/#research',
    tags: ['content', 'conversion'],
  },
  {
    id: 'quiz-share-og',
    title: 'Quiz share OG cards',
    desc: 'Per-preset /quiz/share/[preset] routes with dynamic OG images for social referral handoff.',
    status: 'shipped',
    sprint: 'Sprint 16',
    href: '/quiz/share/starter',
    tags: ['seo', 'conversion'],
  },
  {
    id: 'sitemap-sprint-16',
    title: 'Sitemap expansion',
    desc: 'Quiz share routes + delivery-systems library page indexed for discoverability.',
    status: 'shipped',
    sprint: 'Sprint 16',
    href: '/sitemap.xml',
    tags: ['seo'],
  },
  {
    id: 'compound-expansion-nr',
    title: 'NR vs NMN buyer guide expansion',
    desc: 'Deep-dive module + shop verification for nicotinamide riboside with updated compare table.',
    status: 'shipped',
    sprint: 'Sprint 17',
    href: '/library/compounds/nr',
    tags: ['content', 'library'],
  },
  {
    id: 'brief-research-sync',
    title: 'Brief ↔ Research intel sync',
    desc: 'Auto-rotate Protocol Brief issues from research feed PMIDs with compound cross-links.',
    status: 'shipped',
    sprint: 'Sprint 17',
    href: '/brief',
    tags: ['retention', 'content'],
  },
  {
    id: 'ui-overhaul-sprint-18',
    title: 'Premium UI overhaul + contextual clarity',
    desc: 'ContextRail what/why/next panels, card-premium surfaces, hero stat strip, section mesh backgrounds.',
    status: 'shipped',
    sprint: 'Sprint 18',
    href: '/',
    tags: ['ui', 'ux'],
  },
  {
    id: 'json-ld-compound-pages',
    title: 'Compound page JSON-LD',
    desc: 'MedicalWebPage + ScholarlyArticle citation schema on all compound deep-dives.',
    status: 'shipped',
    sprint: 'Sprint 18',
    href: '/library/compounds/nmn',
    tags: ['seo'],
  },
  {
    id: 'lifestyle-module-depth',
    title: 'Lifestyle pillar depth upgrade',
    desc: 'Hallmark matrices, graphical decision trees, lab deep-links, and Lifestyle Pillars hub on /library.',
    status: 'shipped',
    sprint: 'Sprint 19',
    href: '/library#lifestyle-pillars',
    tags: ['content', 'library'],
  },
  {
    id: 'labs-marker-deeplink',
    title: 'Labs marker deep-links from lifestyle modules',
    desc: '/labs?marker=hscrp&tab=input pre-selects biomarker from lifestyle pillar lab tie-ins.',
    status: 'shipped',
    sprint: 'Sprint 19',
    href: '/labs?marker=hscrp&tab=input',
    tags: ['labs', 'ux'],
  },
  {
    id: 'design-v3-cinematic',
    title: 'Design System v3 — cinematic UI escalation',
    desc: 'Ambient aurora layer, hero rings, card-ultra, btn-gradient, nav glass scroll state, hub shell mesh.',
    status: 'shipped',
    sprint: 'Sprint 20',
    href: '/',
    tags: ['ui', 'design'],
  },
  {
    id: 'hub-context-expansion',
    title: 'OS hub context rails — what/why/next everywhere',
    desc: 'Centralized hub-context for dashboard, stacks, labs, tools, shop, brief, learn, quiz, library, compare, and all 26 modules.',
    status: 'shipped',
    sprint: 'Sprint 21',
    href: '/dashboard',
    tags: ['content', 'ux'],
  },
  {
    id: 'per-tool-context',
    title: 'Per-tool contextual clarity',
    desc: 'Active tool tab shows dedicated what/why/next rail — simulator through defense scan.',
    status: 'shipped',
    sprint: 'Sprint 21',
    href: '/tools?tab=simulator',
    tags: ['content', 'tools'],
  },
  {
    id: 'trust-faq-contact-context',
    title: 'Trust, FAQ, contact & delivery-systems context rails',
    desc: 'ContextRail on /trust (per-tab), trust subpages, /faq, /contact, and /library/delivery-systems with PageHeader upgrade.',
    status: 'shipped',
    sprint: 'Sprint 22',
    href: '/trust',
    tags: ['content', 'trust', 'ux'],
  },
  {
    id: 'per-trust-tab-context',
    title: 'Per-trust-tab contextual clarity',
    desc: 'Active trust tab shows dedicated what/why/next rail — overview through update history.',
    status: 'shipped',
    sprint: 'Sprint 22',
    href: '/trust',
    tags: ['content', 'trust'],
  },
  {
    id: 'command-palette-v2',
    title: 'Command palette v2 — context-aware quick actions',
    desc: 'Palette surfaces hub context, recent modules, and stack-aware shortcuts from any page.',
    status: 'shipped',
    sprint: 'Sprint 23',
    href: '/dashboard',
    tags: ['ux', 'os'],
  },
  {
    id: 'research-intel-context',
    title: 'Research Intel contextual rails & feed filters',
    desc: 'Per-category what/why/next on Research Intel with hallmark and compound filter chips.',
    status: 'shipped',
    sprint: 'Sprint 23',
    href: '/#research',
    tags: ['content', 'research'],
  },
  {
    id: 'palette-recent-modules',
    title: 'Recent module tracking in command palette',
    desc: 'Library deep-dives log to localStorage; palette surfaces last 8 visited modules.',
    status: 'shipped',
    sprint: 'Sprint 23',
    href: '/library',
    tags: ['ux', 'library'],
  },
  {
    id: 'homepage-section-context',
    title: 'Homepage section context rails',
    desc: 'Dynamic what/why/next on compare row, brief capture rail, OS funnel, and research intel sections.',
    status: 'shipped',
    sprint: 'Sprint 24',
    href: '/',
    tags: ['content', 'ux'],
  },
  {
    id: 'nav-breadcrumb-context',
    title: 'Nav breadcrumb + hub context strip',
    desc: 'Persistent mini context strip under nav showing current hub next-step on all OS routes.',
    status: 'shipped',
    sprint: 'Sprint 37',
    href: '/dashboard',
    tags: ['ux', 'os'],
  },
  {
    id: 'gsc-verification-indexing',
    title: 'Google Search Console verification + indexing acceleration',
    desc: 'HTML file + meta tag verification, IndexNow submissions, HTML sitemap, and priority URL registry.',
    status: 'shipped',
    sprint: 'Sprint 27',
    href: '/site-map',
    tags: ['seo'],
  },
  {
    id: 'homepage-upconversion-rails',
    title: 'Homepage upconversion rails — Brief, Compare, stack deep links',
    desc: 'Brief email capture rail, six comparison cards, featured stack preset deep links, quiz Shop + Brief CTAs.',
    status: 'shipped',
    sprint: 'Sprint 29',
    href: '/',
    tags: ['conversion', 'ux'],
  },
  {
    id: 'sprint29-content-expansion',
    title: 'Sprint 29 content — 15 research items, 25 FAQs, 20 glossary terms',
    desc: 'GlyNAC 16-week RCT, NMN insulin sensitivity, sulforaphane CKD trial PMIDs; FAQ 21–25 + five glossary terms.',
    status: 'shipped',
    sprint: 'Sprint 29',
    href: '/faq',
    tags: ['content', 'research'],
  },
  {
    id: 'sprint31-research-competitors-biomarkers',
    title: 'Sprint 31 — researchFeed 18, competitors 8, biomarkers 8',
    desc: 'Ca-AKG/resveratrol/fisetin PMIDs, Examine/NOVOS/FoundMyFitness intel, IL-6 + Homocysteine markers, Clinical Studies pulse.',
    status: 'shipped',
    sprint: 'Sprint 31',
    href: '/#research',
    tags: ['content', 'research'],
  },
  {
    id: 'sprint32-personalization-products-polish',
    title: 'Sprint 32 — personalization rails, /products hub, graphical polish',
    desc: 'Intent-aware hero, return-visitor protocol rail, product picks catalog, preset-filtered research, Nav Quiz/Shop CTAs, stat-card trust.',
    status: 'shipped',
    sprint: 'Sprint 32',
    href: '/products',
    tags: ['conversion', 'ux'],
  },
  {
    id: 'sprint33-elite8-integration',
    title: 'Sprint 33 — Elite 8 LQ ranking + priority-upgrades cherry-pick',
    desc: 'Elite 8 Longevity Quotient at /elite-8, production health monitor workflow, Brief subscribe error hardening, tools hub promo.',
    status: 'shipped',
    sprint: 'Sprint 33',
    href: '/elite-8',
    tags: ['tools', 'integration'],
  },
  {
    id: 'sprint34-tier-b-compounds',
    title: 'Sprint 34 — Taurine, Spermidine, Pterostilbene Tier B expansion',
    desc: 'Three OTC compounds in data.ts + library MDX modules; hallmark autophagy/mito mappings; Elite 8 library links.',
    status: 'shipped',
    sprint: 'Sprint 34',
    href: '/library/compounds/taurine',
    tags: ['content', 'library'],
  },
  {
    id: 'sprint35-site-health-polish',
    title: 'Sprint 35 — Site health polish + safety coverage',
    desc: 'Tier B safety profiles, Elite 8 SSR scores, products library-only rail, biomarker mappings, self-heal route expansion.',
    status: 'shipped',
    sprint: 'Sprint 35',
    href: '/trust',
    tags: ['ux', 'fix'],
  },
  {
    id: 'sprint36-trust-indexing',
    title: 'Sprint 36 — Trust & indexing emergency',
    desc: 'Verified PMIDs, zero-commission copy unification, FAQ/lab stale counts, Tier B dashboard library links.',
    status: 'shipped',
    sprint: 'Sprint 36',
    href: '/trust/methodology',
    tags: ['trust', 'seo'],
  },
  {
    id: 'sprint37-ssl-hardening',
    title: 'Sprint 37.1 — SSL & transport security hardening',
    desc: 'HTTPS+apex middleware, HSTS preload in next.config, Trust transport-security disclaimer, self-heal HTTP/HSTS monitors.',
    status: 'shipped',
    sprint: 'Sprint 37.1',
    href: '/trust/disclaimers',
    tags: ['trust', 'security'],
  },
  {
    id: 'sprint37-visual-transcend',
    title: 'Sprint 37 — Material visual transcend + hub context strip',
    desc: 'Breadcrumb + hub next-step in ContextBar on all OS routes; gradient CTA finale, backdrop-blur library cards, anti-CTA-fatigue Browse Library path.',
    status: 'shipped',
    sprint: 'Sprint 37',
    href: '/',
    tags: ['ui', 'ux'],
  },
  {
    id: 'sprint38-synergy-network-aging-ticker',
    title: 'Sprint 38 — Compound Synergy Network + Biological Age Ticker',
    desc: 'Interactive SVG network graph (14 compounds, 23 edges, 5 pathways) on homepage. Real-time dual-rate biological age ticker in hero using requestAnimationFrame. Both with depth: glow filters, tier badges, hover tooltips, smooth ms-precision animation.',
    status: 'shipped',
    sprint: 'Sprint 38',
    href: '/',
    tags: ['ui', 'visualization'],
  },
  {
    id: 'sprint39-quiz-persistence-dashboard-goals',
    title: 'Sprint 39 — Quiz persistence, NMN vs Spermidine comparison, new goal labels',
    desc: 'Quiz result saved to PlatformContext on completion. Dashboard and OS funnel handle longevity + metabolic goals. 9th comparison table (NMN vs Spermidine). Comparison row copy dynamicized. Elite 8 cross-links to stack + compare pages.',
    status: 'shipped',
    sprint: 'Sprint 39',
    href: '/library/compare',
    tags: ['content', 'ux'],
  },
  {
    id: 'sprint40-shop-intelligence-complete',
    title: 'Sprint 40 — Complete shop intelligence for all 14 compounds',
    desc: 'Buyer guides (COA checklists, dose anchors, red flags) for all 8 previously missing compounds. All 14 compounds in compoundModuleMap. Shop preset filter shows all 7 presets. Timing logic corrected per compound. MDX sections 5-8 added to taurine, spermidine, pterostilbene.',
    status: 'shipped',
    sprint: 'Sprint 40',
    href: '/shop',
    tags: ['content', 'products'],
  },
  {
    id: 'sprint41-stack-analysis-complete',
    title: 'Sprint 41 — Stack analysis complete for all 14 compounds',
    desc: 'compoundBaseScores, synergyPairMatrix, compoundMonthlyCost, and stackInteractions updated for all 8 new compounds. hallmarkDisplayNames now covers all 11 hallmarks (autophagy, nutrient sensing, intercellular comm., telomeres). Goal labels fixed across DashboardHubHero and UserNextStepsPanel.',
    status: 'shipped',
    sprint: 'Sprint 41',
    href: '/stacks',
    tags: ['tools', 'content'],
  },
];

export const nextUpByStatus = {
  shipped: nextUpImprovements.filter((i) => i.status === 'shipped'),
  in_progress: nextUpImprovements.filter((i) => i.status === 'in_progress'),
  planned: nextUpImprovements.filter((i) => i.status === 'planned'),
} as const;

export function getNextUpHighlights(limit = 4): NextUpItem[] {
  const priority = [...nextUpByStatus.in_progress, ...nextUpByStatus.planned];
  return priority.slice(0, limit);
}